### ISSUE TITLE
Cannot read property '_sodium_init' of undefined - Using libsodiumjs with requirejs 

### ISSUE THREAD

**Issue by jmbm1989** [jedisct1/libsodium.js#10]
When I use libsodiumjs with requirejs i get the following error: 

          "Uncaught TypeError: Cannot read property '_sodium_init' of undefined(anonymous function) @ libsodium-wrappers.js:20context.execCb @ require.js:1665Module.check @ require.js:874(anonymous function) @ require.js:1121(anonymous function) @ require.js:132(anonymous function) @ require.js:1171each @ require.js:57Module.emit @ require.js:1170Module.check @ require.js:925Module.enable @ require.js:1158Module.init @ require.js:782callGetModule @ require.js:1185context.completeLoad @ require.js:1579context.onScriptLoad @ require.js:1686"

the way that i am using it is:
![requiretest-html](https://cloud.githubusercontent.com/assets/3846058/7595211/0d1de8d8-f8bc-11e4-8aa3-ed80db4267e5.png)

![main-js](https://cloud.githubusercontent.com/assets/3846058/7595220/15ffc214-f8bc-11e4-9393-50362c85ea82.png)

![test-js](https://cloud.githubusercontent.com/assets/3846058/7595231/2036f658-f8bc-11e4-94b1-8a3983140484.png)

When i run it i get the error thar i mention:

![error](https://cloud.githubusercontent.com/assets/3846058/7595241/2c2822c0-f8bc-11e4-8aaa-e8052e8dafb8.png)

**Comment by jmbm1989** [comment]
the problem, as i can see, is on the libsodium module, i don't know why but it cannot be loaded.

**Comment by jmbm1989** [comment]
in define(["libsodium"], factory); it doesn't load the libsodium module.

**Comment by jedisct1** [comment]
Looks like Emscripten doesn't play well with AMD.
As a quick workaround, add:

    define("libsodium",function(){var Module={}

as the first line of `libsodium.js` and

    return Module})

as the last line.

**Comment by jedisct1** [comment]
Can you try the current code (in Git, I haven't pushed it to Bower yet)?

AMD support should hopefully be fixed, and I also added support for ES6 modules.

**Comment by jmbm1989** [comment]
Yes, now it works!

**Comment by jedisct1** [comment]
Great, thanks!

I'm gonna push a new version to bower.
