### ISSUE TITLE
Compile wasm using async API.

### ISSUE THREAD

**Issue by creationix** [jedisct1/libsodium.js#100]
Since chrome blocks sync compiling the wasm on the main thread can we switch to the async compile API which should work better?  We've already got an onready style callback so it shouldn't change any APIs right?

**Comment by jedisct1** [comment]
Hi!

I don't remember the details, but this is something I initially tried, but miserably failed to achieve.
But a pull request to implement this without breaking the rest would be awesome :)

**Comment by jedisct1** [comment]
Superseded by #105
