### ISSUE TITLE
pickparams for scrypt

### ISSUE THREAD

**Issue by Jaaap** [jedisct1/libsodium.js#102]
As referenced in https://github.com/jedisct1/libsodium/issues/601 i'd like to use pickparams.
Is it possible to make this available in libsodium.js?

**Comment by jedisct1** [comment]
Probably not, as this is an internal function, and scrypt is not really recommend any more since the high-level API uses Argon2 instead.

**Comment by jedisct1** [comment]
But that function is pretty trivial to rewrite in Javascript or in whatever language you want to use your other scrypt implementation with.

**Comment by Jaaap** [comment]
I've been trying everything but i cannot figure out how to get it to
p=1, N=512 and r=256
Is this even possible?

**Comment by jedisct1** [comment]
Right now, libsodium.js doesn't work at all.

**Comment by jedisct1** [comment]
`r` is fixed to `8`, so you wont be able to find any `opslimit`, `memlimit` tuple that changes it to something else.

**Comment by jedisct1** [comment]
Looks like the idea setting `r` to 256 comes from SQRL, but that is a terrible choice. And another good reason to never expose these parameters individually.

**Comment by Jaaap** [comment]
Oh is 256 not a good value for r?

**Comment by jedisct1** [comment]
Unless you own a novel type of dynamic memory that no one ever heard about, you're just wasting resources and eventually compute a weaker hash that you could.

**Comment by Jaaap** [comment]
I think the objective is to protect against future ASICs that are onlikely to have 16M of fast cache.

**Comment by jedisct1** [comment]
That's not what `r` is for.

**Comment by jedisct1** [comment]
Good write-up on this: https://stackoverflow.com/questions/11126315/what-are-optimal-scrypt-work-factors#answer-30308723
