### ISSUE TITLE
how to use it in vue?

### ISSUE THREAD

**Issue by zhongzi** [jedisct1/libsodium.js#104]
can u give a example for me ? thanks !
(1)  npm install libsodium-wrappers
(2)  use in Vue project like:
     var sodium = require('libsodium-wrappers')
      console.log(sodium.to_hex(sodium.crypto_generichash(64, 'test')))
(3) npm run dev 

then i got:
---
This dependency was not found:

* fs in ./~/.0.5.4@libsodium/dist/modules/libsodium.js

To install it, you can run: npm install --save fs
> Listening at http://localhost:8080
---

it's useless to install fs module

any body help me ? 
thanks!

**Comment by jedisct1** [comment]
You probably need "libsodium" in addition to "libsodium-wrappers".

**Comment by jedisct1** [comment]
Superseded by #105

**Comment by zhongzi** [comment]
Anyway，Thank you all the same. 
Great projects.
