### ISSUE TITLE
0.7.0 upgrade privateKey is not defined

### ISSUE THREAD

**Issue by bufke** [jedisct1/libsodium.js#112]
Hello, I'm trying to upgrade to 0.7.0. I'm getting an error with this test case:

```
it("test crypto_box_keypair", async () => {
    await sodium.ready;
    let pair = sodium.crypto_box_keypair();
});
```

I get ReferenceError: privateKey is not defined. I installed via npm and am running jasmine tests with webpack dev server (which was all previously working). I also noticed my import no longer works without installing both the sumo and non-sumo wrappers. Previously I only needed sumo and it all worked. I'll keep poking around to see if I can figure out what's going on.

**Comment by bufke** [comment]
This file was recently changed - I'm not exactly sure how these json files work. 

https://github.com/jedisct1/libsodium.js/commit/e6ce43ca0808f78d759ea05bae4e742c1ded27ad#diff-664280394ce59295aec1953ba0a2c4b7

Is it possible the use of secretKey and privateKey variables has caused a mismatch?

**Comment by jedisct1** [comment]
Indeed.

The secret key being sometimes called "secretKey" and sometimes "privateKey" is messy and confusing. And lead to this.

It should be fixed now. Thanks!
