### ISSUE TITLE
sodium.crypto_pwhash is not a function

### ISSUE THREAD

**Issue by bufke** [jedisct1/libsodium.js#113]
I'm also having trouble using sumo functions. 

```
    it("test hash", async () => {
        const _sodium = require('libsodium-wrappers-sumo');
        await _sodium.ready;
        const password = "hunter2";
        const salt = new Uint8Array([88, 240, 185, 66, 195, 101, 160, 138, 137, 78, 1, 2, 3, 4, 5, 6]);
        const hash = _sodium.crypto_pwhash(
            _sodium.crypto_box_SEEDBYTES,
            password,
            salt,
            _sodium.crypto_pwhash_OPSLIMIT_INTERACTIVE,
            _sodium.crypto_pwhash_MEMLIMIT_INTERACTIVE,
            _sodium.crypto_pwhash_ALG_DEFAULT,
        );
    });
```

I get sodium.crypto_pwhash is not a function. I see there is a note about totalMemory but how would I go about setting this?

**Comment by jedisct1** [comment]
May it be because it loads the wrong "libsodium" module, and loads the one from the non-sumo directory instead?

**Comment by buu700** [comment]
It looks like modules-sumo/libsodium-wrappers.js isn't actually including all the sumo exports. I can find the string `crypto_pwhash:` in the browser version, but not the module version.

**Comment by buu700** [comment]
It looks like the problem is that modules-sumo/libsodium-wrappers.js is requiring `libsodium` instead of `libsodium-sumo`.

**Comment by bufke** [comment]
Fantastic and thank you! I owe @jedisct1 and other libsodium contributors a beer if you are ever in NYC. All my unit tests involving libsodium.js 0.7.x are now passing with web assembly!
