### ISSUE TITLE
Change to from_base64 default?

### ISSUE THREAD

**Issue by bufke** [jedisct1/libsodium.js#114]
In <0.7.0 this code works

```
    it("test base64", () => {
        const testB64 = "2A28PjsDW/WpQqMXPLTIkL99VwnofGRqNL7wdJrzUyo=";
        const result = sodium.from_base64(testB64);
        console.log(result);
    });
```

The result is a Uint8Array [216, 13, 188, 62, 59, 3, 91, 245, 169, 66, 163, 23, 60, 180, 200, 144, 191, 125, 87, 9, 232, 124, 100, 106, 52, 190, 240, 116, 154, 243, 83, 42]

In 0.7.0 this gives me Error: invalid input. Changing it to `sodium.from_base64(testB64, 1);` however fixes it and gives the same (correct) result. Was something changed here? Also is there a smarter way to input the second param instead of `1`?

**Comment by jedisct1** [comment]
The second parameter has to be one of
`base64_variants.ORIGINAL`, `base64_variants.ORIGINAL_NO_PADDING`, `base64_variants.URLSAFE` or `base64_variants.URLSAFE_NO_PADDING`.

The default is `base64_variants.URLSAFE_NO_PADDING`.

In < 0.7.0, the base64 parser was not strict enough, which could be dangerous.
