### ISSUE TITLE
crypto_sign() and crypto_sign_open()

### ISSUE THREAD

**Issue by Edwardzyc** [jedisct1/libsodium.js#116]
When crypto_sign_open() tries to check the signed message and you give it the wrong public key - it errors out with

Uncaught Error: incorrect usage

Shouldn't it return 0 or -1 according to the documentation @ https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html

Under what conditions would a verification fail? Will this function always return the message or error out? If this is an issue - I can take a look at it (or maybe I am using the library wrong?)

**Comment by jedisct1** [comment]
This message means that the key doesn't have the correct size, so it's not the wrong public key, it's not a key at all.

**Comment by jedisct1** [comment]
Sample usage:

```js
  let keypair = sodium.crypto_sign_keypair();
  let [pk, sk] = [keypair.publicKey, keypair.privateKey];
  let signed = sodium.crypto_sign(sodium.from_string("message"), sk);
  let unsigned = sodium.crypto_sign_open(signed, pk);
```

**Comment by jedisct1** [comment]
Oh, you're right, it throws an exception. I'm not sure that this is the intended behavior indeed :/

**Comment by jedisct1** [comment]
Looks like the purpose of the `expect` property in a json definition is to throw an 'incorrect usage' exception.

Ah. I wouldn't have expected something called `expect` to do that. That thing is probably used incorrectly in many places, such as `crypto_box_open()` and other decryption/verification functions.

**Comment by jedisct1** [comment]
How do people use that library? Is an exception what we should throw in such a situation or would it be better to return `null`?

**Comment by jedisct1** [comment]
`expect` should probably be renamed `assert`.

**Comment by Edwardzyc** [comment]
I'll test the update later this weekend and give my thoughts. 

I personally think it would be best to stick as close as possible to the [documentation](https://download.libsodium.org/doc/public-key_cryptography/public-key_signatures.html) since there isn't really documentation for the JS version. 

That would mean returning 0 and -1 (or the equivalent js convention) to denote whether  the verify succeeded or failed. The alternative could be to document this exception behavior for users.

**Comment by jedisct1** [comment]
The upside of exceptions is that they can't be silently ignored. Returning `0` or `-1` is also not very intuitive for Javascript code.

The Javascript bindings need some real documentation no matter what. There is a script to automatically generate one from the prototypes, but it's not a real documentation, with explanations and examples.

That's on my todo list.

**Comment by buu700** [comment]
This definitely seems more like a documentation issue than an actual flaw in the API to me (present error message content aside). I think this could be effectively handled by finishing #80, putting in `@see` tags with links to relevant libsodium doc pages where relevant (and maybe `@param`/`@returns` tags in some cases to explain non-obvious differences from the C API), and hosting the output of a tool like [Compodoc](https://github.com/compodoc/compodoc) or [TypeDoc](https://github.com/TypeStrong/typedoc) somewhere.
