### ISSUE TITLE
What should be client's behaviour when server restarts ?

### ISSUE THREAD

**Issue by miteshjadia** [jedisct1/libsodium.js#118]
I was going through "dnscrypt-proxy" code which runs on client side and found that It tries to re-fetch certificate at the interval of one hour.

Below are the doubts. 

1) What should be effective expiry duration of certificates generated on dnscrypt-server?
    If it is less than an hour, should there be a logic on client side to re-fetch certificate before few seconds of current certificates expiry ?

2) What if server restarts at some point where client were already leased certificates ?
    As of now dnscrypt-proxy (client) will still try to do communication using negotiated <mkey>, which will fail at server. Should there be any certificate re-fetch event after few consecutive exceptions ?

**Comment by jedisct1** [comment]
Wrong repository. This one is about a Javascript/Webassembly crypto library, that has nothing to do with dnscrypt.

The dnscrypt protocol is documented here: https://github.com/jedisct1/dnscrypt-proxy/blob/master/DNSCRYPT-V2-PROTOCOL.txt . See the "Operational perspective" section in particular.
