### ISSUE TITLE
Values differ from "sodium-native"

### ISSUE THREAD

**Issue by vladimiry** [jedisct1/libsodium.js#119]
I didn't compare all the values, but this is a simple example to demo the difference:
```diff
--- 1-sodium-native.txt	2017-10-28 11:54:40.406066833 +0300
+++ 2-libsodium-wrappers-sumo.txt	2017-10-28 11:55:56.628061469 +0300
@@ -1,16 +1,16 @@
 crypto_pwhash_ALG_ARGON2I13: 1,
-crypto_pwhash_ALG_DEFAULT: 1,
+crypto_pwhash_ALG_DEFAULT: 2,
 crypto_pwhash_BYTES_MIN: 16,
-crypto_pwhash_BYTES_MAX: 4294967295,
+crypto_pwhash_BYTES_MAX: -1,
 crypto_pwhash_PASSWD_MIN: 0,
-crypto_pwhash_PASSWD_MAX: 4294967295,
+crypto_pwhash_PASSWD_MAX: -1,
 crypto_pwhash_MEMLIMIT_MIN: 8192,
-crypto_pwhash_MEMLIMIT_MAX: 4398046510080,
-crypto_pwhash_MEMLIMIT_SENSITIVE: 536870912,
-crypto_pwhash_MEMLIMIT_INTERACTIVE: 33554432,
-crypto_pwhash_MEMLIMIT_MODERATE: 134217728,
-crypto_pwhash_OPSLIMIT_MIN: 3,
-crypto_pwhash_OPSLIMIT_MAX: 4294967295,
-crypto_pwhash_OPSLIMIT_SENSITIVE: 8,
-crypto_pwhash_OPSLIMIT_INTERACTIVE: 4,
-crypto_pwhash_OPSLIMIT_MODERATE: 6,
+crypto_pwhash_MEMLIMIT_MAX: -2147483648,
+crypto_pwhash_MEMLIMIT_SENSITIVE: 1073741824,
+crypto_pwhash_MEMLIMIT_INTERACTIVE: 67108864,
+crypto_pwhash_MEMLIMIT_MODERATE: 268435456,
+crypto_pwhash_OPSLIMIT_MIN: 1,
+crypto_pwhash_OPSLIMIT_MAX: -1,
+crypto_pwhash_OPSLIMIT_SENSITIVE: 4,
+crypto_pwhash_OPSLIMIT_INTERACTIVE: 2,
+crypto_pwhash_OPSLIMIT_MODERATE: 3,
```
![difference-demo](https://user-images.githubusercontent.com/1560781/32133032-627de314-bbd8-11e7-9000-bf252cb5a018.png)

Used versions:
- "sodium-native": "1.10.3",
- "libsodium-wrappers-sumo": "0.7.2",
- "electron": "1.8.2-beta.1",
- Node.js v8.8.0
- npm 5.5.1

**Comment by vladimiry** [comment]
I understand that values used for key deriving should be saved during deriving and reused then, but such difference still does look weird. For example there is only one algorithm supported which is `crypto_pwhash_ALG_ARGON2I13=1`, but `crypto_pwhash_ALG_DEFAULT=2` for some reason.

**Comment by jedisct1** [comment]
Fixed in e9722026f195e16f60551680af5deaf02732a3ba :)

**Comment by vladimiry** [comment]
Thanks, please keep in mind I simply highlighted the possible issue, with limited demo, means the issue potentially might be bigger than it seems.

**Comment by jedisct1** [comment]
Looks fine to me. sodium-native is probably just using an old libsodium version.

**Comment by vladimiry** [comment]
Right, it looks like sodium-native@1.10.3 comes with libsodium 1.0.12, not the 1.0.15.
