### ISSUE TITLE
Should crypto_pwhash_BYTES_MAX be -1?

### ISSUE THREAD

**Issue by Edwardzyc** [jedisct1/libsodium.js#121]
sodium.crypto_pwhash(sodium.crypto_pwhash_BYTES_MAX)
TypeError: keyLength must be an unsigned integer

Using crypto_pwhash_BYTES_MAX in the crypto_pwhash function throws an error as seen above.
Is it user error?

**Comment by jedisct1** [comment]
That was fixed a while back in d6f8c8f628f0084798235e48534eb9d6f0fa0493

There won't be any new release until version 1.0.16 of libsodium is out, but you can use the generated files from this repository meanwhile.

**Comment by Edwardzyc** [comment]
Thanks for confirming that for me.
