### ISSUE TITLE
Can't anyhow compile it

### ISSUE THREAD

**Issue by pzduniak** [jedisct1/libsodium.js#122]
Having issues with all Node.js bindings, so I think it's somethign with libsodium itself. Currently trying on Alpine (but Debian didn't work either). Deps are as following:

```RUN apk add --update --no-cache git make libtool autoconf automake gcc g++ libsodium libsodium-dev binutils build-base```

And the error is:

```make[3]: *** No rule to make target 'crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S', needed by 'crypto_stream/salsa20/xmm6/libsodium_la-salsa20_xmm6-asm.lo'.  Stop.
make[3]: Leaving directory '/app/node_modules/sodium-native/libsodium/src/libsodium'
make[2]: *** [Makefile:2925: install-recursive] Error 1
make[2]: Leaving directory '/app/node_modules/sodium-native/libsodium/src/libsodium'
make[1]: *** [Makefile:397: install-recursive] Error 1
make[1]: Leaving directory '/app/node_modules/sodium-native/libsodium/src'
make: *** [Makefile:511: install-recursive] Error 1```

**Comment by jedisct1** [comment]
Hi!

`libsodium.js` is already compiled. You can simply use `npm` to add it to your project.

`sodium-native` is a different project: https://github.com/sodium-friends/sodium-native
I'm aware of it but I've never used it, so I can't really help.

**Comment by pzduniak** [comment]
God damn it, I accidentally removed the first line. It's an issue with the C project libsodium. The JS version won't help because I want to use its argon2 impl.

`make[3]: *** No rule to make target 'crypto_stream/salsa20/xmm6/salsa20_xmm6-asm.S', needed by 'crypto_stream/salsa20/xmm6/libsodium_la-salsa20_xmm6-asm.lo'.  Stop.`

**Comment by pzduniak** [comment]
And I created the issue in the wrong project. I need to sleep...
