### ISSUE TITLE
Decrypt before validation signature with `crypto_box_*`

### ISSUE THREAD

**Issue by creationix** [jedisct1/libsodium.js#123]
I'm wondering if there is a way to decrypt a `crypto_box` without first knowing the sender's public key.  I'm sending the public key as part of the payload as a way for clients to authenticate to servers.  

I can't have the public key out in the open because my servers can easily be impersonated (through invalid DHT peers or DNS hacks).  I don't want my client's public keys leaked.

If it's possible to decrypt the payload, extract the public key of the sender, and then validate the authentication tag, that would be perfect.

**Comment by jedisct1** [comment]
The answer is no, unless you already have a copy of the shared secret.

Maybe what you can do is encrypt the message + the public key with a shared key (using `secretbox` or some AEAD), and append a signature of these. Then, decrypt the message and the public key, and use that key to check that the signature is valid.

But that's pretty unusual. Public keys are really meant to be public. Are you then checking public keys against a trusted list? If not, there is no point in having an authentication tag. If you do, this is still quite a fragile protocol.

**Comment by creationix** [comment]
So the point of my authentication is to prove that someone is the owner of the public key.  It's their identity basically.  The services will be checking the public keys against internal ACL lists.

But thanks for your answer.  I had forgotten exactly how the encryption was constructed (still had my brain in old-school RSA encrypt + sign)

**Comment by creationix** [comment]
Maybe I should back up and explain what I'm trying to design.

I want clients to be able to connect to servers in a variety of ways including DHT.  This means that once connected to a server, it's not authenticated at all and could easily be an impostor.

My clients know the server's public key beforehand and trusts it is the correct public key.  

The server has internal ACLs that are keyed by client public keys.  So I need clients to authenticate themselves.

The connection itself needs to be encrypted.  I was thinking stream ciphers using key exchange to get the shared keys would work well.

While public keys tend to be public in PK systems, I want some amount of privacy.  For example, when a client does a lookup for a server's public key, the discovery key used in the DHT network is actually a blake2b hash of the server's public key.  Thus the server's "public" key is about as public as unlisted github gist urls.  Clients can also be servers themselves in other contexts and generally don't want their identity broadcast to the whole world.

I could start out by having the client send it's public key to the server, but encrypted in a sealed box that only an authentic server can read.

Then I need some secure way to mutually authenticate the peers and upgrade to stream encryption.

What do you propose?  Am I totally crazy?

**Comment by creationix** [comment]
Also for the stream encryption, I'll probably be using something TCP-like which is reliable an ordered.  The RPC messages themselves will be framed somehow if that matters.

Another option is to go completely stateless and just have messages be normal `crypto_box` messages addressed to the server.  Only problem is how does the server know which public key to use to verify the signature?  I guess I could serialize a request, sign it using the client's key, and then send it to the server in a sealed box.  But that seems overly complicated and there is a better solution.
