### ISSUE TITLE
Please publish 0.7.3

### ISSUE THREAD

**Issue by deweller** [jedisct1/libsodium.js#124]
I am unable to install the newest version directly from github using npm.  Can you publish a new version with the updated libsodium version?

Thanks.

**Comment by jedisct1** [comment]
Errr... the new libsodium version hasn't been released yet, and the Javascript version hasn't been tested at all. Give them some time :)

**Comment by deweller** [comment]
I thought this library was not up to date.  My mistake.

Thanks for the response.

**Comment by jedisct1** [comment]
In case you want to help, this is currently a blocker: https://github.com/kripken/emscripten/issues/5925
