### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by buu700** [jedisct1/libsodium.js#127]
I'm seeing what looks like a recent regression that's causing a memory leak. I don't have a good isolated test to share, but I get the following error consistently after every 13 iterations of a loop that uses `crypto_generichash`, `crypto_pwhash`, `crypto_aead_xchacha20poly1305_ietf`, and `crypto_box_curve25519xchacha20poly1305`:

`Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0`

This happens with a build of libsodium.js from December 27 that includes my PR https://github.com/jedisct1/libsodium/pull/653, and the previous build I was using that didn't have this problem was from October 18, so the root cause must be that PR and/or a change to libsodium(.js) or emscripten between those two dates.

I haven't closely followed the other recent commits, but the enabling of Closure in that PR seems like a plausible cause; I'll test that after a new build with `crypto_box_curve25519xchacha20poly1305` is generated. After that, my best guess would be a general regression in emscripten, since it seems like an odd thing for a libsodium change to cause.

**Comment by jedisct1** [comment]
I uploaded a new build without Closure (which doesn't seem to be saving much anyway).
Can you give it a spin?

**Comment by buu700** [comment]
Oh, hm, it looks like this is actually being caused by a different module. I was pretty sure Node's stack track said libsodium last night, but maybe I just misread something. Sorry about that!

Closing this for now, and I'll reopen if it turns out that something needs to be fixed here too.

(I suppose disabling Closure for now isn't a bad idea anyway, for the reasons you pointed out earlier.)

**Comment by buu700** [comment]
Okay yeah, this was an issue in one of my libraries (mceliece.js), not libsodium.js. Apparently emscripten doesn't consistently export malloc and free if they aren't explicitly included in the export list (which I see they are in libsodium's build script), so by chance the most recent build was just leaking all of its memory.
