### ISSUE TITLE
[off-topic, C language] about low-level scrypt API

### ISSUE THREAD

**Issue by barron9** [jedisct1/libsodium.js#129]
i am using this function with the parameters like this and i get error

```
  const uint8_t * salt = "cd7c9xxxxxxxxx6cc70b30407ade5e";
        uint64_t  N=8192; uint32_t  r=8; uint32_t p=1; 
        

        **uint8_t * buf ; //?? i tried with buf = null and buf length 0 but i need 32 dklen! what is buf is for?**
        uint8_t passwd = "111111111";
       int aa= crypto_pwhash_scryptsalsa208sha256_ll(&passwd, sizeof passwd,
                                              salt, sizeof salt,
                                              N, r, p, NULL,32
                                                     );
```

what if buf for? in the docs? https://download.libsodium.org/doc/password_hashing/scrypt.html

**Comment by jedisct1** [comment]
This is the wrong project. This project is a Javascript library, your code looks like C. Whatever.

Can you post the source code of a complete function, that actually compiles?

**Comment by jedisct1** [comment]
I would also recommend using `-Wall -W`, or with a modern compiler, `-Weverything` when compiling your code.

If you see compilation errors with these flags, your code has issues with the syntax of the C language itself, unrelated to the libraries you are using.

**Comment by barron9** [comment]
oh yes, here is js sorry, but this c code gets extra parameters then the js. 

btw this is all code i am using.

starts with

```
#include <sodium.h>

int main(void) {
    if (sodium_init() < 0) {
        /* panic! the library couldn't be initialized, it is not safe to use */
    }
```
its not about linking, it compiles with other fuctions, i am just asking what is "buf" for here

**Comment by jedisct1** [comment]
I have no idea what `buf` is, since it's not used anywhere in the few lines you copied, and the declaration-like line it appears would not compile as it doesn't make any sense in C.

**Comment by barron9** [comment]
![aasddd](https://user-images.githubusercontent.com/27488285/35366266-94dc3e72-0189-11e8-8134-5af1f52699a4.png)

ok, when i pass null it works,anyway

**Comment by jedisct1** [comment]
You need to fix all the things in yellow (which are not enough, there are more errors here. The built-in static analyzer will give you more hints).

These are errors with the C language. Before using such a library, I would recommend learning the basics of the C language.

What the types are, how to use arrays, how strings work, how to get the length of a string.

This will help you a lot for the rest of your project.

But since you're apparently writing something for macOS, you don't have to use C. You can use Swift: https://github.com/jedisct1/swift-sodium

There's no scrypt there, though, but if your intent is to store password, it will work.

**Comment by barron9** [comment]
did you check the doc ? https://download.libsodium.org/doc/password_hashing/scrypt.html
i just need to check a pass with a correspondng salt.
Low-level scrypt API

> The traditional, low-level scrypt API is also available:
> int crypto_pwhash_scryptsalsa208sha256_ll(const uint8_t * passwd, size_t passwdlen,
>                                           const uint8_t * salt, size_t saltlen,
>                                           uint64_t N, uint32_t r, uint32_t p,
>                                           uint8_t * buf, size_t buflen);
> Please note that r is specified in kilobytes, and not in bytes as in the Sodium API.

**Comment by jedisct1** [comment]
Sorry, I can't help you.

You question is unrelated to this project, and your actual issues have nothing to do with libsodium either. 

You need to learn the basics of the language you are using. For example, `sizeof` doesn't return the length of a string. Try to understand the warnings the compiler prints.
