### ISSUE TITLE
 TypeError: invalid key length

### ISSUE THREAD

**Issue by jmls** [jedisct1/libsodium.js#130]
I'm trying to follow the example of crypto_secretbox_easy(), but using it in a typescript method with this code:

```
public async encrypt(message) {
        await sodium.ready;

        const key = sodium.randombytes_buf(sodium.crypto_shorthash_KEYBYTES);
        console.log('#1', key);
        const nonce = sodium.randombytes_buf(
            sodium.crypto_secretbox_NONCEBYTES
        );

        const payload = nonce.concat(
            sodium.crypto_secretbox_easy(message, nonce, key)
        );

        return {
            key,
            payload
        };
}
```
I get  `#1 Uint8Array [ 244, 215, 122, 67, 60, 244, 138, 12, 89, 133, 219, 21, 233, 78, 127, 253 ]` on the console , but then a ` TypeError: invalid key length`

I also tried changing the key to a string `const key = 'foo';` but got the same error

what am I missing ?

**Comment by jedisct1** [comment]
Use `crypto_secretbox_keygen()` to create a key for `secrebox`, and `crypto_shorthash_keygen()` to create a key for `shorthash`.

Here, you built the keys yourself, using the key length for `shorthash` and then used that key for `secretbox`. These are completely different operations, that use different keys.

**Comment by jmls** [comment]
dear god, sorry ;) thanks.

**Comment by jmls** [comment]
Sorry, me again -  Just taken the example code "as is"

```
const sodium = require('libsodium-wrappers');
let key;
function encrypt_and_prepend_nonce(message) {
    let nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
    return nonce.concat(sodium.crypto_secretbox_easy(message, nonce, key));
}

(async () => {
    await sodium.ready;
    key = sodium.from_hex(
        '724b092810ec86d7e35c9d067702b31ef90bc43a7b598626749914d6a3e033ed'
    );

    try {
        let result = await encrypt_and_prepend_nonce('foo');
    } catch (e) {
        console.log('err', e);
    }
})();
```

running this gives the error

```
xc TypeError: nonce.concat is not a function
    at encrypt_and_prepend_nonce (<path>/x.js:6:18)
    at __dirname (<path>/x.js:34:28)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (module.js:655:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by jedisct1** [comment]
https://stackoverflow.com/questions/14071463/how-can-i-merge-typedarrays-in-javascript


There’s also a concat-typed-arrays npm module.

**Comment by ryancwalsh** [comment]
I appreciate that StackOverflow post and added my own fiddle demo of `concat-typed-array` here: 

https://stackoverflow.com/questions/14071463/how-can-i-merge-typedarrays-in-javascript#comment90580366_14071518

(https://codesandbox.io/s/4rok95vy24?autoresize=1&expanddevtools=1&hidenavigation=1)

That seems to work, which is cool.

However I'm still struggling to get the basic libsodium.js example to work. Here is my latest attempt: https://stackoverflow.com/q/51812991/470749

@jmls Do you have a working example?
