### ISSUE TITLE
crypto_pwhash available in non-sumo build

### ISSUE THREAD

**Issue by webmaster128** [jedisct1/libsodium.js#131]
In this repo's [README](https://github.com/jedisct1/libsodium.js) we have

> The crypto_pwhash_* function set is also only included in the Sumo version. The high amount of heap memory (allocated after loading) required by these functions may not be desirable when they are not being used.

However, I am successfully running tests on [crypto_pwhash()](https://gist.github.com/webmaster128/b2dbe6d54d36dd168c9fabf441b9b09c#crypto_pwhash) in a project that only includes and loads [libsodium-wrappers](https://www.npmjs.com/package/libsodium-wrappers) (no "-sumo"). So at least the symbols `crypto_pwhash` and `crypto_pwhash_ALG_ARGON2ID13` are included in the standard build.

Even if `crypto_pwhash_*` does not match `crypto_pwhash`, I don't think this is desired, right?

**Comment by jedisct1** [comment]
The `README` is not up to date. `crypto_pwhash()` is now present in regular builds as well.

**Comment by webmaster128** [comment]
👍 thanks
