### ISSUE TITLE
Log instead of crashing when WebAssembly can't be used

### ISSUE THREAD

**Issue by ffflorian** [jedisct1/libsodium.js#132]
Hi @jedisct1,
at [Wire](https://github.com/wireapp) we were really happy to see the latest version of `libsodium.js` includes WebAssembly! :tada: 

However, version 0.7.3 throws an error on a site with CSP headers using Chrome:
```
Uncaught (in promise) abort({}). Build with -s ASSERTIONS=1 for more info.
```

As we found out, this happens because WebAssembly [can't be used without `unsafe-eval`](https://github.com/WebAssembly/content-security-policy/issues/7) in Chrome for now, so this is already known.

As far as I understood, `libsodium.js` has pure JavaScript fallbacks for all functions if WebAssembly can't be used, right? So it would be great if a more meaningful message (and log instead of crashing) could be returned when this happens.

<details>
<summary>HTML example</summary>

```html
<html>
  <head>
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; connect-src 'self' data:; script-src 'self' 'unsafe-inline'">
  </head>
  <body>
    <script>
      window.sodium = {
        onload: function (sodium) {
          let key = sodium.crypto_sign_keypair();
          console.log(key);
        }
      };
    </script>
    <script src="sodium.js" async></script>
  </body>
</html>
```

</details>

**Comment by jedisct1** [comment]
Hi Florian,

Do you know how to do this?

**Comment by ffflorian** [comment]
@jedisct1,

I didn't know how to do this so I asked the people at emscripten: https://github.com/kripken/emscripten/issues/5911#issuecomment-366029402

So this is rather an emscripten issue than a libsodium.js issue and we'll have to wait for the fix (or fix it ourselves).

**Comment by jedisct1** [comment]
Good to know, thanks!
