### ISSUE TITLE
Argon2id 8x slower then commandline tool

### ISSUE THREAD

**Issue by webmaster128** [jedisct1/libsodium.js#133]
The command line tool [argon2 from phc-winner-argon2](https://github.com/P-H-C/phc-winner-argon2.git) performs the following hashing in ~0.8 seconds on a 64 bit Linux (Intel).

```
$ echo -n "abc" | ./argon2 XXXXXXXXXXXXXXXX -id -t 20 -k 65536 -l 32
Type:		Argon2id
Iterations:	20
Memory:		65536 KiB
Parallelism:	1
Hash:		47dcb93ccefb9523efa3df127f0f5d922ee9234ea31665656278daff2e421d3f
Encoded:	$argon2id$v=19$m=65536,t=20,p=1$WFhYWFhYWFhYWFhYWFhYWA$R9y5PM77lSPvo98Sfw9dki7pI06jFmVlYnja/y5CHT8
0.799 seconds
Verification ok
```

The same call (parameters verified by comparing hash result) takes 6.8 seconds in Chromium. Is this and expected performance? Is there a way to see if wasm implementation is used?

**Comment by jedisct1** [comment]
And you would find an even bigger difference when using the C version of libsodium which is even faster than this command-line tool :)

That's unfortunately quite expected. Argon2 is heavily optimized for SIMD instructions of Intel processors.

Webassembly currently doesn't support SIMD instructions, although this is in the works: https://www.chromestatus.com/feature/6533147810332672

**Comment by webmaster128** [comment]
Thanks for the quick reply. Makes sense.

In my test, the C version of libsodium performed as good as the argon2 command line tool (800 ms). In case someone wants to play around with it, this is my benchmark written in C++:

```c++
#include <sodium.h>

#include <chrono>
#include <string>
#include <vector>
#include <iostream>

int main() {
    if (sodium_init() == -1) {
        return 1;
    }

    // INPUT CONFIG
    const int opsLimit = 20;
    const int memLimit = 64*1024*1024;
    const int algorithmId = 2; // Argon2id
    const int out_len = 32;
    std::string password = "abc";
    std::vector<unsigned char> salt = {
        'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X', 'X',
    };


    unsigned char out[out_len];

    auto start = std::chrono::steady_clock::now();
    if (crypto_pwhash(out, sizeof out, password.c_str(), password.size(), salt.data(), opsLimit, memLimit, algorithmId) != 0) {
        /* out of memory */
        return -1;
    }
    auto end = std::chrono::steady_clock::now();
    auto diff = end - start;
    std::cout << std::chrono::duration <double, std::milli> (diff).count() << " ms" << std::endl;

    for(int i = 0; i < out_len; ++i) {
        std::cout << std::hex << (int) out[i];
    }
    std::cout << std::endl;

    return 0;
}
```

compiled with `c++ argon2test.cpp -I/tmp/libsodium-installation/include -L/tmp/libsodium-installation/lib -lsodium`.

However, I consider this done. Thanks!

**Comment by jedisct1** [comment]
Is that with libsodium 1.0.16? It should be consistently faster than the reference implementation, especially on Linux.

Anyway, this doesn't make the wasm issue. Which will get a boost once the SIMD extensions become implemented.

**Comment by webmaster128** [comment]
I was using current master of `https://github.com/jedisct1/libsodium.git` at 91b774d49d1bf268a7 compiled using `./autogen.sh && ./configure --prefix /tmp/libsodium-installation && make -j4 install` with gcc 7.2.0 on Ubuntu 17.10 and Intel® Core™ i5-5300U CPU @ 2.30GHz × 4.
