### ISSUE TITLE
Functions cannot be declared in a nested block in strict mode

### ISSUE THREAD

**Issue by haasted** [jedisct1/libsodium.js#137]
I've included libsodium-wrappers as a dependency using npm.

When I run the unit tests of my project, PhantomJS complains that 
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Functions cannot be declared in a nested block in strict mode
  at src/index.spec.js:61091
```

The error disappears when I remove the import of sodium-wrappers.

`const _sodium = require('libsodium-wrappers');`

Any ideas about work-arounds? My node.js experience is unfortunately a bit limited.

**Comment by dfaust** [comment]
The same problem exists with uglifyjs (see https://github.com/mishoo/UglifyJS2/issues/3027).
I used the `exclude` option of the `uglifyjs-webpack-plugin` to skip the chunks containing libsodium.
