### ISSUE TITLE
Can't minify a project that uses libsodium.js: Uncaught ReferenceError: window is not defined

### ISSUE THREAD

**Issue by jmbm1989** [jedisct1/libsodium.js#14]
I'm trying to minify my project (that is a library) that uses libsodium.js, and I get the following error when i load it:

![result](https://cloud.githubusercontent.com/assets/3846058/7846253/cdf44d36-0492-11e5-8686-f026546461a1.png)

Heare there is an example:

As we can see i'm using GruntJS and the grunt-contrib-requirejs module and almond to minify it.
 
![g1](https://cloud.githubusercontent.com/assets/3846058/7846260/ce10e144-0492-11e5-81c2-0244ea43e217.png)
![g2](https://cloud.githubusercontent.com/assets/3846058/7846259/ce10788a-0492-11e5-9f4f-519af89971ea.png)

Then i wrap it to have a module (based on https://github.com/jrburke/almond).

![end-frag](https://cloud.githubusercontent.com/assets/3846058/7846256/cdf58fde-0492-11e5-9456-40c85fb5a589.png)
![start-frag](https://cloud.githubusercontent.com/assets/3846058/7846254/cdf4b28a-0492-11e5-85e2-1f86ed19e121.png)

heare is my sample code that uses libsodium:

![src](https://cloud.githubusercontent.com/assets/3846058/7846257/cdf780fa-0492-11e5-8a47-05d4a6c6ab1e.png)
![tf2](https://cloud.githubusercontent.com/assets/3846058/7846255/cdf4ee12-0492-11e5-8082-0b0cda49666e.png)

The test that fails

![tf1](https://cloud.githubusercontent.com/assets/3846058/7846258/cdf9e052-0492-11e5-91d5-020e5ccf14fb.png)

And the result of the execution of: grunt mochaTest:functional

![result](https://cloud.githubusercontent.com/assets/3846058/7846253/cdf44d36-0492-11e5-8686-f026546461a1.png)

**Comment by jmbm1989** [comment]
Heare it goes my require.gonfig.js, i've puted fs: '../bower_components/fs/dist/fs.min' because it says that doesn't find it but i don't know why.  
![requirejs](https://cloud.githubusercontent.com/assets/3846058/7846550/99f1f7a2-0494-11e5-8bd3-1b4b98d6a092.png)

**Comment by jedisct1** [comment]
Hi,

Debugging screenshots is hard and the code you sent me doesn't work, but a few things:

* UglifyJS and asm.js don't play well with each other. UglifyJS reduces `a=a|0` to `a|=0` which is invalid asm.js code. libsodium.js asm.js code has already been minified, so you should avoid an extra pass with UglifyJS on it.
* `window` refers to the `window` object in the global scope (when the DOM is available). I'm not familiar with almond.js, but try adding something like `var window;` in `libsodium.js` to see if it works around the error you are seeing. But almond.js might have a better way to declare some symbols as globals. For example, flow.js requires `declare var window` to do so. You may have to do something similar.

**Comment by jmbm1989** [comment]
ok, my problem is that i would like to make a library that uses libsodium.js, works fine, but i would like to use it as a single file like myLib.js. I read that i need to minify it, at the time to do that i have this problems. The question is, Is there any framework or tool or particular configuration that you can recomend me to solve my problem?

**Comment by jedisct1** [comment]
You can still minify your code and then concatenate the files, instead of concatenating first and then minifying.
