### ISSUE TITLE
Browser bundle not on npm

### ISSUE THREAD

**Issue by ffflorian** [jedisct1/libsodium.js#140]
As more and more people are migrating [away from Bower](https://bower.io/blog/2017/how-to-migrate-away-from-bower/), the alternative would be yarn / npm and thus npm packages.

Unfortunately, the `browsers` and `browsers-sumo` bundles are not available on npm and therefore can't be installed with yarn. Would it be possible to make them available on npm, too?

Thanks in advance! :tada:

**Comment by jedisct1** [comment]
The browser thing is not a module, just a file that people can include directly in a web page. Not sure that it is even relevant to keep this at all.

Can't the normal module be used in a browser?

**Comment by ffflorian** [comment]
> Can't the normal module be used in a browser?

No, unfortunately not. When I include it, I get the following error:
```
libsodium-wrappers.js:formatted:2461 Uncaught TypeError: Cannot read property 'ready' of undefined
    at t (libsodium-wrappers.js:formatted:2461)
    at libsodium-wrappers.js:formatted:2620
    at libsodium-wrappers.js:formatted:2624
```

<details>
<summary>HTML example</summary>

```html
<html>
  <body>
    <script>
      window.sodium = {
        onload: function (sodium) {
          let h = sodium.crypto_generichash(64, sodium.from_string('test'));
          console.log(sodium.to_hex(h));
        }
      };
    </script>
    <script src="node_modules/libsodium-wrappers-sumo/dist/modules-sumo/libsodium-wrappers.js" async></script>
  </body>
</html>
```
</details>

**Comment by jedisct1** [comment]
With a module loader, of course.

```js
const _sodium = require('libsodium-wrappers');
(async() => {
  await _sodium.ready;
  const sodium = _sodium;
  // ...
})();
```

Seems to work as expected here. Had to add `import 'babel-polyfill'` for the async call since I'm using Parcel, but this may not even be required with Webpack.

**Comment by ffflorian** [comment]
Yes, sorry, of course I could use Webpack, but that would add another dependency to a project which would not be needed otherwise. I understand the argument that the browser bundle is not a classic npm module but I'd be happy anyway if you would publish it :slightly_smiling_face:.

**Comment by jedisct1** [comment]
But how to you even use something from npm without a bundler?

**Comment by NullVoxPopuli** [comment]
> No, unfortunately not. When I include it, I get the following error:
> libsodium-wrappers.js:formatted:2461 Uncaught TypeError: Cannot read property 'ready' of undefined

@ffflorian 
I'm getting this error, too


how do you resolve it? 
I am loading from:
```
node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js
```
