### ISSUE TITLE
Ship unminified javascript code

### ISSUE THREAD

**Issue by webmaster128** [jedisct1/libsodium.js#142]
I am trying to debug why Edge does not load libsodium.js inside of a WebWorker (.ready does not resolve). This is very complicated, since libsodium.js and libsodium-wrappers.js are always minified. I tried to compile the .js myself but failed because it is very complicated to setup an up-to-date emscripten environment, which seems to require compiling a compiler from source.

Would it be possible to check-in unminified versions as well?

I am thinking of a structure like

```
dist/browsers/sodium.js
dist/browsers/sodium.min.js
dist/browsers-sumo/sodium.js
dist/browsers-sumo/sodium.min.js
dist/modules/libsodium-wrappers.js
dist/modules/libsodium-wrappers.min.js
dist/modules/libsodium.js
dist/modules/libsodium.min.js
dist/modules-sumo/libsodium-wrappers.js
dist/modules-sumo/libsodium-wrappers.min.js
dist/modules-sumo/libsodium-sumo.js
dist/modules-sumo/libsodium-sumo.min.js
```

Of course, the output of emscripten will not be very readable. But especially the glue code in libsodium.js (e.g. the .ready promise) as well as the wrapper is very interesting for review and debugging.

**Comment by jedisct1** [comment]
If you are going to hack it, you should just rebuild it.

`make standard` builds the standard distribution, unpacked, `make sumo` builds the sumo version, also unpacked.

**Comment by jedisct1** [comment]
Emscripten is actually very simple to install; you don't need to compile anything.

On macOS, just use Homebrew.
On other environments, use [emsdk](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html)

**Comment by webmaster128** [comment]
Ah, thanks. The SDK works great. I did not know about that option.

**Comment by NullVoxPopuli** [comment]
unminified code is also handy for debugging when there is a usage problem or bug or something.

**Comment by NullVoxPopuli** [comment]
having unminified code would help prevent this impossible-to-debug-ness

![image](https://user-images.githubusercontent.com/199018/39677913-1e0ecdce-5151-11e8-822b-f30516ab9f64.png)

**Comment by jedisct1** [comment]
Typescript would.

**Comment by NullVoxPopuli** [comment]
what do you mean? are there types available? (I'm using typescript)

**Comment by ffflorian** [comment]
> what do you mean? are there types available? (I'm using typescript)

Yes, see [`@types/libsodium-wrappers`](https://www.npmjs.com/package/@types/libsodium-wrappers) and  [`@types/libsodium-wrappers-sumo`](https://www.npmjs.com/package/@types/libsodium-wrappers-sumo).
