### ISSUE TITLE
crypto_generichash_blake2b_salt_personal to derive keys

### ISSUE THREAD

**Issue by vikram919** [jedisct1/libsodium.js#144]
Hello @FSMaxB , @jedisct1
I am working to derive keys of 80 byte long from higher order entropy keys > 32byte, can I use `crypto_generichash_blake2b_salt_personal` ? If so, can you please explain how to pass  arguments, I have seen the discussion previously on this https://github.com/jedisct1/libsodium/issues/347
Thank you

**Comment by jedisct1** [comment]
You can call `crypto_kdf()` twice, with different subkey ids.

**Comment by jedisct1** [comment]
Alternatively, you can use `randombytes_buf_deterministic()`.

**Comment by vikram919** [comment]
Hi,
`randombytes_buf_deterministic()` returns  `TypeError: invalid seed length
    at Q (sodium.js:1)` it works fine in libsodium C framework but the javascript wrapper throws exception regarding the seed lenght provided. Hope you will fix it.
Thank you

**Comment by jedisct1** [comment]
The seed must be `SEEDBYTES` bytes long, no matter what the language is.

A 768 bit high-entropy seed doesn't make any sense. If this is a password, use `crypto_pwhash()` instead.

**Comment by codemaster101** [comment]
@jedisct1 Hey I am getting a similar error while using lib-sodium. 

This is my source code:


`const sodium = require('libsodium-wrappers');
const util = require('util');
const encoder = new util.TextEncoder('utf-8');
const HDKey = require('hdkey');

async function run() {
	await sodium.ready;
	const seed = `52379d04randomseed342ffe586b0importantdatamissingf8bc2f2c898thisisaseedthatIuse9616d9590e2noError9c2b`;
    const HDpath = 'm/44\'/1729\'/0\'/0\'';
    const hdkey = HDKey.fromMasterSeed(Buffer.from(seed, 'hex'));
	const derivedSeed = hdkey.derive(HDpath).privateExtendedKey;
	console.log(derivedSeed.length) // this is 111
	console.log(derivedSeed);
	console.log(await sodium.crypto_sign_SEEDBYTES);  // This is 32 
	const kp = sodium.crypto_sign_seed_keypair(derivedSeed);
	console.log(kp);
}


async function main() {
	await run();
}

main();`

My question is how do I use sodium.crypto_sign_seed_keypair to create the key pair without getting the error: 

> TypeError: invalid seed length

Is there a sodium library which reduces the seed to 32 bytes. I have to use the original seed to create an address for the Blockchain Tezos.

**Comment by jedisct1** [comment]
@codemaster101 This is off-topic, and Tezos uses the secp256k1 curve, while libsodium uses curve25519. This is not going to work.
