### ISSUE TITLE
Is it currently possible to change memory?

### ISSUE THREAD

**Issue by bufke** [jedisct1/libsodium.js#145]
Poking around I found talk of setting total memory. I found this even works:

```
window.sodium = {
    totalMemory: something,
};
```

However it causes a Abort({}) error as described in https://github.com/jedisct1/libsodium.js/issues/132

I am hoping to get a more authoritative answer if changing the memory is possible or not. I get the sense that it isn't a documented feature and not quite ready but wanted to check. It makes the pw_hash feature effectively unusable without sumo (but I don't need sumo now that pw_hash is in non-sumo). Is there any workaround? I'm guessing I could compile myself to set ram instead of doing it in JS?

**Comment by bufke** [comment]
Also I tried running make but I just get 

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 392, in _handle_results
    task = get()
TypeError: __init__() takes at least 3 arguments (1 given)
```

Ubuntu 17.10. I tried building libsodium (not js) but get the same error on make check.

**Comment by jedisct1** [comment]
Unfortunately not, still due to the issue you raised earlier: #128
