### ISSUE TITLE
How to know if sodium.js (wasm) was loaded?

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#149]
I am loading `sodium.js` in a Chrome browser via the [onload callback](https://github.com/jedisct1/libsodium.js/tree/0.7.3#usage-in-a-web-browser-via-a-callback). How do I know if the WebAssembly or the JavaScript version has been loaded? 

Is there a flag on the sodium wrapper which I can query from JavaScript to detect if it uses wasm?

So far I only check that there is a "wasm" entry listed up in "Sources" and that I get a "data:application/octet-stream;base64" XMLHttpRequests log message but is there a programmatic way to check it?

**Sources > wasm:**

![image](https://user-images.githubusercontent.com/469989/38431420-6a347fa4-39c4-11e8-857b-6947a0ddf0ef.png)

**Log XMLHttpRequests:**

![unbenannt-2](https://user-images.githubusercontent.com/469989/38431874-f55640bc-39c5-11e8-8453-5c6314e52682.PNG)

**Comment by jedisct1** [comment]
Check `sodium.libsodium.usingWasm`.

**Comment by bennyn** [comment]
Great! That's exactly what I was looking for! Thanks so much. 👍

**Comment by ffflorian** [comment]
@jedisct1 Seems like this flag was removed with commit https://github.com/jedisct1/libsodium.js/commit/943ff951c5d5851709475e454549c0dbbfbc278d? How come?
