### ISSUE TITLE
crypto box example?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jedisct1/libsodium.js#151]
The api documentation seems slightly incomplete, and it looks like all the tests are minified.

Just looking for an example of how to do public-key encryption with libsodium.js

thanks!

**Comment by bufke** [comment]
I made a thin wrapper around libsodium.js that might be helpful to you as an example https://gitlab.com/passit/simple-asymmetric-js/blob/master/simple_asym/crypto.ts

The readme on the project has some Bob and Alice examples too (but using my wrapper instead of libsodium.js directly).

**Comment by NullVoxPopuli** [comment]
It seems I still have a bit to learn about sodium.
like, how can encrypting not involve your private key? (only the target public key?)
Does this mean, that if _anyone_ has your public key, they can send you encrypted messages? but _somehow_ to decrypt the message, you need the receiver's private key?

regular RSA needs public and private key on encryption and decryption. so, the box not requiring a private key to encrypt is throwing me off. 

hmm

**Comment by NullVoxPopuli** [comment]
> My examples show both asymmetric (public/private key pair) and symmetric encryption. They are often used together because asymmetric is not good for larger amounts of data.

I knew that with RSA (which really was RSA + AES), but I thought that nacl box was supposed to solve that. 

Thanks for the links!

**Comment by NullVoxPopuli** [comment]
oh hey, there is crypto_box_easy
just found that out. The typings are incomplete.

**Comment by NullVoxPopuli** [comment]
TODO: post link to tests where I demonstrate the encrypt/decrypt cycle between two people: https://gitlab.com/NullVoxPopuli/emberclear/

**Comment by ryancwalsh** [comment]
@NullVoxPopuli Did you get this working? I wish I could see more examples of working libsodium.js. 

I'm trying to put a better example together here: https://stackoverflow.com/q/51812991/470749

Thanks.

**Comment by NullVoxPopuli** [comment]
@ryancwalsh yup! 
test: https://gitlab.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/src/utils/nacl/unit-test.ts#L19

implementation: https://gitlab.com/NullVoxPopuli/emberclear/blob/master/packages/frontend/src/utils/nacl/utils.ts#L48
