### ISSUE TITLE
use in chrome extension background script

### ISSUE THREAD

**Issue by nicopowa** [jedisct1/libsodium.js#155]
hi,
first, thanks for the hard work you're doing !
i am using libsodium.js in the browser and i tried to load it in my extension's background script to share some procedures between tabs.
unfortunately, it throws an error while loading which makes it unusable :

Uncaught (in promise) TypeError: B.printErr is not a function at sodium.js:1

any idea how i could make it work ?
thanks !

sample extension (does nothing, only loads sodium in background script) :
[sodiumext.zip](https://github.com/jedisct1/libsodium.js/files/2042603/sodiumext.zip)

**Comment by kushn1ruk** [comment]
Catching this error too in chrome extensions' background page.

**Comment by bufke** [comment]
The error seems to effect any usage as a web extension in Chrome.

- Works in Chrome (web)
- Works in Firefox web and web extension
- Doesn't work in Chrome background, popup, or even just a page like chrome-extension://gkgdoehlembmnlgbbjahgmaenidapjnd/index.html

Will poke around a bit. Seems like a recent regression. @nicopowa are you getting it from the released npm package or directly from this git repo (or source)? I got this error right after going from the npm version to building myself.

**Comment by bufke** [comment]
By forcing the printErr variable to be a console.log function I was able to get the real error message. 

"failed to asynchronously prepare wasm: CompileError: WebAssembly.compile(): Wasm code generation disallowed by embedder"

This isn't a libsodium.js regression then if this is the same issue you are getting. Looking at your manifest I suspect you have the same issue. Though it would be nice if the real error message came through.

Try adding `"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",`

If this is the case then it has nothing to do with libsodium.js and just is Chrome's policy.

My stupid hack to get the error message is to edit libsodium.js and find printErr and make it say 

`C.printErr=(err) => console.log('error!', err)!=typeof printErr`...

The change is the `(err) => console.log('error!', err)`

**Comment by nicopowa** [comment]
Hi, it's working now !
i'll read CSP docs about the unsafe-eval as it may cause security issues, but it's great to be able to handle crypto in the background.

the init has to be different though,
instead of :

window.sodium = { onload: function (sodium) {

i plugged my init code on the promise at the end of sodium.js as follows :

sodium.ready.then(sodiumInitialized).catch(sodiumNotInitialized);

working example attached
[sodiumext_2.zip](https://github.com/jedisct1/libsodium.js/files/2198020/sodiumext_2.zip)

thanks !
