### ISSUE TITLE
Is there a way to compile to a smaller size (gzipped)?

### ISSUE THREAD

**Issue by NullVoxPopuli** [jedisct1/libsodium.js#156]
So, I'm working on https://emberclear.io, and am trying to optimize bundle size,
currently, I'm at this:
![image](https://user-images.githubusercontent.com/199018/41999297-2a0b35ec-7a2b-11e8-9d7d-63533e181cb7.png)
libsodium takes about 148KB. 

I'm wondering if there is a way to bring that down, based off what I read here: https://github.com/nimiq/qr-scanner/

>  Javascript QR Code Scanner based on Lazar Lazslo's javascript port of Google's ZXing library.
In this library, several improvements have been applied over the original port:
    - Lightweight: ~33.7 kB (~12 kB gzipped) minified with Google's closure compiler.

previously, I was using https://github.com/schmich/instascan/, which has a very large bundle size, due to ZXing being quite large: https://bundlephobia.com/result?p=instascan@1.0.0 (439KB total). So.. the reduction there is insane!

Just wondering if anyone has had success with better gzip sizes?

**Comment by jedisct1** [comment]
You can recompile libsodium with only the functions you need. These are in the `EXPORTED_FUNCTIONS_STANDARD` definition of the `emscripten.sh` compilation script.

But 148 Kb is barely the size of an image.

**Comment by NullVoxPopuli** [comment]
> You can recompile libsodium with only the functions you need. These are in the EXPORTED_FUNCTIONS_STANDARD definition of the emscripten.sh compilation script.

excellent, I'll give that a go.

> But 148 Kb is barely the size of an image.

yeah, I'm doing a Progressive Web App (PWA), so every few KB counts. I want the appearance of a fast boot up time in my app. I'm already down from 850KB by switching away from instascan :)

**Comment by NullVoxPopuli** [comment]
actually, @jedisct1 where is `emscripten.sh`? having trouble finding it

**Comment by jedisct1** [comment]
Hi!

`emscripten.sh` is part of libsodium; it's in the `dist-build` directory.
