### ISSUE TITLE
Documentation on base64 conversion usage - sporadic success in conversion

### ISSUE THREAD

**Issue by NullVoxPopuli** [jedisct1/libsodium.js#158]
some context,
just trying test that I can convert to/from base64

my test (these are in typescript):
```ts
  module('toBase64 / fromBase64', function() {
    test('converts uint8array and back', function(assert) {
      const msgAsUint8 = Uint8Array.from([104, 101, 108, 108, 111]); // hello

      const base64 = stringEncoding.toBase64(msgAsUint8);
      const original = stringEncoding.fromBase64(base64);

      assert.deepEqual(original, msgAsUint8);
    });
  });
```

the to/from functions:
```ts
import libsodiumWrapper from 'libsodium-wrappers';

// for the utils, we don't care about wasm,
// so the conversions don't need to be async
const sodium = libsodiumWrapper.sodium;


export function toBase64(array: Uint8Array): string {
  return sodium.to_base64(array, sodium.base64_variants.ORIGINAL);
}

export function fromBase64(base64: string): Uint8Array {
  return sodium.from_base64(base64);
}
```

when the test runs, I get this error:

![image](https://user-images.githubusercontent.com/199018/42124689-995ecb64-7c35-11e8-9070-4ba39eab4f08.png)

I've tried all of the base64 conversion variants, and the only one that works is `sodium.base64_variants.URLSAFE_NO_PADDING` -- but that was only once, and my test won't pass again :-/

So, I'm wondering if there is an explanation on the different variants and what sort of things are / aren't allowed with them?

Note: this is on version 0.7.3 -- gonna try master, and see what happens.
same thing on master -- maybe my usage is wrong?

**Comment by jedisct1** [comment]
```js
const _sodium = require('libsodium-wrappers');
(async() => {
  await _sodium.ready;
  const sodium = _sodium;
  try {
    let t = new Uint8Array([0, 1, 2, 3, 4]);
    let t64 = sodium.to_base64(t, sodium.base64_variants.ORIGINAL);
    console.log(t64);
    let t2 = sodium.from_base64(t64, sodium.base64_variants.ORIGINAL);
    console.log(t2.every((v, i) => v === t[i]));
  } catch (e) {
    console.error(e);
  }
})();
```

Seems to work fine. If you don't resolve the future, I don't think `libsodium` will be loaded.

**Comment by NullVoxPopuli** [comment]
oh, does base64 rely on the libsodium stuff to be loaded? the to/from hex utilities don't. :-\
I'll give that a go

**Comment by NullVoxPopuli** [comment]
ok, so yeah, my problem was that the base64 utils rely on `libsodium` being loaded _and_ I need the same variant specified for both to and from. Cool! :)

thanks!
