### ISSUE TITLE
Does not work on RunKit

### ISSUE THREAD

**Issue by barkermn01** [jedisct1/libsodium.js#163]
It does not work on RunKit:
![image](https://user-images.githubusercontent.com/37368/43410928-7e428a02-9420-11e8-965f-da23dfeed3f9.png)

**Comment by jedisct1** [comment]
Use it as documented?

![screen shot 2018-07-30 at 20 27 29](https://user-images.githubusercontent.com/124872/43415889-12d16394-9437-11e8-9587-ec90a0465554.png)
