### ISSUE TITLE
aead_chacha20poly1305_ietf_decrypt with strange behaviour on react app

### ISSUE THREAD

**Issue by yvesago** [jedisct1/libsodium.js#164]
When I try to use  aead_chacha20poly1305_ietf in a React app
I can encrypt without trouble or warning
but to decrypt I have this warning :

Missing translation for key: "__WEBPACK_IMPORTED_MODULE_3_libsodium_wrappers_sumo___default.a.crypto_aead_chacha20poly1305_ietf_decrypt is not a function

A second load can decrypt.

Same think for libsodium_wrappers or libsodium_wrappers_sumo

Version 0.7.3

**Comment by jedisct1** [comment]
Are you properly waiting for the Promise to complete?

**Comment by yvesago** [comment]
You are right It's certainly something about Promise

But I try this kind of code and it's not better :
 
```
function Decrypt(json) {
  return new Promise((resolve, reject) => {
           console.log("==DeCrypt==");
           console.log(json);
           var nonce = new Uint8Array(12);
           nonce = text2ua(atob(json.nonce));
           const key = blake2b('secret',null,32);
           const dec = sodium.crypto_aead_chacha20poly1305_ietf_decrypt(
                  null,
                  text2ua(atob(json.xaddress)),
                  "1234",
                  nonce,
                  key,
                  "text"
                  );
           json.xaddress = dec;
           resolve(true);
       //     reject('Error');
  });
}
```

As it fails on page reload maybe it comes from an other source ...
