### ISSUE TITLE
crypto_pwhash throws a TypeError

### ISSUE THREAD

**Issue by bsterne** [jedisct1/libsodium.js#165]
Calling sodium.crypto_pwhash with normal values results in:
`TypeError: B.print is not a function`

Here is a JSFiddle illustrating the issue:
https://jsfiddle.net/72cqt0tk/74/

**Comment by jedisct1** [comment]
Try the `sumo` version.

**Comment by jedisct1** [comment]
The documentation says that `crypto_pwhash_*` is present in both versions, and I think this is supposed to be the case. But maybe the precompiled files don't have this yet, due to the issues with recent Emscripten versions being broken on Linux.
