### ISSUE TITLE
Feature request: crypto_onetimeauth

### ISSUE THREAD

**Issue by buu700** [jedisct1/libsodium.js#17]
(http://doc.libsodium.org/advanced/poly1305.html)

**Comment by jedisct1** [comment]
Just curious: what is your use case for `crypto_onetimeauth`?
Before considering it, make sure to check the requirements documented here http://doc.libsodium.org/advanced/poly1305.html

**Comment by buu700** [comment]
In the development branch of [Cyph](https://www.cyph.com), we have OTR swapped out with a new protocol built on Sodium and [NTRU](https://github.com/cyph/ntru.js), but the NTRU library isn't quite as nice and high-level as Sodium.

We're currently [polyfilling crypto_onetimeauth with TweetNaCl.js](https://gist.github.com/buu700/9b384d5905ce3221a15e) as a temporary workaround, which has been working well, so this construction definitely works for our use case. (Luckily, the NTRU parameter set we'd chosen can encrypt just enough data to hold one XSalsa20 key and one Poly1305 key.)

I understand if you'd prefer to keep the low-level features out of libsodium.js though; if that is the case, I'd be okay with either keeping our TweetNaCl version or building an internal fork of libsodium.js.

**Comment by buu700** [comment]
Just checking in again, is onetimeauth something that would make sense to enable in mainline libsodium.js?

(I was about to send a pull request, but it looks like it's already been implemented and just needs to be flagged on in the build script.)

**Comment by jedisct1** [comment]
Hi,

`crypto_onetimeauth()` can definitely be added. What is in `libsodium.js` is currently incomplete. Namely, `crypto_onetimeauth_{init(),update(),final()}` are missing, and I'd rather not tag a release with only half of the pieces.

If you want to implement the missing pieces, that would be awesome!

**Comment by buu700** [comment]
Ah, thanks! I'll go ahead and add the missing pieces and send a PR.

**Comment by buu700** [comment]
Okay, I made the changes in PR #25. Does that all look correct, and if so is there anything else needed on my end to enable onetimeauth (e.g. to any config files or build scripts)?
