### ISSUE TITLE
Unable to use sodium.crypto_pwhash_MEMLIMIT_INTERACTIVE in browser

### ISSUE THREAD

**Issue by fredemmott** [jedisct1/libsodium.js#175]
Code:

```
<html>
  <head>
    <script language="javascript">
      console.log("starting");
      window.sodium = {
        onload: function(sodium) {
          console.log('hello');
          let password = 'toor';
          let salt = sodium.randombytes_buf(sodium.crypto_pwhash_SALTBYTES);
          let key = sodium.crypto_pwhash(
            sodium.crypto_secretbox_KEYBYTES,
            password,
            salt,
            sodium.crypto_pwhash_OPSLIMIT_INTERACTIVE,
            sodium.crypto_pwhash_MEMLIMIT_INTERACTIVE, // 1024 * 1024 * 10 is fine, 11MB breaks
            sodium.crypto_pwhash_ALG_DEFAULT
          );
          console.log(key);
        }
      };
    </script>
    <script language="javascript" src="sodium.js" async></script>
  </head>
  <body>
    Hello, world
  </body>
</html>
```

Failure:

```
[Error] Unhandled Promise Rejection: TypeError: E is not a function. (In 'E(A)', 'E' is undefined)
	iA (sodium.js:1:474327)
	Y (sodium.js:1:308668)
	enlargeMemory (sodium.js:1:471688)
	wasm-stub
	<?>.wasm-function[44]
	<?>.wasm-function[37]
	<?>.wasm-function[247]
	<?>.wasm-function[246]
	<?>.wasm-function[329]
	<?>.wasm-function[330]
	<?>.wasm-function[322]
	<?>.wasm-function[59]
	<?>.wasm-function[318]
	<?>.wasm-function[308]
	<?>.wasm-function[213]
	wasm-stub
	_crypto_pwhash
	FA (sodium.js:1:534619)
	onload (index.htm:10)
	(anonymous function) (sodium.js:1:557384)
	promiseReactionJob
```

Tested with latest Chrome and Safari on MacOS 10.14

**Comment by jedisct1** [comment]
Is that with the `sumo`  version?

**Comment by fredemmott** [comment]
That's with https://github.com/jedisct1/libsodium.js/blob/9d4455cfd8c68a53238475b9f900f42582d7c925/dist/browsers/sodium.js (current master, but permalink)

fredemmott-pro:sodiumtest fredemmott$ openssl sha256 sodium.js
SHA256(sodium.js)= e5ab837bad21af11bc7d874e3fd08f4e3732d7fe93c264a96fa9791b8bac2751

**Comment by fredemmott** [comment]
ah, sorry, I missed this note in the README:

> The crypto_pwhash_* function set is also only included in the Sumo version. The high amount of heap memory (allocated after loading) required by these functions may not be desirable when they are not being used.

This doesn't seem strictly accurate though - it's present in non-sumo, it just has a lower limit

**Comment by fredemmott** [comment]
Yeah, it works fine with sumo - thanks.

Leaving this open, as the documentation should be clarified, and I'm guessing that the main crypto_pwhash function should be removed from non-sumo?

**Comment by jedisct1** [comment]
pwhash was added to the regular version to implement server relief, where the computation work is shared between the client and the server in order to mitigate resource exhaustion attacks. The non-sumo version is enough for this.

Keeping memory usage low may be preferable in a browser environment. So, even if the entire computation is done client-side, you may want to reduce memory usage, and increase the number of iterations. The non-sumo version is perfectly fine in that context as well.

**Comment by jedisct1** [comment]
Adding new constants indeed seems like a good idea, even though it will be very dependent on the set of devices you are targeting (which can include servers, when run using node).
