### ISSUE TITLE
unhandledExceptions exit without logging

### ISSUE THREAD

**Issue by adri326** [jedisct1/libsodium.js#177]
After experiencing an issue with the library, similar to other ones (two of them to be exact) that I had seen in the couple last days, @Clemens-E has found that there was a tiny bit of code in `dist/module/libsodium.js`, which yields:
```js
process.on("unhandledRejection",function(A,I){process.exit(1);});
```

It could be the reason to why programs would close "mysteriously" without logging any reason. The `process.on("uncaughException")` could also be it.

**Comment by Clemens-E** [comment]
I recently found the issue because my process always quited on any error without showing it. Then after a lot of time I found this code and discussed it in a channel. You too. This guy thought it may be a good idea to open a issue (what I wanted to do today). Absolutely thanks for not mentioning my name in any way.
my tag in discord (CHY4E#0505)

**Comment by eslachance** [comment]
Also https://github.com/jedisct1/libsodium.js/blob/8fa117918df38f52668feaf9cbc498c633671855/wrapper/libsodium-post.js#L1

Basically, what you're doing here is that any project that uses libsodium will exit on any unhandled promise rejection. Meaning, troubleshooting errors on any project using libsodium becomes impossible. Please take this into consideration.

**Comment by jedisct1** [comment]
The original handlers are added by Emscripten.

And the purpose of what @eslachance quoted is specifically to remove these, so that an error is printed.

See #672 for some context.

**Comment by Clemens-E** [comment]
But the error isnt printing, the process just exits.
After removing the packet it does print it out, is the version too old?

**Comment by adri326** [comment]
So.. you're disabling error logging to remove the handler which disables it..?

**Comment by jedisct1** [comment]
The original handlers are added by the compiler.

**Comment by adri326** [comment]
Shouldn't it be reported to emscriptem then?

**Comment by jedisct1** [comment]
That would be great! Go ahead :)

**Comment by adri326** [comment]
Will do
