### ISSUE TITLE
Using with typescript/angular

### ISSUE THREAD

**Issue by grosch** [jedisct1/libsodium.js#179]
I did an `npm install libsodium-wrappers` but when I try and build I get this:

> WARNING in ./node_modules/libsodium/dist/modules/libsodium.js
Module not found: Error: Can't resolve 'crypto' in '/private/tmp/vtb/node_modules/libsodium/dist/modules'

> ERROR in ./node_modules/libsodium/dist/modules/libsodium.js
Module not found: Error: Can't resolve 'path' in '/private/tmp/vtb/node_modules/libsodium/dist/modules'

Are there other npm modules that are required?

**Comment by bufke** [comment]
I get the warning too and just ignore it. I don't get the error. How are you building? Angular-cli? Custom webpack? I use libsodium.js with angular-cli. Feel free to look at my [configuration](https://gitlab.com/passit/passit-frontend/).

**Comment by grosch** [comment]
OK, I have a bare project that's failing now.  I can reproduce it like so.  

1. ng new failing  (no routing, plain css)
2. npm install libsodium-wrappers
3. Edit src/app/app.component.ts to do an `import * as Sodium from 'libsodium-wrappers'` and then in the constructor just say `const key = Sodium.from_hex('');`
4. npm run build

`ng --version` says this:

> Angular CLI: 7.0.7
Node: 11.5.0
OS: darwin x64
Angular: 7.0.4

**Comment by grosch** [comment]
Thank you, that fixed it!
