### ISSUE TITLE
Release to npm? 

### ISSUE THREAD

**Issue by madsheep** [jedisct1/libsodium.js#180]
Hi!, 
Any chance you could release to npm? 
Using latest release from there (0.7.3) is still broken by issue #152

**Comment by madsheep** [comment]
I think there is also an issue with the regen? - the faulty code that triggered #152 is still present in the files in dist directory there: 

![https://api.monosnap.com/rpc/file/download?id=kjJJMFAKpDoSUIdm8xCfgFgfb3nn8i](https://api.monosnap.com/rpc/file/download?id=kjJJMFAKpDoSUIdm8xCfgFgfb3nn8i)

**Comment by muelli** [comment]
Yeah, I think I'd like to have a release which incorporates a fix for https://github.com/jedisct1/libsodium.js/issues/173

**Comment by madsheep** [comment]
@NullVoxPopuli I think that's because @jedisct1 is preparing a release (looking at commits it seems to be the case) - hang tight :)

**Comment by jedisct1** [comment]
Yes, libsodium 1.0.17 was just released this morning. libsodium.js was updated with the new code, but a bit of testing would be good before sending it to npm.

Also, there are no Javascript wrappers for the new functions introduced in 1.0.17. But that can be done later.

Meanwhile, you don't need npm. Test using the code available in the `dist` folder and report any regression you may come across!
