### ISSUE TITLE
API Example(secretbox) does not work - with suggestions

### ISSUE THREAD

**Issue by jcdc404** [jedisct1/libsodium.js#181]
In checking out this library for a project I'm working on I noticed that the secretbox example in the API section of the README.md does not work. After reading another issue, this is related to at least one other example. The problem is that nonce is a typedarray and not a regular array, so it does not have a concat method. 

A potential solution is to update the README.md:
    to add:
        `let nonce_arr = sodium.to_hex(nonce);`
    then change:
       ` return nonce.concat(sodium.crypto_secretbox_easy(message, nonce, key));`
    to:
        `return sodium.from_hex(nonce_arr.concat(sodium.to_hex(sodium.crypto_secretbox_easy(message, nonce, key))));`

There may be a more elegant solution, but this works in the browser.

**Comment by paragonie-scott** [comment]
A more elegant solution is `Buffer.from(typedArrayGoesHere)` :)

**Comment by rm-rf-etc** [comment]
> A more elegant solution is `Buffer.from(typedArrayGoesHere)` :)

There's no `Buffer` in the browser, this is a NodeJS API. There exists a module to recreate the `Buffer` API in the browser.

The readme and examples should be a lot clearer. TweetNaCl has been far more approachable for me.

The examples should not use `let` everywhere. Most of these should be `const`. Take, for example, this:
```javascript
    let nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
    return nonce.concat(sodium.crypto_secretbox_easy(message, nonce, key));
```

`let` is completely unnecessary here.

Test for yourself in NodeJS:
```javascript
> const a = [1,2]
undefined
> a.concat([3,4,5])
[ 1, 2, 3, 4, 5 ]
> a
[ 1, 2 ]
>
```
