### ISSUE TITLE
TypeError: privateKey cannot be null or undefined

### ISSUE THREAD

**Issue by Genie23** [jedisct1/libsodium.js#182]
Hello,

I am a French developer, and I just discovered this library.

My goal is to encrypt exchanges between PHP and Javascript. To be done I planned to use paragonie / sodium_compat side PHP and jedisct1 / libsodium.js Javascript side. PHP side, I have no problem for now. On the javascript side, however, I think I do not use the sodium.js script properly.

Before connecting Javascript to PHP, I wanted to try to encrypt and then decrypt a basic message ("TEST") as follows:

`

    <script src="sodium.js" async></script>
    <script>
        sodium = {
            onload: sodium => {
                var keys = sodium.crypto_box_keypair();

                var ciphered = sodium.crypto_box_seal(sodium.from_string("TEST"), keys.publicKey);
                console.log(ciphered);

                var unciphered = sodium.crypto_box_seal_open(ciphered, keys.privateKey);
                console.log(unciphered);
            }
        };
    </script>
`

The encryption goes well, but at the time of decryption, I have the following error:

`TypeError: privateKey cannot be null or undefined`

Thank you in advance for all the help you will give me.

**Comment by gpalomar** [comment]
Hi @Genie23 !

You have missed the public key part! For decryption you should use both keys as following:

`var unciphered = sodium.crypto_box_seal_open(ciphered, keys.publicKey, keys.privateKey);
            console.log(unciphered);`

Don't forget to decode the decrypted binary string using:
`var original = sodium.to_string(unciphered)`

Hope this helps 😄
