### ISSUE TITLE
sodium.crypto_sign_seed_keypair is not a function

### ISSUE THREAD

**Issue by Sm00g15** [jedisct1/libsodium.js#184]
Hey there

I just recently upgrade libsodium-wrappers-sumo to 0.7.3 and I'm now running into this error when attempting to generate a key pair:

`     TypeError: sodium.crypto_sign_seed_keypair is not a function`
 
Have you any idea what could be causing this? Should I be waiting for libsodium.ready to be true so the entropy is sufficient before trying to run any functions?

**Comment by extreg** [comment]
How did you fix this issue? I am importing my sodium.js file into html file and giving me same error.
