### ISSUE TITLE
Wrong nonce size?

### ISSUE THREAD

**Issue by grosch** [jedisct1/libsodium.js#185]
This line in my typescript file:

```typescript
console.info(Sodium.crypto_aead_chacha20poly1305_ietf_NPUBBYTES + "\n");
```

Reports that the bytes count should be 12.  However, if I then do this in PHP version 7.2.11

```php
echo SODIUM_CRYPTO_AEAD_CHACHA20POLY1305_NPUBBYTES . "\n";
```

it says that the byte size should be 8.  Why the mismatch?

**Comment by grosch** [comment]
I see that libsodium itself defines this as 12, so not an issue with your library.

**Comment by jedisct1** [comment]
`chacha20poly1305_ietf` has a 8 bytes nonce size, `chacha20poly1305` has a 12 bytes nonce size, `xchacha20poly1305_ietf` has a 24 bytes nonce size.
