### ISSUE TITLE
New emscripten version and ALLOW_MEMORY_GROWTH

### ISSUE THREAD

**Issue by bufke** [jedisct1/libsodium.js#186]
Hello, on a whim I decided to see if the most recent emscripten improved anything. [Last time](https://github.com/jedisct1/libsodium.js/issues/128) I checked it was impossible to build this project with the current release at the time. 

It seems 1.38.21 builds the project successfully. I then tired out ALLOW_MEMORY_GROWTH which was previously stated as having serious performance hits. How did you benchmark it? I would love to try rerunning such benchmarks. To my eye, it didn't have any negative performance effects when running argon2 but of course a "how does it feel" test isn't a good one. The effects are quite positive for my use case (login needs pwhash but nothing else needs much ram). Enabling this by default would also greatly help the "just works" factor and would fix #175 .

What do you think of updating the readme with more detailed instructions on how to compile? I'd be happy to submit a PR. If you don't have time, I could also try figuring out a performance benchmark to compare with and without memory growth.

**Comment by bufke** [comment]
I ran a test like this:

```
sodium.crypto_pwhash(
        sodium.crypto_box_SEEDBYTES,
        password,
        salt,
        hashVersion.OPSLIMIT,
        hashVersion.MEMLIMIT,
        hashVersion.ALG,
);
```

I ran it 4 times for with and without memory growth. I used the same password and salt and ran this in Chrome on Linux.

without ALLOW_MEMORY_GROWTH
time (avg) 790ms
ram after test 125 mb

with ALLOW_MEMORY_GROWTH
time (avg) 820ms
ram after test 141mb

It's consistently slightly faster without memory growth. Memory growth also eat a little more ram than me specifying exactly what I know the max ram will be.

My take away from this test is that allow memory growth has very minimal performance effects but makes libsodium.js easier to use and uses less memory overall (depending on use case of course).

**Comment by jedisct1** [comment]
This is good news, and indeed, having something that works out of the box would be great.

In order to run the benchmarks, you can run the `emscripten.sh` script with `--tests`. The `.log` files for each test will contain the time it took to complete the test.

**Comment by bufke** [comment]
Doesn't seem to really be any difference in the tests

```
without     2347000000000
with growth 2330800000000
pwhash_argon2id.js
```

Fairly unscientific test - I just ran it once with and once without. I wonder if the difference will only show in a browser.

**Comment by bufke** [comment]
Is this still relevant with https://github.com/jedisct1/libsodium.js/commit/41e6c7ffa5694a195453cc2e8364f2847a2c1e24 ? I see you removed the warning about heap memory.

**Comment by jedisct1** [comment]
It should not be relevant any more :)
