### ISSUE TITLE
Can’t evoke libsodium-wrappers-sumo functions in `0.7.4`

### ISSUE THREAD

**Issue by dangodev** [jedisct1/libsodium.js#187]
This may be an education/README question, but I’m experiencing an issue with the `0.7.4` wrapper from npm. I’m trying to use the `crypto_pwhash_scryptsalsa208sha256_ll` function, and it’s undefined:

```js
import { crypto_pwhash_scryptsalsa208sha256_ll } from 'libsodium-wrappers-sumo';

console.log(crypto_pwhash_scryptsalsa208sha256_ll) // undefined;
```

Digging a little further, there seems to be a `libsodium` key on the initial object that’s loaded, that has a reference to that function:

```js
import * as libsodiumWrappersSumo from 'libsodium-wrappers-sumo';

const { libsodium } = libsodiumWrappersSumo;
console.log(Object.keys(libsodium));
// [… '_crypto_pwhash_scryptsalsa208sha256_ll',  … ]

libsodium._crypto_pwhash_scryptsalsa208sha256_ll(...args)
// TypeError: Cannot read property 'apply' of undefined at Object.C._crypto_pwhash_scryptsalsa208sha256_ll
```

In the second example, the `libsodiumWrappersSumo` object eventually registers the `crypto_pwhash_scryptsalsa208sha256_ll` later, but by that time my function has already executed and I don’t have a promise I can wait for.

Is this a problem with the generated npm library, or is there a way I can wait for `crypto_pwhash_scryptsalsa208sha256_ll` to be loaded?

**Comment by dangodev** [comment]
I’m also noticing the same behavior with `crypto_sign_detached` and `crypto_sign_seed_keypair`, FWIW

**Comment by dangodev** [comment]
Ah! It was right there in the README 🙂 . This fixed my problem:

```js
import * as sodium from 'libsodium-wrappers-sumo';

async myFunction() {
  console.log(typeof sodium.crypto_pwhash_scryptsalsa208sha256_ll) // undefined
  await sodium.ready;
  console.log(typeof sodium.crypto_pwhash_scryptsalsa208sha256_ll) // function 🎉
```

I did notice one line in the README that did trip me up though:

> The crypto_pwhash_* function set is included in both versions.

This doesn’t seem to be accurate; although I can see a reference to `crypto_pwhash_scryptsalsa208sha256_ll` in `libsodium-wrappers`, this code only works if I import `libsodium-wrappers-sumo` for some reason. But after figuring that part out, the README does list `ready` as the thing to wait for.

**Comment by codemaster101** [comment]
Hey @jedisct1 I have a piece of code in a package which I built for in a repository.

The package's code is something like:
```
      await _sodium.ready;
      const sodium = _sodium;
      const hdKey = HDKey.fromMasterSeed(bufMasterSeed);
      const { privateKey }: { privateKey: Uint8Array } = hdKey.derive(derivationPath);
 ```
 
 When I call this package to test, it works perfectly.
 
But when I call it in a package, it fails with:
```
/home/shivam/Desktop/<redacted>/node_modules/libsodium-sumo/dist/modules-sumo/libsodium-sumo.js:1
(function (exports, require, module, __filename, __dirname) { !function(A){function I(A){"use strict";var I;void 0===(I=A)&&(I={});var g=I;"object"!=typeof g.sodium&&("object"==typeof global?g=global:"object"==typeof window&&(g=window)),"object"==typeof g.sodium&&"number"==typeof g.sodium.totalMemory&&(I.TOTAL_MEMORY=g.sodium.totalMemory);var a=I;return I.ready=new Promise((function(A,I){(r=a).onAbort=I,r.print=function(A){},r.printErr=function(A){},r.onRuntimeInitialized=function(){try{r._crypto_secretbox_keybytes(),A()}catch(A){I(A)}},r.useBackupModule=function(){var A,I=void 0!==(I={})?I:{},g={};for(A in I)I.hasOwnProperty(A)&&(g[A]=I[A]);var r=[],t=!1,B=!1,n=!1,o=!1;t="object"==typeof window,B="function"==typeof importScripts,n="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node,o=!t&&!n&&!B;var e,i,C,Q,c="";function _(A){return I.l

TypeError: E is not a function
    at process.BA (/home/<redacted>/node_modules/libsodium-sumo/dist/modules-sumo/libsodium-sumo.js:1:380887)
    at process.emit (events.js:182:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:119:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

Any idea on how to solve it?
