### ISSUE TITLE
Call to crypto_sign_seed_keypair() fails

### ISSUE THREAD

**Issue by anonymoussprocket** [jedisct1/libsodium.js#189]
With the following code. `seed` is a string.
```javascript
import * as sodiumsumo from 'libsodium-wrappers-sumo';

const key_pair = sodiumsumo.crypto_sign_seed_keypair(Buffer.from(seed), 'uint8array');
```
I get this error: `sodiumsumo.crypto_sign_seed_keypair is not a function`. This has started happening since v0.7.0 after the minified version of libsodium-wrappers.js was introduced. I do see that function listed in the file however.

This is a breaking change between 0.5.4 and 0.7.0. It is still broken in 0.7.4.

**Comment by jedisct1** [comment]
Are you waiting for the Promise to be resolved?

**Comment by anonymoussprocket** [comment]
there is just an error immediately.

`sodiumsumo.crypto_sign_seed_keypair is not a function`

**Comment by jedisct1** [comment]
See the [documentation](https://github.com/jedisct1/libsodium.js#usage-as-a-module).

You need to wait for the `.ready` promise before you can use this library.

**Comment by anonymoussprocket** [comment]
I have an update. Calling `await sodiumsumo.ready` did not solve the problem. However I did test it in a separate file with JavaScript and it worked. The problem appears to be the typescript transpiler (3.3.3). The following simply doesn't work in typescript:

```typescript
await sodiumsumo.ready;
const key_pair = sodiumsumo.crypto_sign_seed_keypair(Buffer.from(seed), 'uint8array');
```

That gave me the idea to wrap the sodiumsumo calls in plain JavaScript, so I ended up with this:

```javascript
const sodiumsumo = require('libsodium-wrappers-sumo');

var keys = async (seed) => {
    await sodiumsumo.ready;
    return sodiumsumo.crypto_sign_seed_keypair(seed, '');
}

module.exports = { keys };
``` 

Back in typescript I imported it as `const wrapper = require('./WrapperWrapper');` and called `const k = await wrapper.keys();`. This is awful, but it works.

**Comment by jedisct1** [comment]
If you are transpiling to an old Javascript version, TypeScript will not emit `async/await`, but an emulation using generators.

You should target es2017 (`tsc -t es2017` or `"target": "es2017"` in the `tsconfig.json` file).

**Comment by anonymoussprocket** [comment]
Thank you for the follow up. I’ll try that, but I have async/await all over that code base already.

**Comment by jedisct1** [comment]
Great. By using the native mechanism instead of emulation, your code will be smaller and faster.
