### ISSUE TITLE
Missing the finite field functions ?

### ISSUE THREAD

**Issue by stripedpajamas** [jedisct1/libsodium.js#193]
I tried the normal version and the sumo version but didn't see any of the [finite field](https://download.libsodium.org/doc/advanced/point-arithmetic) functions available (except   `crypto_scalarmult` and `crypto_scalarmult_base`). Are there any plans to support those functions in this wrapper? Specifically the `crypto_core_ed25519_*` functions.

**Comment by jedisct1** [comment]
Hi!

I'm not planning to write wrappers for these, as the ones for [wasm-crypto](https://github.com/jedisct1/wasm-crypto) seem more generally useful.

But if you want to write them, go ahead :)

**Comment by stripedpajamas** [comment]
Awesome, I will try to use the wasm-crypto module. To achieve the functionality of `crypto_core_ed25519_scalar_random`, would you recommend filling a 64-byte Uint8Array with `window.crypto.getRandomValues` and then reducing it with `faScalarReduce`?

**Comment by jedisct1** [comment]
Yes, that's a totally correct way to get a random scalar in `[0..L[`;

**Comment by stripedpajamas** [comment]
Thanks! 🙏
