### ISSUE TITLE
crypto_aead_chacha20poly1305_decrypt returning invalid usage

### ISSUE THREAD

**Issue by pierreraii** [jedisct1/libsodium.js#195]
Usage: 
`const decryptedBody = this.sodiumjs.crypto_aead_chacha20poly1305_decrypt(null, encryptedBodyArray, adArray, nonceArray, key);`

encryptedBodyArray, adArray, nonceArray are all Uint8Array of bytes

Returns the following error: invalid usage

<img width="511" alt="Screen Shot 2019-04-13 at 1 15 13 PM" src="https://user-images.githubusercontent.com/7963892/56078217-35ef8500-5dee-11e9-9769-fef461c5f938.png">

**Comment by jedisct1** [comment]
It means that the ciphertext cannot be decrypted using that key. Or, more likely, that the authentication tag cannot be verified with the nonce, ad, ciphertext and key you provided.

**Comment by Almo7aya** [comment]
Interesting!
