### ISSUE TITLE
Mozilla requires unobfuscated code in WebExtensions starting June 10

### ISSUE THREAD

**Issue by Jaaap** [jedisct1/libsodium.js#197]
https://blog.mozilla.org/addons/2019/05/02/add-on-policy-and-process-updates/

> We will no longer accept extensions that contain obfuscated code. We will continue to allow minified, concatenated, or otherwise machine-generated code as long as the source code is included

I'm using your excellent lib in my WebExtension.
Is it possible to compile this is a non-obfuscated way?

**Comment by jedisct1** [comment]
The distributed files are not obfuscated. They are just minified, so that should be fine according to their requirements.

You can also run `make target` (or `make standard` / `make sumo`) to run everything up to the point where `uglifyjs` is called.

**Comment by Jaaap** [comment]
Oh that's nice.
I'm gonna try to compile it.
