### ISSUE TITLE
Uncaught (in promise) TypeError: i is not a function

### ISSUE THREAD

**Issue by earendil02** [jedisct1/libsodium.js#201]
Tried to include the browser-sumo file in a webpage using the example code:
```
<script>
    window.sodium = {
        onload: function (sodium) {
            let h = sodium.crypto_generichash(64, sodium.from_string('test'));
            console.log(sodium.to_hex(h));
        }
    };
</script>
<script src="sodium.js" async></script>
```
Loading the page I get in console the error:

> Uncaught (in promise) TypeError: i is not a function
    at oA (sodium.js:1)
    at Object.A.Pointer_stringify (sodium.js:1)
    at e (sodium.js:1)
    at sodium.js:1

**Comment by earendil02** [comment]
Trying with the normal browser file I get the following error instead:

> Uncaught (in promise) TypeError: n is not a function
    at tA (sodium.js:1)
    at Object.A.Pointer_stringify (sodium.js:1)
    at e (sodium.js:1)
    at sodium.js:1

**Comment by thomseddon** [comment]
I got the same error when running from master, everything seems to work OK with the latest tagged release however: https://github.com/jedisct1/libsodium.js/releases/tag/0.7.4
