### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by ffflorian** [jedisct1/libsodium.js#206]
Hi @jedisct1,
this is probably a duplicate of #37 but I wanted to raise the question again if it would be possible to create a changelog for a new release? The commit history also doesn't really help me when there are commits like ["git push"](https://github.com/jedisct1/libsodium.js/commit/ffe64526e01c658fe38e824e7d9c621fa9524736) which seem to include a merge - but I am not sure.

Due to the importance of this library and its possible security impacts I am hesitating to upgrade it to the latest version because I don't know the changes.

I am also in charge of keeping the [types on DefinitelyTyped](https://www.npmjs.com/package/@types/libsodium-wrappers) up-to-date and I am not really sure what to change.

As a first step it would really help if you could stick to [Semantic Commit Messages](https://seesparkbox.com/foundry/semantic_commit_messages) so I know what is an important fix, a breaking feature or a non-important build chore.

Thank you!

**Comment by jedisct1** [comment]
Hi Florian,

The changes are essentially libsodium updates.

The wrappers themselves don't get much changes. The code of these wrappers is so unreadable that the main change I'm expecting to do as soon as possible is rewrite everything.
