### ISSUE TITLE
Is it possible to build without WASM support?

### ISSUE THREAD

**Issue by yvbbrjdr** [jedisct1/libsodium.js#213]
Hi @jedisct1!

I'm trying to write a browser extension in TypeScript with webpack. Webpack will pack `vm-browserify` (which includes an `eval` call) into all files that import (directly or indirectly) `libsodium-wrappers`, but we don't want to have any `eval` calls in our extension. We figured that it *might be* because of the WebAssembly code in the `libsodium` package. So is it possible to build `libsodium` without WASM?

Thanks.

**Comment by jedisct1** [comment]
Not without major changes.

But if webpack adds unnecessary dependencies, or does calls that you want to avoid, this is probably something you should rather report to webpack maintainers.

**Comment by yvbbrjdr** [comment]
Thank you for your reply! Do you have any instructions or hints on how I could build it without WASM?

Although I don't know exactly how it works, I think the eval call might be a necessary dependency to pack node modules with WASM to something that's runnable in the browser.

**Comment by yvbbrjdr** [comment]
Thank you for your explanation! It seems to be webpack's issue to pack unnecessary methods into the js files.
