### ISSUE TITLE
Release current master

### ISSUE THREAD

**Issue by webmaster128** [jedisct1/libsodium.js#214]
On master there are a bunch of fixes, like e.g. https://github.com/jedisct1/libsodium.js/issues/205. Could we release them to npm? Thanks!

**Comment by paragonie-scott** [comment]
It looks like the release process is slightly more involved than updating package.json then `git tag -s tagnamehere && npm publish`, but I too would like to see a new release soon.

@jedisct1 Let me know if you want me to help with anything before the next release is ready! :)

**Comment by jedisct1** [comment]
Make sure that there are no regressions :)

**Comment by paragonie-scott** [comment]
#221 adds tests to master, #222 adds them to a branch off v0.7.5 (with my sodium_add fix and Travis integration).

**Comment by webmaster128** [comment]
0.7.6 is released, thanks
