### ISSUE TITLE
crypto_onetimeauth API not exposed in libsodium-wrappers

### ISSUE THREAD

**Issue by paragonie-scott** [jedisct1/libsodium.js#216]
I'm working on a high-level abstraction and noticed that `libsodium-wrappers` isn't included in the non-sumo build, despite being part of the [NaCl API](https://nacl.cr.yp.to/onetimeauth.html).

Although this isn't generally something most people will need or want to use (since naked Poly1305 is a bit dangerous to hand to most developers), its absence will draw criticism from NaCl purists.

EDIT: It's also not in the sumo build.

**Comment by jedisct1** [comment]
According to `emscripten-symbols.def`, the related symbols are exported in `libsodium.js`, but [wrappers](https://github.com/jedisct1/libsodium.js/tree/master/wrapper/symbols) for these have never been written. 

Probably because in 5 years, nobody ever needed this :)

**Comment by paragonie-scott** [comment]
I'm more than happy to eschew these in my wrapper library. (If I really need this in the future, I do have an [implementation](https://github.com/paragonie/poly1305-js) that I can point people towards.)

**Comment by paragonie-scott** [comment]
I ended up using my polyfill in sodium-plus. https://github.com/paragonie/sodium-plus/commit/7d2b9af3117cbb5294c58726c05e0884d138cce7
