### ISSUE TITLE
important question

### ISSUE THREAD

**Issue by 1018715564** [jedisct1/libsodium.js#220]
Hello Author, I'm encapsulating your library

In advanced encryption, crypto_aead_chacha20poly1305_encrypt is used, but it needs six parameters. I don't know what these six parameters mean. Please let me know. Thank you. It's very urgent.

**Comment by jedisct1** [comment]
Like all functions, the parameters are the same as in the C version except that lengths don't need to be explicitly specified.

So the parameters are:

- message
- additional data
- secret nonce
- public nonce
- key

**Comment by 1018715564** [comment]
I don't know why the package introduced through NPM has 6 parameters in the packaged JS code. Seeing the answers from other developers on the Internet, I found that someone passed the parameters as follows:



Sodium. crypto_aead_cha20poly1305_ietf_encrypt (message, ad, nonce, nonce, key, "");



I tried it, too. The strange thing is that it worked.
