### ISSUE TITLE
Test if string is a hash?

### ISSUE THREAD

**Issue by a-legrand** [jedisct1/libsodium.js#223]
Not an issue but a question :)

Is there a correct way to test if a string is the result of crypto_pwhash_str?
I can obvisouly test if the string starts with "$argon..." but if the algorithm changes in the future this is not reliable

many thanks for your work @jedisct1

**Comment by jedisct1** [comment]
Unfortunately, there isn't any reliable way to do it. You need to store this information along with the string.

**Comment by a-legrand** [comment]
Thanks for your quick reply :+1:
