### ISSUE TITLE
sodium.crypto_box_keypair is not a function

### ISSUE THREAD

**Issue by extreg** [jedisct1/libsodium.js#224]
Hi everyone,

I am loading sodium.js into my html file. I tried using Browser and Browser-sumo version.

I am testing out the library and trying to work from one of the test samples:
var aliceKeypair = sodium.crypto_box_keypair();
    var aliceSecret = Buffer.from(aliceKeypair.privateKey);
    var alicePublic = Buffer.from(aliceKeypair.publicKey);

I am getting TypeError: sodium.crypto_box_keypair is not a function error in my browser console.

any idea why this is happening? the library is loaded, and if I do console.log( sodium ); i can see the list of available functions, crypto_box_keypair() is one of them.

any help greatly appreciated. I am not running the site from nodejs. just standard html and js file loaded from apache.

**Comment by paragonie-scott** [comment]
Did you `await sodium.ready` first?

**Comment by extreg** [comment]
ya sorry, it was my bad. I had to put async on js file reference.
