### ISSUE TITLE
Missing some constants and functions

### ISSUE THREAD

**Issue by ffflorian** [jedisct1/libsodium.js#226]
Hey @jedisct1,

while cleaning up the [TypeScript definition files](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/libsodium-wrappers), I just noticed that the following constants are defined but not exposed in libsodium-wrappers v0.7.6 (and also not in libsodium-wrappers-sumo v0.7.6):

- [`crypto_secretstream_xchacha20poly1305_MESSAGESBYTES_MAX`](https://github.com/jedisct1/libsodium.js/blob/d2b312b84ca9563972d2f67e9cfc37ab5c868245/wrapper/constants.json#L113)
- [`crypto_secretstream_xchacha20poly1305_NPUBBYTES`](https://github.com/jedisct1/libsodium.js/blob/d2b312b84ca9563972d2f67e9cfc37ab5c868245/wrapper/constants.json#L114)

The same with the function [`randombytes_set_implementation()`](https://github.com/jedisct1/libsodium.js/blob/d2b312b84ca9563972d2f67e9cfc37ab5c868245/wrapper/symbols/randombytes_set_implementation.json).

Do you know why they are not exposed and do you plan to expose them? If not I will remove them from the TypeScript definition files.

---

**Example code using version 0.7.6:**

```js
const libsodium = require('libsodium-wrappers-sumo');

libsodium.ready.then(() => {
  console.log('crypto_secretstream_xchacha20poly1305_MESSAGESBYTES_MAX', libsodium.crypto_secretstream_xchacha20poly1305_MESSAGESBYTES_MAX)
  console.log('crypto_secretstream_xchacha20poly1305_NPUBBYTES', libsodium.crypto_secretstream_xchacha20poly1305_NPUBBYTES)
  console.log('randombytes_set_implementation', libsodium.randombytes_set_implementation)
});
```

**Console output:**

```
crypto_secretstream_xchacha20poly1305_MESSAGESBYTES_MAX undefined
crypto_secretstream_xchacha20poly1305_NPUBBYTES undefined
randombytes_set_implementation undefined
```

**Comment by jedisct1** [comment]
Looks like constants need to be manually defined in a `constants.json` file. I didn't even remember about that file.

Some constants may indeed be missing here.

I'm going to try to write something that generates them automatically, or at least check that the file is consistent with what's being defined in the library.

**Comment by ffflorian** [comment]
> Looks like constants need to be manually defined in a `constants.json` file

Yes, but the missing constants are defined in the file, but still missing in the generated JS file :slightly_smiling_face:

**Comment by jedisct1** [comment]
Ah, indeed. Well, let's do one thing at a time :)

**Comment by ffflorian** [comment]
True :slightly_smiling_face: if you need any help, let me know. :+1:

**Comment by jedisct1** [comment]
Typo:

```text
+   { "name": "crypto_secretstream_xchacha20poly1305_MESSAGEBYTES_MAX", "type": "uint" },
-  { "name": "crypto_secretstream_xchacha20poly1305_MESSAGESBYTES_MAX", "type": "uint" },
```

**Comment by jedisct1** [comment]
`randombytes_set_implementation` is not exported to Javascript from the library.

I'm to check whether it actually works from Javascript before enabling it.

**Comment by ffflorian** [comment]
@jedisct1 and what about `crypto_secretstream_xchacha20poly1305_NPUBBYTES`?

**Comment by jedisct1** [comment]
`crypto_secretstream_xchacha20poly1305_NPUBBYTES` doesn't exist anywhere.

`crypto_secretstream` creates nonces automatically; applications don't supply them.

**Comment by ffflorian** [comment]
> `crypto_secretstream_xchacha20poly1305_NPUBBYTES` doesn't exist anywhere.

Well, it exists in [`constants.json`](https://github.com/jedisct1/libsodium.js/blob/eb8df976bb6be882b000de5d62350db217b161be/wrapper/constants.json#L184) 🙂. Shall we then remove it from there?

**Comment by jedisct1** [comment]
I guess so :)

**Comment by ffflorian** [comment]
Alright, I'll create a PR tomorrow.
In the meantime, you could approve https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47535 if you like to :)
