### ISSUE TITLE
Produces the wrong signature

### ISSUE THREAD

**Issue by jcayzac** [jedisct1/libsodium.js#228]
[`crypto_sign_update()` uses Ed25519ph](https://libsodium.gitbook.io/doc/public-key_cryptography/public-key_signatures#multi-part-messages) but I can't reproduce the results mentioned in the official [test vectors](https://tools.ietf.org/html/rfc8032#section-7.3) with this library:

```js
const sodium = require('libsodium-wrappers')

const sk = Buffer.from('833fe62409237b9d62ec77587520911e9a759cec1d19755b7da901b96dca3d42', 'utf8')
const message = Buffer.from('616263', 'hex')

var state = sodium.crypto_sign_init()
sodium.crypto_sign_update(state, message)
var signature = Buffer.from(sodium.crypto_sign_final_create(state, sk)).toString('hex')
// Expected: 98a70222f0b8121aa9d30f813d683f809e462b469c7ff87639499bb94e6dae4131f85042463c2a355a2003d062adf5aaa10b8c61e636062aaad11c2a26083406
//      Got: d3c601adc2e867d0a8b19d0f2cd2a6d00b346cb00659ac15d6df92387e32390ec9fe1a8f466a9e468100afc47bf6af090a883ff5edecd1b9b26ac5428b694003
```

**Comment by jcayzac** [comment]
Actually I just tested with the C library and I get the same result. I've created an issue there: https://github.com/jedisct1/libsodium/issues/896

**Comment by jedisct1** [comment]
This is not a valid key pair.
