### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript

### ISSUE THREAD

**Issue by luugiathuy** [jedisct1/libsodium.js#23]
Thanks for the wrappers. However when I'm using the library on [ElectronJS](http://electron.atom.io) for my app, I got this error:

> Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'

on this line https://github.com/jedisct1/libsodium.js/blob/ab89d0100c960742186b3e3b373b5608cb0694a0/dist/modules/libsodium.js#L13. I think Chromium prevents execution from `eval` or `Function`. Do you know how to fix this error or anyway to work around this issue so that I can use the lib for my app? Thank you!

**Comment by jedisct1** [comment]
This is actually due to the Closure compiler, see https://github.com/kripken/emscripten/issues/2209

I recompiled the files without Closure. Which is pretty sad since it slightly increases the file size, but at least, it's going to work everywhere, no matter what the CSP rules are.

**Comment by luugiathuy** [comment]
@jedisct1: Thank you :+1: We're looking forward to the next release.
