### ISSUE TITLE
Suggested note to Compatibility section in README

### ISSUE THREAD

**Issue by j-berman** [jedisct1/libsodium.js#231]
libsodium.js a tool I wish I had put stronger consideration into using earlier on a separate project. One of the reasons I was deterred from using it was that the [Compatibility section](https://github.com/jedisct1/libsodium.js#compatibility) highlights that old browsers do not work with it and in some cases, produce incorrect results.

However, the project I'm working on currently relies on WebCrypto. Which I recently realized is [similarly incompatible](https://caniuse.com/#feat=cryptography) with nearly the same browsers listed in your compatibility section.

This was my fault for not realizing. However, I think it would be helpful for people like me in the future to include a note in the Compatibility section that says something along the lines of:

>Note: this is comparable to [the WebCrypto API](https://caniuse.com/#feat=cryptography), which is compatibile with a similar number of browsers.

Regarding producing incorrect results, this would be a bit worse for the project I'm working on because this means user data could be corrupted. If possible, additional information on what that entails (maybe, which functions produce incorrect results) would also be super helpful.

**Comment by jedisct1** [comment]
Added, thanks!

I don't remember the details of the issues we had with iOS 7, but this is probably not very relevant any more. I'm not even sure that the current version library will load at all on iOS 7, that was released 7 years ago.
