### ISSUE TITLE
Possible to do selective imports?

### ISSUE THREAD

**Issue by mobitar** [jedisct1/libsodium.js#232]
When running

```
export {
  ready,
  crypto_pwhash,
  crypto_pwhash_ALG_DEFAULT,
} from 'libsodium-wrappers';
```

the compiled result contains all libsodium algos (like Diffie-Hellmen related functions), and not just the explicit imports.

I see this issue: https://github.com/jedisct1/libsodium.js/issues/168

Could you possibly provide a tl;dr on what would need to be modified to allow this?

**Comment by collincusce** [comment]
Yes same. I was just doing a webpack analyzer and see this: https://i.imgur.com/uW7ToJX.png 

I added this library last night. It's great. It works. It supports my chacha needs. Holy cow, though, this is massive. I can't find a good way to reduce its size...

**Comment by collincusce** [comment]
I see this issue: 

https://github.com/jedisct1/libsodium.js/issues/156

I'm not quite sure how to make this workaround work for me, but it does seem like a viable option since I only need xchacha, randbuf, and pwhash.
