### ISSUE TITLE
Create Secret Keys from String

### ISSUE THREAD

**Issue by yslvlln** [jedisct1/libsodium.js#237]
Hi, I am currently working on a project in which android platform will send the encrypted message and decrypt it using my JS function. In my android project I tried creating a key using the ff snippet:
```
Key key = Key.fromPlainString("sampleSecret");
```
I wonder how can I achieve the same key using libsodium.js? I tried this snippet of code but thrown and error of invalid length.
```
let key = sodium.from_string('sampleSecret');
let ciphertext = sodium.crypto_secretbox_easy(message, nonce, key);
```

Thanks!

**Comment by jedisct1** [comment]
What you provided is password, not a secret key.

You can use `crypto_pwhash` to derive a key from a password.

Or if you really trust your password to really have enough entropy, use `crypto_generichash` to derive a key.

In both cases, the output length must be `crypto_secretbox_keybytes()` bytes long.

**Comment by yslvlln** [comment]
Sorry, im a bit confused. In my android project I encrypt using 
```
val key = Key.fromPlainString("test")
val ciphertext = la.cryptoSecretBoxEasy("plaintext", nonce, key)
```
How do I achieve this in JS?

**Comment by jedisct1** [comment]
Not sure what bindings you've been using for Android, but they should never have accept that as a key.

**Comment by yslvlln** [comment]
Hi @jedisct1, Appreciate the help i got it working.
