### ISSUE TITLE
problem with converting to javascript

### ISSUE THREAD

**Issue by arthur798** [jedisct1/libsodium.js#238]
Hi guys, I might be doing something wrong but I need to get publicKey as string, I am doing:

```      
const publicKey = this.sodium.crypto_box_keypair().publicKey.to_string()
```

however I am getting `this.sodium.crypto_box_keypair(...).publicKey.to_string is not a function`

also can u then generate keypair from public/private key so if a user has their private key from the above can u regenerate keypair?

**Comment by arthur798** [comment]
also tried
```
        const keypair = this.sodium.crypto_box_keypair()
        this.publicKey = keypair.publicKey
        console.log(this.sodium.to_string(this.publicKey))
```

Failed to execute 'decode' on 'TextDecoder': The encoded data was not valid.

**Comment by jedisct1** [comment]
Keys are binary data, not passwords. Non-UTF8 data cannot represent a string in Javascript.

You need to encode keys, for example into hexadecimal: `sodium.to_hex(key)`.
