### ISSUE TITLE
php encryption and js decryption, invalid keys?

### ISSUE THREAD

**Issue by arthur798** [jedisct1/libsodium.js#239]
publicKey = bXJ9KxXB6haPBoNOy2PfohaSRdbjqBp6x3oGk042MiY=
privateKey = ZgoTCNjvLzsFmKBNtCwdXGlmm1wslV3pfvtpFdxgs7g=

so in php i am encrypting like that:
```
            return sodium_crypto_box_seal($file_content, base64_decode('bXJ9KxXB6haPBoNOy2PfohaSRdbjqBp6x3oGk042MiY='));
```

I am able to decrypt with following code:

```
           $keypair = sodium_crypto_box_keypair_from_secretkey_and_publickey(base64_decode('ZgoTCNjvLzsFmKBNtCwdXGlmm1wslV3pfvtpFdxgs7g='), base64_decode('bXJ9KxXB6haPBoNOy2PfohaSRdbjqBp6x3oGk042MiY='));
           $decrypted = sodium_crypto_box_seal_open($encrypted, $keypair);
```

however doing similar code on javascript to decrypt :

```
          const publicKeyBase64 = "bXJ9KxXB6haPBoNOy2PfohaSRdbjqBp6x3oGk042MiY=";
          const privateKeyBase64 = "ZgoTCNjvLzsFmKBNtCwdXGlmm1wslV3pfvtpFdxgs7g=";
          const publicKey = this.sodium.from_base64(publicKeyBase64, this.sodium.base64_variants.ORIGINAL)
          const privateKey = this.sodium.from_base64(privateKeyBase64, this.sodium.base64_variants.ORIGINAL)
          console.log(privateKey)
          console.log(publicKey)
          const result = this.sodium.crypto_box_seal_open(this.encryptedFile, publicKey, privateKey);
```

however I am getting Error: incorrect key pair for the given

**Comment by jedisct1** [comment]
Check that `encryptedFile` is the same. For example that it has the same length than in PHP, and that it encodes to the same thing in hexadecimal.

**Comment by arthur798** [comment]
I believe it is I encrypt it in PHP and save it to Aws S3. Then retrieve the file and decrypt. I tried to retrieve file and decrypt in PHP and it worked fine

**Comment by jedisct1** [comment]
Once again, verify that what you hae in `this.encryptedFile` matches what you get in PHP.

**Comment by arthur798** [comment]
Yeah it is the same as I have retrieved the content the same way PHP does and I can decrypt it in PHP. I can pass the file over the encrypted one if you want but I am sure I have decrypted this file in PHP and can't do the same in JavaScript

**Comment by arthur798** [comment]
[asd.pdf](https://github.com/jedisct1/libsodium.js/files/4652488/asd.pdf)

That is the file which I grab content off and decrypt with php which works or grab the content and pass back to the frontend which doesn't work

**Comment by jedisct1** [comment]
Works fine:

```ts
const fetch = require('node-fetch'), _sodium = require('libsodium-wrappers');
(async () => {
    await _sodium.ready;
    const sodium = _sodium;

    const pk = sodium.from_base64("bXJ9KxXB6haPBoNOy2PfohaSRdbjqBp6x3oGk042MiY=", sodium.base64_variants.ORIGINAL);
    const sk = sodium.from_base64("ZgoTCNjvLzsFmKBNtCwdXGlmm1wslV3pfvtpFdxgs7g=", sodium.base64_variants.ORIGINAL);
    const c = new Uint8Array(await (await fetch("https://github.com/jedisct1/libsodium.js/files/4652488/asd.pdf")).arrayBuffer());
    const m = sodium.crypto_box_seal_open(c, pk, sk);
    console.log(m); // no exception; properly returns the unencryped file, whose length is 11607 bytes
})();
```

Check that you are reading binary content, not a UTF-8 or JSON string.

**Comment by arthur798** [comment]
That works! Didn't know I need to put the content of file into Uint8Array? How do I convert it back to string for users to be able to see the content?

**Comment by arthur798** [comment]
@jedisct1

**Comment by jedisct1** [comment]
In JavaScript like in most languages (PHP being an exception) strings can only contain characters. Sequence of things that can be displayed or typed on a keyboard.

If you want to store a sequence of arbitrary bytes, you must use an `Array<u8>` or (more efficient) a typed array `Uint8Array`.

But this is unrelated to libsodium and more about JavaScript, so you’d better ask on dedicated discussion boards where people far more skilled with JavaScript than me can help you.
