### ISSUE TITLE
crypto_sign_ed25519_sk_to_seed and crypto_sign_sk_to_seed are not present

### ISSUE THREAD

**Issue by SethiShivam** [jedisct1/libsodium.js#240]
Hi jedisct1  ,
I am using libsodium wrapper library for my nodejs and i want to extract seed and public key from private key  but i can't see those methods in libsodium-wrappers but the same are available in pysodium .

Could you please help me with that ?

Best Regards
Sethi Shivam

**Comment by jedisct1** [comment]
Looks like wrappers [exist](https://github.com/jedisct1/libsodium.js/blob/master/wrapper/symbols/crypto_sign_ed25519_sk_to_seed.json).

These functions are not part of the high-level APIs, so you must use `sumo` builds, not regular builds.

**Comment by SethiShivam** [comment]
What is the difference between both of them ?
