### ISSUE TITLE
Any alternate for crypto_scalarmult_curve25519_base

### ISSUE THREAD

**Issue by SethiShivam** [jedisct1/libsodium.js#241]
Hi Sir ,
As per your suggestion i am now using libsodium-wrapper-sumo . 
Do we have any alternative for this api  , As i have not found this api in my module but it is available in pysodium.

Thanks and Regards
Sethi Shivam

**Comment by jedisct1** [comment]
Just use `crypto_scalarmult_base()`.

**Comment by SethiShivam** [comment]
Thanks alot Sir ,I am actually new to  this library and i have given tasks to explore few functions .

crypto_box_open_afternm

crypto_box_afternm

and i am also looking for the alternative of these 2 libraries  and after this i am done .

**Comment by jedisct1** [comment]
`crypto_box_easy_afternm`, `crypto_box_open_easy_afternm`

The non-`easy` versions are deprecated, you shouldn't use them any more.

**Comment by SethiShivam** [comment]
so Which one do you recommend to use instead of above two?

Best Regards
Sethi Shivam

**Comment by jedisct1** [comment]
As written above, `crypto_box_easy_afternm` and `crypto_box_open_easy_afternm`.
