### ISSUE TITLE
Regression: package no longer works in react-native starting from libsodium-wrappers@0.7.7

### ISSUE THREAD

**Issue by tasn** [jedisct1/libsodium.js#249]
Hey,

It works great with libsodium-wrapper 0.7.6, though the moment I upgrade to 0.7.7 I get:
```
Error: Both wasm and asm failed to loadTypeError: undefined is not an object (evaluating 'I.asm.rc')
```
I've been fighting with this for hours now trying to figure out what was going on (as it was working in another project) until I decided to downgrade, which as I said, fixed it.

Please let me know if you need any more information.

**Comment by AlexMiniApps** [comment]
I have stuck with the same issue. The version 0.7.8 also has been checked.. and it also contains the issue.

**Comment by dractw** [comment]
Same issue here

**Comment by leonelvsc** [comment]
Same here

**Comment by leonelvsc** [comment]
Any update on this ?

**Comment by melMass** [comment]
Hi, is there any update on this, the issue is still there

**Comment by nikgraf** [comment]
We built https://github.com/serenity-kit/react-native-libsodium matching the libsodium-wrappers API and it works well for us (incl web support via react-native-web). That said so far it's only a subset of the API, but we are open to contributions.
