### ISSUE TITLE
Slow performance of crypto_pwhash compared to other JS implementations

### ISSUE THREAD

**Issue by tasn** [jedisct1/libsodium.js#250]
Hey,

I know that the implementation is slow on JS (I saw it [in the docs](https://libsodium.gitbook.io/doc/password_hashing#argon2)), and I understand this is the case. It actually works quite well for me in node and the browser (Firefox and Chrome on Linux), though it's painfully slow for me on Chrome/Firefox on Android, and Chrome on Windows (according to a user).

However, I just found another implementation that's order of magnitudes faster on JS:
http://antelle.net/argon2-browser/
It also seems to be implemented in C, I wonder if it makes sense to figure out what it is that they do and incorporate it into this lib? Or heck, even just use it directly?

@antelle: as the author of that lib, any idea what may be the difference?

Thanks!

**Comment by antelle** [comment]
Hi! I'm not sure which flags are used to build libsodium nowadays and I can't find any of its WASM builds either. In argon2-browser the argon2 library is compiled as-is, without any modifications, to WebAssembly using [this script](https://github.com/antelle/argon2-browser/blob/master/build-wasm.sh). Notable options related to optimization are:
```sh
CMAKE_C_FLAGS="-O3"
CMAKE_EXE_LINKER_FLAGS="-O3 -g0 -s DEMANGLE_SUPPORT=0 -s ASSERTIONS=0 <...>"
```
which is pretty standard, nothing special here.

**Comment by tasn** [comment]
Thanks for the feedback!
libsodium has its own argon2 implementation, I wonder if it makes sense to fallback to the reference one when compiling for the web.

**Comment by tasn** [comment]
I have another theory: maybe what's going on is that libsodium is falling back to asm.js in those cases and the tests I tried with argon2-browser use wasm. I'm still investigating.

**Comment by jedisct1** [comment]
The emitted JavaScript code is not even asm.js any more. As WebAssembly is becoming ubiquitous, the JavaScript code is really just there as a fallback option, but doesn't get asm.js optimizations.

So, yes, check that you are actually using the WebAssembly version.

The being said, Argon2 (or, really, any memory-hard function) is a really bad fit for JavaScript and for WebAssembly without 4Gb guard pages. To the point that I'd highly recommend using PBKDF2 with webcrypto instead.

**Comment by tasn** [comment]
God I wasted so much time on this. After a long of investigation and comparing libsodium and argon2-browser in different scenarios, it's indeed as I suspected, and it wasn't actually using WASM due to my CSP and the lack of `unsafe-eval`.
With that being said, http://antelle.net/argon2-browser/ still seems to be much faster on Firefox on Android (difference between never finishing and finishing after like 60 seconds). I'm not sure what's causing this one though.

As for PBKDF2: I wish I could, but I can't, it needs to be compatible with other clients that use argon2.

Let's close this ticket for now, and I'll update it if I get any more info.

Sorry for the noise.

**Comment by tasn** [comment]
Just for reference, this takes forever on Firefox on Android: https://stosb.com/~tom/sodium.html
While, this, with the same values, produces the same output and takes a very long time (but much less): http://antelle.net/argon2-browser/
Password: "bloop"
Salt: "0000000000000000"
Memory: 262144 (it's in KiB)
Iterations: 4

Both are very fast on firefox on Linux.
