### ISSUE TITLE
randombytes_buf() can't fill a buffer

### ISSUE THREAD

**Issue by christianbundy** [jedisct1/libsodium.js#252]
In C, this function takes a buffer and fills it with random data:

> ```c
> void randombytes_buf(void * const buf, const size_t size);
> ```
> The `randombytes_buf()` function fills `size` bytes starting at `buf` with an unpredictable sequence of bytes.
>
> -- https://doc.libsodium.org/generating_random_data

In libsodium.js, this function takes an integer, allocates a buffer, fills the buffer with random bytes, and returns it. This seems like the wrong behavior to me, since the readme says:

> The API exposed by the wrappers is identical to the one of the C library, except that buffer lengths never need to be explicitly given.
>
> -- https://github.com/jedisct1/libsodium.js#api

It seems to me that we should be taking `randombytes_buf(buf)` rather than `randombytes_buf(size)` and doing the allocation here. Would you be open to a pull request making a breaking change to resolve this behavior, or am I looking at it wrong? Thanks for your time!

**Comment by jedisct1** [comment]
The JavaScript bindings never take pointers to return an array. Having to do that is just a limitation of the C language.

The JavaScript bindings return results directly.

**Comment by christianbundy** [comment]
Thanks, that makes sense to me.
