### ISSUE TITLE
crypto_scalarmult_ed25519 functions are missing

### ISSUE THREAD

**Issue by FiloSottile** [jedisct1/libsodium.js#256]
Based on the README, I would have expected to find `crypto_scalarmult_ed25519_base` in the sumo package. Happy to make a PR if it's just a matter of adding a JSON to the wrappers folder.

**Comment by jedisct1** [comment]
Hi!

Yes, all functions are available but quite a lot of JavaScript wrappers are missing. Adding the missing functions would indeed just require relevant JSON definitions to be added.

If you could contribute the ones for `ed25519`, that would be great!
