### ISSUE TITLE
No crypto_sign_verify

### ISSUE THREAD

**Issue by Bilb** [jedisct1/libsodium.js#258]
Hi,
Sorry if this is a silly mistake, but I don't find the `crypto_sign_verify` type definition.
We do have a `crypto_sign_verify_detached`, but I guess it needs to be used for a `crypto_sign_detached` call.
Am I right in looking for this type definition?

Possibly related to https://github.com/jedisct1/libsodium.js/issues/80 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/27447

Thanks a lot

**Comment by ffflorian** [comment]
Hi @Bilb,

where do you see the function `crypto_sign_verify`?

**Comment by jedisct1** [comment]
It's called `crypto_sign_open()`.
