### ISSUE TITLE
The result of function 'crypto_core_ristretto255_is_valid_point' is different from native.

### ISSUE THREAD

**Issue by MichaelKim20** [jedisct1/libsodium.js#259]
I checked `true` as a result of the following code.
But isn't this value `false`?
```
        let p2 = Buffer.from("0000000000000000000000000000000000000000000000000000000000000000", "hex");
        let res2 = crypto_core_ristretto255_is_valid_point(p2);
        console.log(res2);
```

**Comment by jedisct1** [comment]
It is very likely that none of the ristretto functions used to work.

366fb21 makes these functions looks better. Untested, but that should be fixed in the next release.
