### ISSUE TITLE
Webworkers

### ISSUE THREAD

**Issue by yovanoc** [jedisct1/libsodium.js#262]
Is there a tutorial on how to use libsodium with webworkers? I see issues talking about this but I can't find a way, thanks.

**Comment by yovanoc** [comment]
anyone on this? :/

**Comment by jedisct1** [comment]
Apparently not :)

**Comment by andy-bin-cn** [comment]
Hi, @yovanoc  do you have find a way to use libsodium with webworkers?

**Comment by cooper667** [comment]
I've had no issues using libsodium in webworkers, using Vite/Rollup for bundling
