### ISSUE TITLE
Error: invalid usage [Chrome on Android]

### ISSUE THREAD

**Issue by vishnukvmd** [jedisct1/libsodium.js#270]
Hey, Chrome on Android devices is throwing the following error on calling `crypto_pwhash` with `crypto_pwhash_OPSLIMIT_SENSITIVE` and `crypto_pwhash_MEMLIMIT_SENSITIVE`:

```
index.tsx?d3bb:69 Error: invalid usage
    at g (libsodium-wrappers.js:1)
    at Object.sr [as crypto_pwhash] (libsodium-wrappers.js:1)
    at _callee17$ (libsodium.ts:797)
    at tryCatch (runtime.js?96cf:63)
    at Generator.invoke [as _invoke] (runtime.js?96cf:293)
    at Generator.eval [as next] (runtime.js?96cf:118)
    at asyncGeneratorStep (_index.mjs?a0f8:3)
    at _next (_index.mjs?a0f8:25)
```

The same code works on Firefox (on the same device) and across all browsers on iOS.

libsodium version: 0.7.9
Chrome version: 89.0.4389.105

Any help would be much appreciated!

Thanks again for this wonderful library.

**Comment by jedisct1** [comment]
`SENSITIVE` settings require a ton of memory, maybe more than allowed by the browser.

Reduce the memory limit to something reasonable and up the number of operations to compensate.

**Comment by vishnukvmd** [comment]
@jedisct1 thanks for the response!

I'm building an end-to-end encrypted storage service, where the user data is encrypted with a `masterKey`. This `masterKey` is stored on my servers after being encrypted with a key that is derived from the user's passphrase (using `crypto_pwhash`).

Lowering the limits would make it less difficult for me as a service provider to brute-force and derive the user's `masterKey`.

If you think there's a way to work around this, please let me know. If not please feel free to close this issue, I'll just block signups from Chrome on Android.

Thanks again!

**Comment by jedisct1** [comment]
You should really look at using zero-knowledge proofs and OPRFs instead.

**Comment by vishnukvmd** [comment]
The constraint I'm currently working with is that the `masterKey` has to be made available on the newest device a user signs into without blocking on the availability of other devices that could provide this information.

In future iterations, I will provide an option to transfer this information either out of band (QR code/manual entry), or via methods where in my servers have zero-knowledge, like you already suggested.

**Comment by jedisct1** [comment]
Reducing the required memory is fine as long as you are raising the number of operations accordingly. What really matters is the product of both parameters.

Anyway, good luck with your project!
