### ISSUE TITLE
Question - performance comparison between crypto and libsodium.js

### ISSUE THREAD

**Issue by p-b--** [jedisct1/libsodium.js#271]
Hello,

I've been using libsodium for a variety for projects, and was going to re-use it for a node.js project, however I noticed that there was a significant performance impact in using this in a node project.

I want to make sure this is expected, and not that I'm doing something wrong in the code I'm running.

This is the test code I used to performance test the two modules:
```
const _sodium = require('libsodium-wrappers');
const crypto = require('crypto');

const { PerformanceObserver, performance } = require('perf_hooks');

const obs = new PerformanceObserver((items) => {
  console.log(items.getEntries()[0].name, items.getEntries()[0].duration);
  performance.clearMarks();
});

obs.observe({ entryTypes: ['measure'] });

const loopcount = 5000;

const auth_tag_length = 16;

// weak constructs for demo
let nonce = Buffer.allocUnsafe(12, 0x00);
let key =  Buffer.allocUnsafe(32, 0x02);

let data = Buffer.alloc(65536, 0xbb);

performance.mark('crypto-start');
for (let i=1; i<=loopcount; i++) {
    let cipher = crypto.createCipheriv('chacha20-poly1305', key, nonce, { authTagLength: auth_tag_length });
    let dataciphered = cipher.update(data);
    cipher.final();
    let fullciphertext = Buffer.concat([dataciphered, cipher.getAuthTag()]);
    nonce.writeUInt16LE(i);
}
performance.mark('crypto-end');

performance.measure("crypto", "crypto-start", "crypto-end")


nonce = Buffer.allocUnsafe(12, 0x01);
(async() => {
    await _sodium.ready;
    performance.mark('libsodium-start');
    for (let i=1; i<=loopcount; i++) {
        fullciphertext = _sodium.crypto_aead_chacha20poly1305_ietf_encrypt(data, null, null, nonce, key);
        nonce.writeUInt16LE(i);
    }
    performance.mark('libsodium-end');
    performance.measure("libsodium", "libsodium-start", "libsodium-end")

})();
```

I ran these across a couple systems, and got these results:
```
crypto 419.948253
libsodium 5686.54988
```

```
crypto 351.376732
libsodium 3447.3915
```

No matter where I run this, I usually see an order of magnitude difference in execution time.

**Comment by jedisct1** [comment]
First, make sure that you are using the WebAssembly implementations and not something in pure JavaScript.

No matter if you are using JavaScript or WebAssembly, this is obviously always going to be slower than native code. I guess this project was mainly done for web browsers.

If you want to use libsodium in Node, [sodium-native](https://sodium-friends.github.io/docs/docs/getstarted) is likely to be faster.

**Comment by p-b--** [comment]
Thanks!

I'll take a look at that project, I really want to try to use libsodium wherever possible to reduce footguns.

I checked using the node inspector for this code and I saw WASM everywhere, so I'm going to _assume_ that it was using WASM, but is there any thing else I should do to ensure that I am using WebAssembly instead of pure JS?
