### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by claudiojulioferraz** [jedisct1/libsodium.js#276]
Hello! Is there any guide on how to use this library? Or do I have to read the source code for this project and the libsodium documentation and relate one thing to the other?

_Automatically translated._

**Comment by jedisct1** [comment]
Functions are the same as in the C version, and work the same way. The only difference is that array sizes are implicit.

The [README](https://github.com/jedisct1/libsodium.js#readme) file has some information about the peculiarities of the JS wrappers, but other than that, you can refer to the C documentation.

**Comment by claudiojulioferraz** [comment]
Understand. I don't program in C, but it doesn't seem difficult to understand. It would be nice to have javascript examples of each of the functions just to make things faster. Thanks!

Automatically translated.

**Comment by yukal** [comment]
Can you please add a description of why should I use this library in my NodeJS projects? Why, and what is the difference between this and the native library [crypto](https://nodejs.org/api/crypto.html) of NodeJS? What algorithms does this library use under the hood?
