### ISSUE TITLE
question: can I generate my own bundle?

### ISSUE THREAD

**Issue by panva** [jedisct1/libsodium.js#283]
👋 Is there a way I could generate a bundle with only a subset of functions? Either wasm, or js, or (preferably) both.

**Comment by jedisct1** [comment]
`libsodium/dist-build/emscripten-symbols.def` contains the list of symbols, each followed by two boolean values. If the first one is set, the symbol will be included in the standard build. If the second one is set, the symbol will be included in the sumo build.

**Comment by panva** [comment]
I have tried so. But probably did not build using the right command. I've made those changes and simply ran "make", the resulting bundle was however unchanged in exports and size.

**Comment by panva** [comment]
I just tried just setting all undesired symbols to 0 and running `make` but the resulting dist files are still packing everything.

**Comment by jedisct1** [comment]
Did you `make distclean` first?

**Comment by panva** [comment]
I did. No luck. I guess I'm way over my head.

If it isn't too much hassle for you, I only need these functions

```
_crypto_aead_xchacha20poly1305_ietf_decrypt
_crypto_aead_xchacha20poly1305_ietf_encrypt
_crypto_generichash
_crypto_stream_xchacha20_xor
```

A gist with wrappers and/or just libsodium.js would be appreciated, but I understand if this you don't have the time and energy.
