### ISSUE TITLE
async `crypto_pwhash`

### ISSUE THREAD

**Issue by Mister7F** [jedisct1/libsodium.js#287]
Hi :) 

I'm using `crypto_pwhash` but this function is slow and block the UI during it's execution, is there any way to make it asynchronous ?

**Comment by jedisct1** [comment]
Unfortunately not, but if you need something in Javascript, check out [scrypt-async-js](https://github.com/dchest/scrypt-async-js).

Or just use pbkdf2 from WebCrypto.
