### ISSUE TITLE
Is there a way to know what version is currently used (wasm/pure JS)?

### ISSUE THREAD

**Issue by rap2hpoutre** [jedisct1/libsodium.js#289]
Is there a way to know what version is currently used (wasm/pure JS)?

And is there a way to *choose* one version over another version?

**Comment by jedisct1** [comment]
Hi!

Your `package.json` file has the version used by your project, and also lets you choose a specific version to use.

If you are referring to the bundled libsodium version, this information is accessible via the `sodium_version_string()` function. The `SODIUM_LIBRARY_VERSION_MAJOR` and `SODIUM_LIBRARY_VERSION_MINOR` constants are also defined.

**Comment by rap2hpoutre** [comment]
Hi @jedisct1!

Thank you for your answer. My question was actually not clear, I apologize!

A bit of context: I'm using libsodium in two projects. One project *seems* to decrypt data really fast, the other one *seems* to be slower. Assuming this lib falls back to pure JS implementation when it fails to use wasm implementation (**maybe my assumption is false though)**, I wanted to be sure that both of my projects use wasm implementation.

Let me know if my question is not clear!

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium.js/issues/149#issuecomment-379317711
