### ISSUE TITLE
not work in node js

### ISSUE THREAD

**Issue by iocmet** [jedisct1/libsodium.js#291]
const sodium = require('libsodium-wrappers')
sodium.crypto_secretbox_easy(opuspacket, b, skey)

TypeError: sodium.crypto_secretbox_easy is not a function

**Comment by makarhuyaker** [comment]
fixed now

 UnhandledPromiseRejectionWarning: TypeError: invalid nonce length

**Comment by jedisct1** [comment]
The error looks self explanatory 😀

Your application supplied an incorrect nonce size.

**Comment by makarhuyaker** [comment]
what a nonce

**Comment by makarhuyaker** [comment]
i am trying to encode opus packets via libsodium and i get the secret key from discord voice gateway

**Comment by makarhuyaker** [comment]
but now i get this error: unsupported input type for key
