### ISSUE TITLE
TypeError: Cannot read property 'Qb' of undefined

### ISSUE THREAD

**Issue by ehamery** [jedisct1/libsodium.js#293]
Hi,
I am trying to use `libsodium-wrappers` in Typescript with:
```
import libsodium from 'libsodium-wrappers';
```
I am doing this in several files where I use `libsodium`.
But then if I import more than 1 of those files in the same file, any call to `await libsodium.ready` throws an exception:
```
TypeError: Cannot read property 'Qb' of undefined
    at Object.I._crypto_sign_seedbytes (/test/node_modules/libsodium/dist/modules/libsodium.js:1:316118)
    at Object.Bt [as crypto_sign_seed_keypair] (/test/node_modules/libsodium-wrappers/dist/modules/libsodium-wrappers.js:1:64050)
```
The object that is not defined is `I.asm`

Any idea what may cause that?
And how I can fix it?
Any help would be much appreciated.

**Comment by lmtr0** [comment]
are you using vite?

**Comment by ehamery** [comment]
@jedisct1 was the issue fixed?

**Comment by jedisct1** [comment]
I don't know :)

Someone asked you a question and you never replied, so I guess you don't need this any more?

**Comment by lmtr0** [comment]
It's surprising that after almost a year, the first question it was this fixed instead of helping us help you, ANYWAY!
For anyone having the same issues and that are using vite, here is the solution that worked for me.
The full source code is available here https://gitlab.com/higenku/apps/account/-/tree/dev/client?ref_type=heads

take a closer look into these files:
- https://gitlab.com/higenku/apps/account/-/blob/wip/client/vite.config.js?ref_type=heads#L25-26
- https://gitlab.com/higenku/apps/account/-/blob/wip/client/vite.config.js?ref_type=heads#L31-34
- https://gitlab.com/higenku/apps/account/-/blob/wip/client/package.json?ref_type=heads#L49-51

**Comment by ehamery** [comment]
It is even more surprising that nobody tried to reproduce the issue from the given description; and instead, after 10 months, wild guess is made to blame a third party module, ANYWAY!

I do not use [vitejs](https://vitejs.dev/) if that was what @lmtr0 was referring to.

**Comment by lmtr0** [comment]
I mean..... I'm not having that issue using vite with SvelteKit, as I described on the website that I was building using libsodium for encryption. Without a proper response to as which package bundler you are using (if using one at all) it's difficult to reproduce the issue. It's like trying to find hair in an egg without knowing what an egg is. You cannot expect developers to just go out of their way and test hundreds of javascript frameworks, package bundlers and UI libraries on hundreds of runtimes to try and find an error that YOU are having, IT IS A HUGE WASTE OF TIME. It's easier if you help us narrow down the problem, so we can be efficient

Moving on, are you using a package bundler at all? Are you using a static site generator, a framework or typescript? What are you trying to accomplish in a website, mobile app, desktop app with electron? Can you please describe your environment?

**Comment by lmtr0** [comment]
thx @jedisct1

**Comment by ehamery** [comment]
I am not sure why @lmtr0 you are insisting on adding extra parameters to the issue...
So instead of wasting time in litanies you could just read at the [description of the issue](https://github.com/jedisct1/libsodium.js/issues/293#issue-1112143853).
To make it even clearer:
- create 2 files `file1.ts` and `file2.ts`, in each:
  - add `import libsodium from 'libsodium-wrappers';` to the top
  - export a function that calls `await libsodium.ready` and another function from `libsodium`
- create a file `main.ts`, in it:
  - import `file1` and `file2`
  - call the exported function from `file1` and `file2`
- transpile/compile the 3 files to Javascript 
- call `node main.js`

No extra package, framework or whatever is needed.

**Comment by jedisct1** [comment]
* `file1.ts`:

```typescript
import libsodium from 'libsodium-wrappers';

export async function test() {
    await libsodium.ready;
    console.log('libsodium is ready');
}
```

* `file2.ts`:

```typescript
import libsodium from 'libsodium-wrappers';

export async function test2() {
    await libsodium.ready;
    console.log('libsodium is ready (2)');
}
```

* `main.ts`:

```typescript
import {test} from './file1';
import {test2} from './file2';

test();
test2();
```

* `package.json`:

```json
{ "dependencies": { "libsodium-wrappers": "^0.7.13" } }
```

Running:

```sh
$ bun main.ts

libsodium is ready
libsodium is ready (2)
```

No issues here.

That being said, initializing it twice is not expected. You should only initialize it once once your application starts, and then use that instance everywhere afterwards.

If it's not an actual application with a start function, just do something like:

```typescript
let _sodium: any;

export async function sodiumInstance() {
    if (!_sodium) {
        _sodium = await libsodium.ready;
    }
    return _sodium;
}
```

**Comment by lmtr0** [comment]
at this point we can assume that this is not an issue anymore, great, lets move on!

**Comment by lmtr0** [comment]
thank you and sorry for the extra work
