### ISSUE TITLE
[REQUEST] Precalculation interface

### ISSUE THREAD

**Issue by wilhelmmatilainen** [jedisct1/libsodium.js#30]
Could these be implemented?
I'm not familiar with emscripten.

http://doc.libsodium.org/public-key_cryptography/authenticated_encryption.html#precalculation-interface

crypto_box_beforenm
crypto_box_easy_afternm
crypto_box_open_easy_afternm

**Comment by jedisct1** [comment]
Hi Wilhelm,

They certainly can!

I'll try to do it soon.

**Comment by jedisct1** [comment]
These symbols are already exported in the emscripten code. So, what's really missing is the javascript wrappers.

**Comment by wilhelmmatilainen** [comment]
Could you bump the version and publish to the npm, so that this can be used?
