### ISSUE TITLE
function crypto_generichash_blake2b_salt_personal       id and ctx can't be null ?

### ISSUE THREAD

**Issue by vitock** [jedisct1/libsodium.js#303]
in [blake2b-ref.c](https://github.com/jedisct1/libsodium/blob/6d566070b48efd2fa099bbe9822914455150aba9/src/libsodium/crypto_generichash/blake2b/ref/blake2b-ref.c#L168) I found that both salt and personal could be null.

how could I set salt  without  setting ctx ?  

OR, blake2b has  a default salt or ctx ? I tried  Uint8Array filled with 0, it did not generate correct hash

**Comment by jedisct1** [comment]
Good catch.

The type for these parameters is `buf`. I guess it should be something like `buf_optional`.

It's quite surprising to see that such type is not implemented yet, as there are other functions with nullable fixed-size buffers.
