### ISSUE TITLE
Duplicate ​"​​crypto_aead_*" constants

### ISSUE THREAD

**Issue by Jack-Edwards** [jedisct1/libsodium.js#307]
Printing the sodium module in the browser reveals some duplicate constant values.  Their only differentiation is whether "IETF" is uppercase or lowercase.

Which set is "more correct"?  I don't want to map both sets, nor do I want to map the one set that may be removed in the future.

Uppercase `IETF`:
- crypto_aead_chacha20poly1305_IETF_ABYTES: 16
- crypto_aead_chacha20poly1305_IETF_KEYBYTES: 32
- crypto_aead_chacha20poly1305_IETF_MESSAGEBYTES_MAX: -17
- crypto_aead_chacha20poly1305_IETF_NPUBBYTES: 12
- crypto_aead_chacha20poly1305_IETF_NSECBYTES: 0
- crypto_aead_xchacha20poly1305_IETF_ABYTES: 16
- crypto_aead_xchacha20poly1305_IETF_KEYBYTES: 32
- crypto_aead_xchacha20poly1305_IETF_MESSAGEBYTES_MAX: -17
- crypto_aead_xchacha20poly1305_IETF_NPUBBYTES: 24
- crypto_aead_xchacha20poly1305_IETF_NSECBYTES: 0

Lowercase `IETF`:
- crypto_aead_chacha20poly1305_ietf_ABYTES: 16
- crypto_aead_chacha20poly1305_ietf_KEYBYTES: 32
- crypto_aead_chacha20poly1305_ietf_MESSAGEBYTES_MAX: -17
- crypto_aead_chacha20poly1305_ietf_NPUBBYTES: 12
- crypto_aead_chacha20poly1305_ietf_NSECBYTES: 0
- crypto_aead_xchacha20poly1305_ietf_ABYTES: 16
- crypto_aead_xchacha20poly1305_ietf_KEYBYTES: 32
- crypto_aead_xchacha20poly1305_ietf_MESSAGEBYTES_MAX: -17
- crypto_aead_xchacha20poly1305_ietf_NPUBBYTES: 24
- crypto_aead_xchacha20poly1305_ietf_NSECBYTES: 0
​

**Comment by jedisct1** [comment]
Use the lowercase ones (`crypto_aead_chacha20poly1305_ietf_ABYTES`).

The other ones are for backward compatibility with a very old version of libsodium.
