### ISSUE TITLE
Algorand/IOG libsodium VRF implementation for node js?

### ISSUE THREAD

**Issue by gitmachtl** [jedisct1/libsodium.js#314]
Hi,

thank you for your hard work!

I am searching for a node js compatible libsodium lib, that has the signing/verification feature for VRF keys/prove included. Like Algorand and IOG is using. Does anyone know if such a lib exists, or could it be added to this one?

Thank you very much.

Best regards,
 Martin

**Comment by jedisct1** [comment]
Try [ecvrf](https://www.npmjs.com/package/ecvrf) maybe?

**Comment by gitmachtl** [comment]
> Try [ecvrf](https://www.npmjs.com/package/ecvrf) maybe?

Hi, thx for the reply. No ecvrf is using a completly different VRF implementation than the Algorand/IOG implementation. I tried it a few hours ago. Here is a link to the Algorand/IOG c lib: https://github.com/algorand/vrf/blob/main/libsodium-vanilla-wrapper/vrf.c

**Comment by gitmachtl** [comment]
Its also related to: https://github.com/jedisct1/libsodium/pull/1188

**Comment by jedisct1** [comment]
As you saw here, the specification is still a work in progress.

So it's not going to be merged in libsodium until it is finalized.
