### ISSUE TITLE
Jest raises `Cannot read properties of undefined (reading 'sodium')`

### ISSUE THREAD

**Issue by fboucquez** [jedisct1/libsodium.js#315]
Hi team, jest is raising this error when trying to use a lib that depends on libsodium-wrappers

Minimal example:

```js
import _sodium from 'libsodium-wrappers'

test('sodium', () => {
  console.log(_sodium)
})
```

Any hint how to fix it?

**Comment by Moonligth1995** [comment]
https://github.com/jedisct1/libsodium.js/issues/315#issue-1618649434

**Comment by marcel-tomes** [comment]
```ts
import _sodium from 'libsodium-wrappers'

test('sodium', async () => {
  await _sodium.ready
  console.log(_sodium)
})
```

See https://github.com/jedisct1/libsodium.js#usage-as-a-module

Does this help?
