### ISSUE TITLE
Scrypt can't put values bigger than 8589934592

### ISSUE THREAD

**Issue by jmbm1989** [jedisct1/libsodium.js#32]
On the wrapprer there are a validation that says 

		if (!(typeof memLimit === "number" && (memLimit | 0) === memLimit) && (memLimit | 0) > 0) {
			_free_and_throw_type_error(address_pool, "memLimit must be an unsigned integer");
		}
I can't inform a memLimit value like 8589934593 or bigger.

and the problem is that (8589934593 | 0)  is -1 
                                     (8589934592 | 0)  is 0 

but as I understand it makeas a kind of negative countdown.

**Comment by jmbm1989** [comment]
You're doing a bitwise operation (simple |: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators#Bitwise_OR)

Because of that, this is done using a 32bit signed int.

Maybe you wanted to double it to use a binary logical operator (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_Operators#Logical_OR)

**Comment by jmbm1989** [comment]
The error is
Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 33554432, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

**Comment by jedisct1** [comment]
The upper limit is actually 2147483647.

Do you really need more than 2 Gb for this operation? That doesn't sound really practical, especially in a web browser environment.

In the asm.js specification, memory offsets are defined to be 32 bit integers. You can't have a 8 Gb heap.
