### ISSUE TITLE
In need a help

### ISSUE THREAD

**Issue by SwykanySolutions** [jedisct1/libsodium.js#321]
I need help, I'm using the libsodium-warpper library, but following the instructions inside the npm page, the concat method doesn't work anymore. I don't know if it's the java script or if there's a library missing.

```
ERROR:
    return nonce.concat(sodium.crypto_secretbox_easy(message, nonce, key));
                 ^
TypeError: nonce.concat is not a function
at encrypt_and_prepend_nonce 
```

**Comment by jedisct1** [comment]
Did you try checking what type `nonce` is?
