### ISSUE TITLE
Invalid pwhash salt length - 16 vs 32 bytes

### ISSUE THREAD

**Issue by stanhebben** [jedisct1/libsodium.js#325]
It seems the pwhash functions here expect a salt length of 16 bytes. However, libsodium (at least version 1.0.18) uses a 32 bytes salt.

Where does this difference come from, and is there a way to fix this discrepancy with the official libsodium version?

**Comment by jedisct1** [comment]
It's always been 16 bytes:

```c
#include <stdio.h>
#include <sodium.h>

int main(void)
{
    printf("%zu\n", crypto_pwhash_saltbytes());
    return 0;
}
```

```sh
$ zig cc a.c -lsodium
$ ./a.out

16
```

**Comment by stanhebben** [comment]
Seems the rust-sodium wrapper I was using defaults to scryptsalsa208sha256 instead of argon. Explicitly using the scryptsalsa208sha256 functions solves the issue (and that uses a salt of 32 bytes).
