### ISSUE TITLE
Argon2id usage

### ISSUE THREAD

**Issue by vault-thirteen** [jedisct1/libsodium.js#330]
Hello.

I am trying to understand how can I use this library to create a key using the Argon2id algorithm with custom settings.
Do I need the `sodium._crypto_pwhash` function for this ?
If yes, then where is the documentation for this function ?

I can see some pieces of words in the JavaScript file, but it is not clear what all this means:
`,B._crypto_pwhash=(A,I,g,C,a,e,_,t,r,o,i)=>(B._crypto_pwhash=T.cf)(A,I,g,C,a,e,_,t,r,o,i),`

I know that the library was originally written in C language, which uses different approach from JavaScript and documentation for the library written in C language differs from JavaScript variant.

It would be great if you could show where do I put such arguments as `password`, `salt`, `keySize`, `memory`, `numberOfIterations`.

I have the following code on my server side, which is written in Golang, and I want to do the same in this JavaScript port of C.
`key = argon2.IDKey(pwd, salt, Argon2Iterations, Argon2Memory, Argon2Threads, Argon2KeyLength)`

The documentation of the C variant located at https://doc.libsodium.org/password_hashing/default_phf has 8 arguments:
```
if (
		crypto_pwhash
		(
			key, 
			sizeof key, 
			PASSWORD, 
			strlen(PASSWORD), 
			salt,
			crypto_pwhash_OPSLIMIT_INTERACTIVE, 
			crypto_pwhash_MEMLIMIT_INTERACTIVE,
			crypto_pwhash_ALG_DEFAULT
		) != 0
) 
{
    /* out of memory */
}
```

The piece of JS abrakadabra has 10 arguments:
```
B._crypto_pwhash=
(
A,
I,
g,
C,
a,
e,
_,
t,
r,
o,
i
)
```

8 <> 10, so I assume that simple analogy does not work here.

Thank you.

**Comment by vault-thirteen** [comment]
It looks like this library is creating itself in runtime and my IDE sees only the code which is creating the library but not the library itself, so it says that this function does not exist. Is there any way to get the JS code which has explicit definitions of public functions so that my IDE is able to see it ?

**Comment by vault-thirteen** [comment]
It looks like have found a way. I need to develop my JS code inside a web browser, not inside the IDE ! Web browser shows that `sodium.crypto_pwhash()` is public and visible. Oh My God !..

**Comment by jedisct1** [comment]
You can look at the JSON files here: https://github.com/jedisct1/libsodium.js/tree/master/wrapper/symbols

But really, it's the same as the underlying library, without array lengths having to be explicitly passed as an argument. Pretty much identical to the PHP bindings.

**Comment by vault-thirteen** [comment]
Thank you.
