### ISSUE TITLE
@types/libsodium-wrappers missing type definitions for new 1.0.19 functions

### ISSUE THREAD

**Issue by bschick** [jedisct1/libsodium.js#334]
Version:  @types/libsodium-wrappers 0.7.13

Seems to be missing:
crypto_aead_aegis128l_*
crypto_aead_aegis256_*
crypto_kdf_hkdf_*

**Comment by jedisct1** [comment]
These definitions are maintained independently and are not part of this repository.

https://github.com/DefinitelyTyped/DefinitelyTyped seems to be the repository where they are maintained.

**Comment by ffflorian** [comment]
@bschick feel free to open a merge request in DefinitelyTyped.

**Comment by bschick** [comment]
@ffflorian I forked DefinitelyTyped and made changes that look to match the signatures in https://github.com/jedisct1/libsodium.js/tree/64c1a1fe56fabd32afe86876d5f7b51ef1c6a3e2/wrapper/symbols

Here is the diff from upstream
https://github.com/DefinitelyTyped/DefinitelyTyped/compare/master...bschick:DefinitelyTyped:master

I did not submit the pull request because:

1. When I try to call the aegis functions,libsodium wrappers throw:
TypeError:libsodium_wrappers__WEBPACK_IMPORTED_MODULE_1___default(...).crypto_aead_aegis256_encrypt is not a function

2. My intention was to also add the crypto_kdf_hkdf_* functions but I didn't find definitions anywhere in libsodium.js

Apologies if these are novice issues...  new TS and libsodium

**Comment by bschick** [comment]
@ffflorian pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69226
