### ISSUE TITLE
New 1.0.19 functions only partially supported

### ISSUE THREAD

**Issue by bschick** [jedisct1/libsodium.js#335]
While working on this issue: https://github.com/jedisct1/libsodium.js/issues/334 I hit errors trying to call the following 1.0.19 functions from plain old javascript:

crypto_aead_aegis128l_*
crypto_aead_aegis256_*
crypto_kdf_hkdf_*

After some grepping and simple tests, it looks like: 

1. The crypto_aead_aegis* functions are defined in normal npm libsodium-wrappers but not in the normal npm libsodium package. Therefore the following throws a TypeError in nodejs 21
```
const sodium = require('libsodium-wrappers');

sodium.ready.then( () => {
        let k1 = sodium.crypto_aead_aegis256_keygen();
        console.log(k1);
})
```
```
TypeError: sodium.crypto_aead_aegis256_keygen is not a function
    at /home/bschick/shared/lstest/index.js:
```

2. The crypto_aead_aegis* functions are present in both  libsodium-wrappers-sumo and libsodium-sumo and work as expected in a simple test. Since the crypto_aead_aegis* functions are "standard track" in libsodium 1.0.19, however, I expected them to be in both normal and sumo packages. 

3. crypto_kdf_hkdf_* don't seem to be present in either normal or sumo packages

I'll send a patch if I have time to dig into the libsodium.js build, but hoping a fix is quicker for someone already familiar.

**Comment by jedisct1** [comment]
Can you try the current code? The aegis functions are now in standard packages. Additionally, new emscripten versions removed support for a command-line flag we were using, which may have prevented some updates.

**Comment by bschick** [comment]
Cloning the libsodium.js repo and using the code from /dist I did get aegis functions to work from the non-sumo files. 

The crypto_kdf_hkdf functions I tested do not, for example:
```
TypeError: sodium.crypto_kdf_hkdf_sha256_extract is not a function
    at /home/bschick/shared/angular/lstest/index.js:30:19
```

**Comment by bschick** [comment]
@jedisct1 anything else you'd like me to try?

**Comment by jedisct1** [comment]
Looks like Javascript wrappers for these functions [don't exist](https://github.com/jedisct1/libsodium.js/tree/master/wrapper/symbols), so they have to be written 🤷

**Comment by bschick** [comment]
For the crypto_kdf_hkdf*, agreed. For the crypto_aead_aegis* functions they do exist, but I haven't gotten that to work in a browser project using angular and typescript. A bit of a novice on all this however (see above).
