### ISSUE TITLE
Is a new libsodium.js release planned?

### ISSUE THREAD

**Issue by stnmtz** [jedisct1/libsodium.js#341]
Hi there,

We've seen quite some changes to libsodium and libsodium.js repositories, but unfortunately missing a published NPM package of those changes. Is there any plan for a new libsodium.js release (and NPM updates) in near future?

Thanks and Best Regards

**Comment by jedisct1** [comment]
Yes, of course, releases happen from time to time.

Besides the addition of`crypto_auth_hmacsha512256`, I don't think there are practical differences between the last release on npm and the current code, so there's no urgency.
