### ISSUE TITLE
Implement package provenance

### ISSUE THREAD

**Issue by BANOnotIT** [jedisct1/libsodium.js#343]
By implementing package provenance, you enable final library users to audit supply chain. This is especially important for crypto libraries.

https://github.blog/security/supply-chain-security/introducing-npm-package-provenance/

**Comment by jedisct1** [comment]
libsodium nuget packages have had package provenance ever since that feature went public, so why not do it for npm packages as well, indeed.

**Comment by jedisct1** [comment]
> [Provenance limitations](https://docs.npmjs.com/generating-provenance-statements/#provenance-limitations)
> To publish a package with provenance, you must build your package with a supported cloud CI/CD provider using a cloud-hosted runner. Today this includes GitHub Actions and GitLab CI/CD.

Packages don't use GitHub Actions, so that can't work at the moment.
