### ISSUE TITLE
crypto_sign_ed25519_sk_to_curve25519 does not accept seeds as input

### ISSUE THREAD

**Issue by Skycoder42** [jedisct1/libsodium.js#347]
According to https://libsodium.gitbook.io/doc/advanced/ed25519-curve25519:

> However, the `crypto_sign_ed25519_sk_to_curve25519()` function accepts both these 64 byte keys, and the 32 byte seed returned by `crypto_sign_ed25519_sk_to_seed()`

This is true for libsodium itself, but the JS wrapper rejects inputs that are seeds. This is most likely because of size check that happens in the wrapper here: https://github.com/jedisct1/libsodium.js/blob/master/wrapper/symbols/crypto_sign_ed25519_sk_to_curve25519.json#L8

Please update the wrapper to accept both kinds of inputs.

**Comment by jedisct1** [comment]
I think the last 32 bytes are ignored. So in your Javascript app, you can just add 32 random (or zero) bytes after the seed.

**Comment by jedisct1** [comment]
The libsodium documentation has been updated to mention that only the first 32 bytes are used.
