### ISSUE TITLE
wrapper not clearing WASM memory after use?

### ISSUE THREAD

**Issue by NaveenNeti** [jedisct1/libsodium.js#349]
Hi,

I was interested in how secret clearing was happening, especially between the JS and WASM world. After reviewing the raw wrapper template file I saw:

```typescript
    function memzero(bytes) {
      if (!(bytes instanceof Uint8Array)) {
        throw new TypeError("Only Uint8Array instances can be wiped");
      }
      for (var i = 0 | 0, j = bytes.length; i < j; i++) {
        bytes[i] = 0;
      }
    }
```

This only clears the Uint8Array copied via the subarray allocated:

```typescript
    AllocatedBuf.prototype.to_Uint8Array = function () {
      var result = new Uint8Array(this.length);
      result.set(
        libsodium.HEAPU8.subarray(this.address, this.address + this.length)
      );
      return result;
    };
```

I then proceeded to see how it was managed by the compiled WASM code. After cloning and generating a non-minified version of the wrapper and taking keypair generation as an example:

```typescript
    function crypto_box_keypair(outputFormat) {
      var address_pool = [];

      _check_output_format(outputFormat);
      // ---------- output publicKey (buf)

      var publicKey_length = (libsodium._crypto_box_publickeybytes()) | 0,
          publicKey = new AllocatedBuf(publicKey_length),
          publicKey_address = publicKey.address;

      address_pool.push(publicKey_address);

      // ---------- output privateKey (buf)

      var privateKey_length = (libsodium._crypto_box_secretkeybytes()) | 0,
          privateKey = new AllocatedBuf(privateKey_length),
          privateKey_address = privateKey.address;

      address_pool.push(privateKey_address);

      if ((libsodium._crypto_box_keypair(publicKey_address, privateKey_address) | 0) === 0) {
      	var ret = {publicKey: _format_output(publicKey, outputFormat), privateKey: _format_output(privateKey, outputFormat), keyType: 'x25519'};
      	_free_all(address_pool);
      	return ret;
      }
      _free_and_throw_error(address_pool, "internal error");
    }
```

`_free_all` or `_free_and_throw_error` are called for the different cases. 

In the sodium source this seems to map to `utils.c` `sodium_free` which has:
```C

#ifndef HAVE_ALIGNED_MALLOC
void
sodium_free(void *ptr)
{
    free(ptr);
}
#else
void
sodium_free(void *ptr)
{
    unsigned char *base_ptr;
    unsigned char *canary_ptr;
    unsigned char *unprotected_ptr;
    size_t         total_size;
    size_t         unprotected_size;

    if (ptr == NULL) {
        return;
    }
    canary_ptr      = ((unsigned char *) ptr) - sizeof canary;
    unprotected_ptr = _unprotected_ptr_from_user_ptr(ptr);
    base_ptr        = unprotected_ptr - page_size * 2U;
    memcpy(&unprotected_size, base_ptr, sizeof unprotected_size);
    total_size = page_size + page_size + unprotected_size + page_size;
    _mprotect_readwrite(base_ptr, total_size);
    if (sodium_memcmp(canary_ptr, canary, sizeof canary) != 0) {
        _out_of_bounds();
    }
# ifndef HAVE_PAGE_PROTECTION
    if (sodium_memcmp(unprotected_ptr + unprotected_size, canary,
                      sizeof canary) != 0) {
        _out_of_bounds();
    }
# endif
    (void) sodium_munlock(unprotected_ptr, unprotected_size);
    _free_aligned(base_ptr, total_size);
}
#endif /* HAVE_ALIGNED_MALLOC */
```

I may be mistaken in one of my analysis steps, but it seems:
- The `free` calls don't explicitly zero out the memory?
- That a call with `memzero` could be called which will zero out the JS space secret but in the WASM memory space, the secret may still be resident, even if it is deallocated? (Will be written on overwrite)

Question:
Is there value in zeroing out the array before calling `_free_all`?

**Comment by jedisct1** [comment]
[The  `_free()` function](https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html) is part of the Emscripten library, not libsodium.

WebAssembly and JavaScript typically run on a JIT. They don't support volatile pointers, don't allow control over the instruction sets, don't provide any ways to interact with the JIT. JavaScript is GC'd and doesn't have pointers at all, so the JIT is also allowed to silently make as many copies of the data as needed.

All of that to say that it's very hard to make any promise about the fact that `memzero()` does anything useful on that platform. In fact, if it does, this is a bug or a missing optimization in the JIT. Allocations already add a lot of overhead, so I don't think we should add more, for an unreliable outcome.

There would be more value in avoiding all these `allocate()` and `_free()` calls by reusing a preallocated buffer as much as possible. That would be more efficient, and help overwrite previous data even without explicit calls to a zeroing function. 
I'm not familiar enough with the wrapper code generator to implement this, but supporting this is another justification for eventually rewriting this from scratch.

**Comment by NaveenNeti** [comment]
Hi @jedisct1 thank you for the write up. That definitely makes sense, especially if silent copies are being made on the JS/WASM side.

Given the JIT point, I guess it doesn't make sense, to zero anything on the C side either. 

I've been studying the un-minified wrapper file and it seems given the length of `provateKey_length`  may always be the same for keypair type, that `AllocatedBuf` could be a static allocation for `publicKey` and `privateKey`. 

Is this what you were suggesting for the pre-allocation side?

```typescript
const memory = new WebAssembly.Memory({ initial: 1 });
const buffer = new Uint8Array(memory.buffer);

const PUBLIC_KEY_OFFSET = 1024; 
const PRIVATE_KEY_OFFSET = PUBLIC_KEY_OFFSET + 32; 
const KEY_SIZE = 32;

function initialiseReusableKeyArrays() {
    const publicKey = new Uint8Array(buffer.buffer, PUBLIC_KEY_OFFSET, KEY_SIZE);
    const privateKey = new Uint8Array(buffer.buffer, PRIVATE_KEY_OFFSET, KEY_SIZE);
    return { publicKey, privateKey };
}

// Use buffers here for key generation

function clearKeyArray(keyArray) {
    keyArray.fill(0);
}
```

Is the above approach what you were thinking of?

I annotated the code below on where the approach may be used if correct? I'd be keen to contribute.

```typescript
    function crypto_box_keypair(outputFormat) {
      var address_pool = [];

      _check_output_format(outputFormat);

     // Don't use AllocatedBuf here but above static allocation
      var publicKey_length = (libsodium._crypto_box_publickeybytes()) | 0,
          publicKey = new AllocatedBuf(publicKey_length),
          publicKey_address = publicKey.address;

      address_pool.push(publicKey_address);

     // Don't use AllocatedBuf here but above static allocation
      var privateKey_length = (libsodium._crypto_box_secretkeybytes()) | 0,
          privateKey = new AllocatedBuf(privateKey_length),
          privateKey_address = privateKey.address;

      address_pool.push(privateKey_address);

      if ((libsodium._crypto_box_keypair(publicKey_address, privateKey_address) | 0) === 0) {
      	var ret = {publicKey: _format_output(publicKey, outputFormat), privateKey: _format_output(privateKey, outputFormat), keyType: 'x25519'};
        
        // Fill with 0 and re-use
      	_free_all(address_pool);
      	return ret;
      }
      // Fill with 0 and re-use
      _free_and_throw_error(address_pool, "internal error");
    }
```

Thanks again.
