### ISSUE TITLE
Error: module "libsodium" not found from "libsodium-wrappers.js"

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#36]
I tried to load libsodium via `sodium = require('libsodium-wrappers')` but everytime I get this message:

> Error: module "libsodium" not found from "libsodium-wrappers.js"

Can this be caused by the fact that libsodium exports `sodium` AND `libsodium`?

**Comment by jedisct1** [comment]
Is `libsodium.js` in a directory listed in your `NODE_PATH` environment variable?

**Comment by jedisct1** [comment]
If you just need to test in the current directory, the easiest way is just to use
```bash
export NODE_PATH=$(pwd)
```

```
$ node
> var s = require('libsodium-wrappers.js')
> s.sodium_version_string()
'1.0.5'
```
