### ISSUE TITLE
Recommended strategy to protect secret keys in JavaScript?

### ISSUE THREAD

**Issue by desertdev** [jedisct1/libsodium.js#38]
I'm new to libsodium and am wondering about how to use libsodium.js correctly on the client side. How is it possible to use functions that require a secret key parameter without exposing the secret key to the client? Or do I need to consider a different strategy altogether so secret keys are never needed on the client side?

**Comment by bitbeans** [comment]
the question is what exactly you want to achieve?

**Comment by desertdev** [comment]
Considering adding extra layer of encryption to post requests with sensitive data, but already using https as well. Perhaps this is overkill.

**Comment by jedisct1** [comment]
If you want to secure the transport, HTTPS (or HTTP/2) is all you need.
