### ISSUE TITLE
Error at _free_and_throw_error 

### ISSUE THREAD

**Issue by DanieleSassoli** [jedisct1/libsodium.js#39]
Hi,
I'm testing libsodium.js on node with mocha, when I try to decript some cripted data there's obviously something going wrong(otherwise I wouldn't see an error in _free_and_throw_error I guess), but I don't get any useful error message because `_free_and_throw_error throws an error (line 278 of dist/modules/libsodium-wrappers.js)`. 

Here are my crypt and decript functions: 
```javascript
this.nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
this.key = sodium.randombytes_buf(sodium.crypto_secretbox_KEYBYTES);
exports.cript = function (data) {
    this.sanitizeCrypt(data);
    data = new Buffer(data);
    return sodium.crypto_secretbox_easy(data, this.nonce, this.key, 'hex');
};
exports.decript = function (data) {
    this.sanitizeDecript(data);
    return sodium.crypto_secretbox_open_easy(data, this.nonce, this.key);
};
```
Surely I'm doing something wrong, but it looks like something's wrong in error handling.

**Comment by jedisct1** [comment]
Hi Daniele,

What do `sanitizeDecript()` and `sanitizeCrypt()` do?

Also, functions must be given a `Uint8Array`, not a `Buffer`.

**Comment by DanieleSassoli** [comment]
Sorry about not removing those lines, they don't change the data in any form, they only check that what I pass into the functions is defined and that it is what I intend to decript, they don't change the data in any way. I noticed that `crypto_secrebox_easy` and `crypto_secretbox_open_easy` convert whatever I pass to them to `Uint8Array` so I removed `new Buffer(data)` and just pass in a string, is that correct, or do I have to convert them to `Uint8Array` explicitly?
```javascript
this.nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
this.key = sodium.randombytes_buf(sodium.crypto_secretbox_KEYBYTES);
exports.cript = function (data) {
    return sodium.crypto_secretbox_easy(data, this.nonce, this.key, 'hex');
};
exports.decript = function (data) {
    return sodium.crypto_secretbox_open_easy(data, this.nonce, this.key);
};
```

**Comment by jedisct1** [comment]
You're encoding the ciphertext as a hex string, but try to decrypt it as a `UInt8Array`. Pick one, stick to it :)

If you don't need any encoding, remove that `hex` thing:
```javascript
return sodium.crypto_secretbox_easy(data, this.nonce, this.key);
return sodium.crypto_secretbox_open_easy(data, this.nonce, this.key);
};
```

If you need to encode the result as a hex string:
```javascript
return sodium.to_hex(sodium.crypto_secretbox_easy(data, this.nonce, this.key));
return sodium.crypto_secretbox_open_easy(sodium.from_hex(data), this.nonce, this.key);
```

**Comment by DanieleSassoli** [comment]
and that was pretty...obviuos, none the less I didn't manage to figure it out myself. Thank's, everything works like a charm now, thanks.

**Comment by DanieleSassoli** [comment]
oh, sorry, maybe I shouldn't be closing the issue, coz it wasn't related to my problem(which is fixed) but with a possible bug in error handling, dunno if you want to investigate further on the problem feel free to reopen the issue.
