### ISSUE TITLE
Where is crypto_hash_sha256 and crypto_hash_sha512?

### ISSUE THREAD

**Issue by terinjokes** [jedisct1/libsodium.js#41]
These functions exist in the wrapper, but aren't exported as they don't exist in libsodium. The README says they're included.

**Comment by jedisct1** [comment]
The README file has been fixed. Thanks for spotting this!

**Comment by jedisct1** [comment]
What is currently exported in the JavaScript version is only the high-level API (for authentication: `crypto_auth()`), and not low-level functions.

This might change later, probably by providing two versions of the library. One with only the high-level API, and a "fat" one with everything.

**Comment by terinjokes** [comment]
@jedisct1 I was switching from [`sodium`](https://github.com/paixaop/node-sodium), which exposes the low-level functions, but was complicating the build. [`js-nacl`](https://github.com/tonyg/js-nacl) also exposes the `crypto_hash_256` function.
