### ISSUE TITLE
"sodium.crypto_sign_keypair" is slow

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#42]
I have a fairly new computer (Intel Core i7-6500U, 16 GB RAM, SSD) running Windows 10 (64-bit). But when I execute `sodium.crypto_sign_keypair` in my browser (Chrome 47) then it takes 2-3 seconds to get the key pair. 

Do you experience the same performance issues with this call? If yes, is there anything which can be done to make it faster? Or do you know what specific calls inside `crypto_sign_keypair` slows it down? Maybe it's related to the entropy?

**Comment by jedisct1** [comment]
Maybe better now with webassembly?
