### ISSUE TITLE
sodium.crypto_aead_chacha20poly1305_encrypt is not a function

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [jedisct1/libsodium.js#43]
i want to use this lib's aead function, but the aead family cannot use.
may be dont export then?

I use it in browser with
```html
<script src="sodium.js" async defer></script>
```
and test it use this:
```javascript
temp = sodium.to_base64(
    sodium.crypto_generichash(
        64,
        TextIn
    )
);
```
it work.

but when i test aead with:
```javascript
temp = sodium.crypto_aead_chacha20poly1305_encrypt(
    TextIn,
    "124",
    undefined,
    "public_nonce",
    "key",
    "base64"
);
```
it not work and tell me <code>sodium.crypto_aead_chacha20poly1305_encrypt is not a function</code>

**Comment by jedisct1** [comment]
Hi,

And thanks for pointing out. These symbols were indeed not exported to the Javascript version.

I'm going to fix this shortly.

**Comment by jedisct1** [comment]
By the way, parameters must all be `Uint8Array`, not strings.

**Comment by jedisct1** [comment]
cdnjs version and npm packages will be updated after 1.0.9 is released, but meanwhile, you can get updated JS files here:

https://github.com/jedisct1/libsodium.js/tree/master/dist

`crypto_aead_chacha20poly1305` has been included: https://download.libsodium.org/libsodium.js/browsers-test/

Thanks!
