### ISSUE TITLE
crypto_aead_chacha20poly1305_decrypt not implemented in libsodium.js

### ISSUE THREAD

**Issue by garethlewis** [jedisct1/libsodium.js#45]
The libsodium_wrappers.js contains the function crypto_aead_chacha20poly1305_decrypt, but when you call this, an error is produced as this is not implemented in libsodium.js.  I can that this has been added to the master branch, but is not available in an actual tagged release, which is all I can choose in npm.

Would it be possible to publish an update based on master to npm.

**Comment by jedisct1** [comment]
Wait until 1.0.9 is released :)
