### ISSUE TITLE
Error 137 when using crypto_box_beforenm and crypto_box_easy

### ISSUE THREAD

**Issue by GeorgLippold** [jedisct1/libsodium.js#48]
I'm trying to use crypto_box_beforenm and crypto_box_easy like this in [Tonic](https://tonicdev.com/npm/libsodium), but always end up with error 137:
```javascript
require('libsodium');
var sodium = require('libsodium-wrappers');

// Preliminary key setup
var keyAlice = sodium.crypto_box_keypair(); 
var keyBob = sodium.crypto_box_keypair();

// this throws error 137 in Tonic
var sharedKey = sodium.crypto_box_beforenm(keyBob.publicKey, keyAlice.privateKey); 

var json = '{ "superSecretMessage":"test" }';
var nonce = sodium.randombytes_buf(sodium.crypto_box_NONCEBYTES);
// This also throws 137 in Tonic - suggest that the beforeNM function has a memory leak or similar?
var encrypted = sodium.crypto_box_easy(json, nonce, keyBob.publicKey, keyAlice.privateKey);
```

Any ideas how to fix this?

**Comment by jedisct1** [comment]
Weird. Looks fine here: https://tonicdev.com/572839d56ad20d11006fec5a/testforgeorg

Are you sure you gave the whole test case?

**Comment by jedisct1** [comment]
Googling for 'Error 137' tells that the actual error name is `ERR_NAME_RESOLUTION_FAILED`, i.e. there is a problem with your network connection or your DNS resolver.

This doesn't seem to have anything to do with libsodium :)

**Comment by GeorgLippold** [comment]
Thanks for your reply, and for looking at it so quickly.

It must have been a network / routing issue in Australia. Works now. I checked from two different Internet connections before I submitted it, and both could reproduce the error consistently at and before I lodged the ticket. It's working for me now, so I'm closing it.

Thanks!
