### ISSUE TITLE
Base64 output adding "\r\n" after 76 characters

### ISSUE THREAD

**Issue by peradym** [jedisct1/libsodium.js#49]
This might be intentional for compliance with base64 encoding, but parsing those characters out is required in order to not break the encryption.

Consider letting the user parse their base64 output into their own chunks or adding this information to documentation.

**Comment by jedisct1** [comment]
`to_base64()` has an optional, second argument (`noNewLine`), that can be set to `true` in order to avoid the new lines.

But the base64 encoding/decoding functions should be avoided, as they are not constant time.

I am going to remove them from the documentation until they get rewritten.

**Comment by jedisct1** [comment]
`from_base64()` seems to remove newlines and other characters that should not be part of base64- encoded data:

```js
sB64Enc = sBase64.replace(/[^A-Za-z0-9\+\/]/g, "")
```

So, `from_base64(to_base64(...))` should return the initial data even with the extra `\r\n`.

**Comment by jedisct1** [comment]
The default value for `noNewLine` in `to_base64()` was changed to `true`.

**Comment by peradym** [comment]
Thanks for your response. I do have a question about your recommendation of not using base64 encoding because the functions are not constant time. Do you only recommend this for data that should remain secret?

As far as I can understand, ciphertext data and nonces should have no problem being base64 encoded because the encoding type of the data itself should not introduce vulnerability. I suspect your concern with base64 encoding results from the ability for the data to be compromised through a timing attack because the function itself is not constant time. If this is true then I should only be concerned about base64 encoding secret/sensitive date and not be concerned with encoding non-sensitive data, correct?

I am using the crypto_aead_chacha20poly1305_encrypt function with the "base64" output option. This output is then saved to a database. If I understand correctly, there should be no problem using base64 encoding functions that are not constant time on this ciphertext output because the data is no longer highly sensitive information. That being said, no one should have access to information that they weren't meant to have in the first place.

Is my understanding correct? When it comes to handling sensitive data should I always use uint8array in a Buffer? Sorry if my questions are out of scope for this library or thread.
