### ISSUE TITLE
Add node-zopfli and uglify-js as devDependencies

### ISSUE THREAD

**Issue by fvgs** [jedisct1/libsodium.js#53]
This is just a suggestion, but it may make sense to add the two above-mentioned npm dependencies as devDependencies in `package.json` rather than requiring the contributor to install them globally. Installing dependencies locally is generally good practice.

The accompanying executables would be installed to `node_modules/.bin`, the path to which can be acquired using `npm bin`.

I actually spent far too much time trying to implement this myself prior to submitting my earlier PRs. I thought it might be the contributor's responsibility to update the `dist/` files, so I figured I'd make this change prior to building the project. Though I soon found out the build process takes an excruciatingly long time on my laptop, and I ran into errors when `make` tried to run Uglify.

But this should be a trivial improvement to make for someone better versed in Makefiles and better able to test the build than I.

**Comment by jedisct1** [comment]
No one jumped in, so closing :(
