### ISSUE TITLE
[Question]Sumo version of npm

### ISSUE THREAD

**Issue by zean00** [jedisct1/libsodium.js#56]
Hi,

How to get the sumo version of libsodium via npm? Through bower I can get several file distribution and I can just pick the sumo version, while in npm  I only get one file distribution and it's the standard version.

Thanks

**Comment by AgustinCroce** [comment]
Hi, the problem is in the package.json file. The files attribute has only `["dist/modules/libsodium-wrappers.js"]` so the sumo-modules is ignored if you install from npm.

I also want to know if there are a chance of adding the sumo-modules to the npm installation

**Comment by jedisct1** [comment]
The `sumo` variants are now available on npm!

https://www.npmjs.com/package/libsodium-sumo
https://www.npmjs.com/package/libsodium-wrappers-sumo
