### ISSUE TITLE
Default memory limit too low for `sodium.crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE`

### ISSUE THREAD

**Issue by creshal** [jedisct1/libsodium.js#60]
> Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 50331648, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

That's an awful lot less than the 1073741824 bytes `MEMLIMIT_SENSITIVE` needs. Same for Argon, it seems.

**Comment by jedisct1** [comment]
Allocating 1Gb+ for a single script in a web browser is not really practical.

I highly doubt you cannot use something more reasonable than `MEMLIMIT_SENSITIVE` here.

**Comment by creshal** [comment]
> Allocating 1Gb+ for a single script in a web browser is not really practical.

Nodejs in this case, not a browser. 

> I highly doubt you cannot use something more reasonable than MEMLIMIT_SENSITIVE here.

The current limit of 50MB isn't reasonable for password hashing in any form.

**Comment by jedisct1** [comment]
Avoid the pure javascript implementation in Node, especially with these functions.

Use Natrium or node-sodium instead. They are way faster.

**Comment by creshal** [comment]
> Use Natrium or node-sodium instead. They are way faster.

I know. But I'm running into build problems on Windows, which is why I was looking into this in the first place… oh well.

**Comment by jedisct1** [comment]
Changing the reserved memory to more than 1 Gb is going to make the library unusable for many people, for a use case that doesn't make much sense.

A better fix to do would be to address the build problems you are experiencing on Windows.

**Comment by jedisct1** [comment]
[node-sodium 1.1.7 released](https://github.com/paixaop/node-sodium/releases/tag/1.1.7)

    Added support for Windows installs without having to resort to a manual build.
