### ISSUE TITLE
sodium.crypto_pwhash missing?

### ISSUE THREAD

**Issue by twistylittleworkshop** [jedisct1/libsodium.js#63]
Apologies if being dim, but sodium.crypto_pwhash is undefined in the .min.js and .js browser downloads. The libsodium._crypto_pwhash is undefined also. Other functions (e.g. generic_hash etc.) are fine.

Am I missing a step or something equally obvious?

TIA

Edit: In the libsodium.js module, there is no reference to "..._crypto_pwhash..." either, but the libsodium-wrappers.js seems to expect them there? Apologies again if I'm way off base here - it's been a while since I waded through Emscripten  output...

**Comment by jedisct1** [comment]
As they are rarely used client-side, these functions are only available [in the sumo version](https://github.com/jedisct1/libsodium.js#standard-vs-sumo-version).

**Comment by twistylittleworkshop** [comment]
Ah, sumo it is then! Kicking myself after reading the relevant sentence on the front page!

Presumably, the allocate heap memory would slow interaction on a webage down; by what mechanism is it allocated (and can it be deallocated if this function is only required once in a protocol)?
