### ISSUE TITLE
Is it necessary to initialise libsodium.js like in the standard C library?

### ISSUE THREAD

**Issue by adk1010** [jedisct1/libsodium.js#64]
While investigating the sodium object that is provided by libsodium.js I noticed that it's possible for me to call this method: `libsodium._sodium_init();`.

Do I need to do this? I can't tell if libsodium.js needs initialising like the standard C library does.

**Comment by jedisct1** [comment]
You don't need to do this.

This is done automatically after the module is loaded.

**Comment by jedisct1** [comment]
To clarify: this is not required if you use the `libsodium-wrappers` module.

But it is required if you only include `libsodium.js`.

**Comment by adk1010** [comment]
> But it is required if you only include libsodium.js.

I'm directly including a copy of the sodium.min.js file so I'm guessing that means I should call `init()`?

**Comment by jedisct1** [comment]
You are correct. In that case, you need to call `_sodium_init()`.

**Comment by emugel** [comment]
Think it would be good to add a note about this in the README
