### ISSUE TITLE
Cannot install 0.4.0

### ISSUE THREAD

**Issue by Philipp91** [jedisct1/libsodium.js#68]
When I try to install the 0.4.0 release, I get the following error:

npm WARN install:libsodium@0.4.0 ENOENT: no such file or directory, open 'C:\...\node_modules\.staging\libsodium-822cf139\package.json'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\...\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.7
npm ERR! path C:\...\node_modules\.staging\libsodium-wrappers-d8637cfb\package.json
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\...\node_modules\.staging\libsodium-wrappers-d8637cfb\package.json'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\...\node_modules\.staging\libsodium-wrappers-d8637cfb\package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\...\npm-debug.log

0.3.1 works fine, I suspect it has to do with the changes in 6050d93c483ca5b26411939d92adff61bcea0db5 and fb50aca7676a422042951269d9631418bded53fb.

**Comment by jedisct1** [comment]
Should be fixed. Sorry for the inconvenience.
