### ISSUE TITLE
libsodium-wrappers-sumo npm package references unreleased version of libsodium

### ISSUE THREAD

**Issue by abovethewater** [jedisct1/libsodium.js#69]
Trying to use crypto_pwhash on the server-side, which requires the use of libsodium-wrappers-sumo.

Installing via npm produces the following error:

    npm install libsodium-wrappers-sumo --save
    npm ERR! Darwin 15.6.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "libsodium-wrappers-sumo" "--save"
    npm ERR! node v6.6.0
    npm ERR! npm  v3.10.3

    npm ERR! No compatible version found: libsodium@0.4.5
    npm ERR! Valid install targets:
    npm ERR! 0.4.1, 0.4.0, 0.3.1, 0.3.0, 0.2.12, 0.2.11, 0.2.10, 0.2.9, 0.2.8, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.2
    npm ERR!
    npm ERR!
    npm ERR! If you need help, you may report this error at:
    npm ERR!     <https://github.com/npm/npm/issues>

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/jmathews/work/dilysu/npm-debug.log

Looks like libsodium-wrappers-sumo was published 3 weeks ago at 0.4.5, but libsodium has not been updated on npm, which is still at 0.4.1, published 4 weeks ago.

Can this be updated?

Thanks.

**Comment by jedisct1** [comment]
It should be fixed.

For some reason, publishing to npm seems to be completely broken (OSX/Homebrew). I tried to publish from a Linux machine and it seems to have worked.

That's painful. Happy to see npm die now that we have yarn.

**Comment by abovethewater** [comment]
Thanks for the quick response.

Can confirm that this now installs, but I've had to raise another bug (#70)against the actual package installed. Looks like another npm headache. Sorry!
