### ISSUE TITLE
Uncaught ReferenceError: Module is not defined

### ISSUE THREAD

**Issue by taust** [jedisct1/libsodium.js#7]
I tried to use libsodium.js as discriped in your readme section *Usage with global definitions, for web browsers*, but loading of the js file failed with the error:

Uncaught ReferenceError: Module is not defined

the error is happening in line 13 of libsodium-wrappers.js because neither `root.libsodium` nor `Module` is defined. Is there a bug or am i missing something, maybe an undocumented dependency?

**Comment by jedisct1** [comment]
Hi,

Apparently, an upgrade of Emscripten or Closure caused the `Module` definition to be removed when using `--closure=1`.

A workaround has been added, and I also published a new version on npm and bower. Can you check if this fixes the issue you are seeing?

**Comment by bitbeans** [comment]
Hi, i had the same problem with 0.2.4.

0.2.5 seems to fix it, for me.

**Comment by jedisct1** [comment]
Glad to hear that it's working now! Thanks for reporting this.
