### ISSUE TITLE
crypto_secretbox_open_easy add characters at the end of the decryption result.

### ISSUE THREAD

**Issue by cocheok** [jedisct1/libsodium.js#71]
As we can see in the following code the output is: **Song is canción in Spanish!A** and not **Song is canción in Spanish!**

```
var text = 'Song is canción in Spanish!'
var key = '6de550be1ea85eec994e64a381a44582740967bf9c83e7105f9611923d99bb86';
var nonce = '474c38dacca0e0f41b8a247e0fb1b610a5f8b4fee213adb3';


var cipherText = sodium.crypto_secretbox_easy(text, sodium.from_hex(nonce), sodium.from_hex(key), 'hex');

 var result =  sodium.crypto_secretbox_open_easy(sodium.from_hex(cipherText), sodium.from_hex(options.nonce), sodium.from_hex(key), 'text'); 

console.log(result);
```

I've bypassed this Issue returning **hex** in fact of **text** in **crypto_secretbox_open_easy** and then parsing the result  to text.

```
var text = 'Song is canción in Spanish!'
var key = '6de550be1ea85eec994e64a381a44582740967bf9c83e7105f9611923d99bb86';
var nonce = '474c38dacca0e0f41b8a247e0fb1b610a5f8b4fee213adb3';


var cipherText = sodium.crypto_secretbox_easy(text, sodium.from_hex(nonce), sodium.from_hex(key), 'hex');

 var result = sodium.crypto_secretbox_open_easy(sodium.from_hex(cipherText), sodium.from_hex(options.nonce), sodium.from_hex(key), 'hex');

console.log(sodium.to_string(sodium.from_hex(result)));
```

**Comment by jedisct1** [comment]
Not sure why you are trying to call `crypto_secretbox_open_easy()` twice.

Just call it once:

```javascript
let ciphertext = sodium.crypto_secretbox_easy(text, sodium.from_hex(nonce), sodium.from_hex(key), 'hex')
let decrypted = sodium.crypto_secretbox_open_easy(sodium.from_hex(cipherText), sodium.from_hex(nonce), sodium.from_hex(key))
```

You can also use `sodium.from_string()` to convert a string to a bytes array, and `sodium.to_string()` to convert back a bytes array to a string.

**Comment by cocheok** [comment]
sorry, it's in one call the bypass is:

```

var text = 'Song is canción in Spanish!'
var key = '6de550be1ea85eec994e64a381a44582740967bf9c83e7105f9611923d99bb86';
var nonce = '474c38dacca0e0f41b8a247e0fb1b610a5f8b4fee213adb3';


var cipherText = sodium.crypto_secretbox_easy(text, sodium.from_hex(nonce), sodium.from_hex(key), 'hex');

 var result =  sodium.crypto_secretbox_open_easy(sodium.from_hex(cipherText), sodium.from_hex(options.nonce), sodium.from_hex(key), 'hex');

console.log(sodium.to_string(sodium.from_hex(result)));


```

**Comment by jedisct1** [comment]
I was referring to your first example.

**Comment by cocheok** [comment]
You're right, I've update the comment

**Comment by cocheok** [comment]
But the problem that i've report is that when I encrypt **Song is canción in Spanish!** and then decrtypted it, it adds me an **A** at the end. I can reproduce it with another examples. I thing that the problem is when I put an accent  **´** and when I inform **text** as an output.

**Comment by jedisct1** [comment]
The code above doesn't even parse as valid Javascript, so the actual code you are using is likely to be different.

Can you post a valid fiddle reproducing this issue?

Here is an example: https://jsfiddle.net/72cqt0tk/

**Comment by cocheok** [comment]
As i see, I was in an older version of the libsodium wrappers, 0.2.12.

**Comment by jedisct1** [comment]
That would explain it!

Glad you found the root cause!

Cheers.
