### ISSUE TITLE
How to export additional sodium methods?

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#73]
I installed `libsodium.js` via `bower install` and referenced it in my web application via:

```html
<script src="bower_components/libsodium.js/dist/browsers/combined/sodium.js"></script>
```

I noticed that I can use functions like `sodium.crypto_sign_keypair` or `sodium.crypto_scalarmult` but I need a few more like `sodium.crypto_hash_sha256` and others.

Unfortunately, I'm not a C programmer but maybe you can tell me the steps how to compile a version of `libsodium.js` with these additional methods?

- `sodium.crypto_auth_hmacsha256`
- `sodium.crypto_auth_hmacsha256_verify`
- `sodium.crypto_hash_sha256`
- `sodium.crypto_stream_chacha20_xor`

That would be great.

Best from Berlin,
Benny

**Comment by jedisct1** [comment]
Hi Benny,

Aren't these already available in the `sumo` build?

**Comment by bennyn** [comment]
The `sumo` build contains all of them except `crypto_stream_chacha20_xor`. 😢

**Comment by jedisct1** [comment]
Hi Benny,

I think `crypto_stream_chacha20_xor` is present in `libsodium.js`, and what is actually missing is the Javascript wrapper. Actually, there are no `crypto_stream_*` wrappers at all. Would you like to add them?

**Comment by bennyn** [comment]
I don't know the JavaScript wrapping process of `libsodium` very well but I would like to do the following:

```javascript
var message = 'Hello';

var nonce = [0, 1, 2, 3, 4, 5, 6, 7];
var nonceBuffer = new ArrayBuffer(nonce.length);
var typedNonce = new Uint8Array(nonceBuffer);

var keyMaterial = [5, 30, 208, 218, 140, 173, 89, 133, 238, 120, 243, 172, 56, 0, 84, 80, 225, 83, 110, 68, 59, 136, 105, 202, 200, 243, 73, 174, 28, 38, 66, 246];
var keyMaterialBuffer = new ArrayBuffer(keyMaterial.length);
var typedKeyMaterial = new Uint8Array(keyMaterialBuffer);

var encryptedMessage = sodium.crypto_stream_chacha20_xor(message, typedNonce, typedKeyMaterial, 'uint8array');
```

But from the current state this is not possible because `sodium.crypto_stream_chacha20_xor` cannot be called:

![capture](https://cloud.githubusercontent.com/assets/469989/22161709/eac123b8-df4b-11e6-80f3-8876185cfe71.PNG)

**Comment by bennyn** [comment]
@jedisct1 I have thought about the JavaScript wrappers... So it looks like that libsodium is compiled to libsodium.js (with emscripten) but then it still needs an additional JavaScript wrapper, which provides an interface for the JavaScript world to communicate with the libsodium.js functions, am I right?

If so, then I would need to provide a **crypto_stram_chacha20_xor.json** for https://github.com/jedisct1/libsodium.js/tree/master/wrapper/symbols?!

**Comment by jedisct1** [comment]
Hi Benny,

That is correct. The `libsodium` module is libsodium compiled with Emscripten. It can be used directly (for example the `._crypto_stream_chacha20*` methods are available. Notice the leading `_`).
But the wrapper is a higher layer that makes it easier to use by doing memory management for you, and by making the API shorter (sizes don't have to be provided to the methods, and 64-bit values are transparently split into two parameters).

In your case, additional `.json` files need to indeed be added in the `wrapper/symbols/` directory. There are no `crypto_stream` methods yet, but `crypto_box_*` methods are fairly similar.

**Comment by bennyn** [comment]
> The `libsodium` module is libsodium compiled with Emscripten. It can be used directly (for example the `._crypto_stream_chacha20*` methods are available. Notice the leading `_`).

I tried now the following:

```bash
npm install libsodium
```

```javascript
var libsodium = require('libsodium');
var encrypted_buffer = libsodium._crypto_stream_chacha20_xor(plaintext, nonce, @key, 'uint8array');
```

But it tells me:

> TypeError: libsodium._crypto_stream_chacha20_xor is not a function

So I have to find another library which provides me a `chacha20_xor` function out of the box. Unfortunately, there is only [chacha20](https://github.com/quartzjer/chacha20) which is not xor'ed.

**Comment by bennyn** [comment]
@jedisct1 At [Wire](https://wire.com/) we forked libsodium.js to export `crypto_stream_chacha20_xor` (https://github.com/wireapp/libsodium.js/commit/2e4be94b7275d0441520f02088851ce45baff7c8). 

Our fork is based on libsodium.js v0.2.10 but we don't want to maintain this fork anymore (because there is already libsodium.js v0.4.8). So our idea was to go with the libsodium Sumo builds (which expose everything we need except `crypto_stream_chacha20_xor`).

We could again fork libsodium.js and export that specific function. But doing this every now and then is a cat-and-mouse game which we would like to avoid to play (especially in the context of security & cryptography).

I understand that you don't want to export every function of `sodium` to keep libsodium.js' core compact with the most necessary features to everyone. That's okay. 

But is it maybe possible to provide some kind of plugin system for users, who need more functionality, but don't want to lose track from the original source?

I recently worked with [Popsicle](https://github.com/blakeembrey/popsicle), which has a really nice plugin system. It's a library from a completly different context but it's approach might be suitable also for libsodium.js.

With Popsicle you can get the core library (for HTTP functionality) but also extensions like `popsicle-status` (to simplify HTTP status code handling):

**Example**

```javascript
var popsicle = require('popsicle');
var status = require('popsicle-status');

return popsicle.request({
  method: 'POST',
  url: 'http://example.com/api/users'
}).use([status(), popsicle.plugins.parse('json')]);
```

Do you think it's possible to provide something similar for libsodium.js?

**Idea**

```javascript
var libsodium = require('libsodium'); // sodium core library
var crypto_stream = require('libsodium-crypto-stream'); // plugged in stream ciphers

...

var encryptedMessage = crypto_stream.chacha20_xor(message, nonce, key, 'uint8array');
```

I really hope that we can find a solution.

Many greetings from snowy Berlin,

Benny

**Comment by jedisct1** [comment]
The sumo builds include `crypto_stream_chacha20_xor()`:
```js
let libsodium = require('libsodium-sumo')
typeof(libsodium._crypto_stream_chacha20_xor)
```
```
[Function: be]
```

**Comment by bennyn** [comment]
Thanks for the info. Is the signature of `_crypto_stream_chacha20_xor` the following?

`libsodium._crypto_stream_chacha20_xor(output_message_address, input_message_address, input_message_length, 0, nonce_address, key_address)`

**Comment by jedisct1** [comment]
Hi Benny,

Yes, that looks like the correct signature!

**Comment by bennyn** [comment]
> Yes, that looks like the correct signature!

Ok. So I need to write a wrapping function so that I can use `libsodium._crypto_stream_chacha20_xor` (which requires 6 parameters) to be able to call it with only 4 parameters, like in my examples before:

```javascript
crypto_stream_chacha20_xor(message, typedNonce, typedKeyMaterial, 'uint8array');
```

It will look similar to this:

```javascript
var libsodium = require('libsodium-sumo');
var wrapper = require('libsodium-wrappers-sumo');

/*
 * Wrapping:
 * _crypto_stream_chacha20_xor(output_message_address, input_message_address, input_message_length, 0, nonce_address, key_address)
 *
 * Into:
 * crypto_stream_chacha20_xor(input_message, nonce, key, outputFormat)
 */
function crypto_stream_chacha20_xor(input_message, nonce, key, outputFormat) {
    var address_pool = [];
    wrapper._check_output_format(outputFormat);

    // ---------- input: input_message (unsized_buf)

    input_message = wrapper._any_to_Uint8Array(address_pool, input_message, "input_message");
    var input_message_address = wrapper._to_allocated_buf_address(input_message),
        input_message_length = input_message.length;
    address_pool.push(input_message_address);

    // ---------- input: nonce (buf)

    nonce = wrapper._any_to_Uint8Array(address_pool, nonce, "nonce");
    var nonce_address, nonce_length = (libsodium._crypto_stream_chacha20_noncebytes()) | 0;
    if (nonce.length !== nonce_length) {
        wrapper._free_and_throw_type_error(address_pool, "invalid nonce length");
    }
    nonce_address = wrapper._to_allocated_buf_address(nonce);
    address_pool.push(nonce_address);

    // ---------- input: key (buf)

    key = wrapper._any_to_Uint8Array(address_pool, key, "key");
    var key_address, key_length = (libsodium._crypto_stream_chacha20_keybytes()) | 0;
    if (key.length !== key_length) {
        wrapper._free_and_throw_type_error(address_pool, "invalid key length");
    }
    key_address = wrapper._to_allocated_buf_address(key);
    address_pool.push(key_address);

    // ---------- output output_message (buf)

    var output_message_length = (input_message_length) | 0,
        output_message = new wrapper.AllocatedBuf(output_message_length),
        output_message_address = output_message.address;

    address_pool.push(output_message_address);

    if ((libsodium._crypto_stream_chacha20_xor(output_message_address, input_message_address, input_message_length, 0, nonce_address, key_address)) === 0) {
        var ret = wrapper._format_output(output_message, outputFormat);
        wrapper._free_all(address_pool);
        return ret;
    }
    wrapper._free_and_throw_error(address_pool);
}

var message = 'Hello';

var nonce = [0, 1, 2, 3, 4, 5, 6, 7];
var nonceBuffer = new ArrayBuffer(nonce.length);
var typedNonce = new Uint8Array(nonceBuffer);

var keyMaterial = [5, 30, 208, 218, 140, 173, 89, 133, 238, 120, 243, 172, 56, 0, 84, 80, 225, 83, 110, 68, 59, 136, 105, 202, 200, 243, 73, 174, 28, 38, 66, 246];
var keyMaterialBuffer = new ArrayBuffer(keyMaterial.length);
var typedKeyMaterial = new Uint8Array(keyMaterialBuffer);

var encryptedMessage = libsodium.crypto_stream_chacha20_xor(message, typedNonce, typedKeyMaterial, 'uint8array');

console.log('Result', encryptedMessage);
```

I will post an update here as soon as it works. Thanks for your patience, @jedisct1.

**Comment by ffflorian** [comment]
@jedisct1 

We created a module [libsodium-addons](https://github.com/wireapp/libsodium-addons/), to additionally expose needed functions (for now only `crypto_stream_chacha20_xor`), which can be used in addition to `libsodium.js`.

Working example:
```js
const addons = require('./libsodium-addons/dist/index');

const message = 'Hello';

const nonce = [0, 1, 2, 3, 4, 5, 6, 7];
const nonceBuffer = new ArrayBuffer(nonce.length);
const typedNonce = new Uint8Array(nonceBuffer);

const keyMaterial = [5, 30, 208, 218, 140, 173, 89, 133, 238, 120, 243, 172, 56, 0, 84, 80, 225, 83, 110, 68, 59, 136, 105, 202, 200, 243, 73, 174, 28, 38, 66, 246];
const keyMaterialBuffer = new ArrayBuffer(keyMaterial.length);
const typedKeyMaterial = new Uint8Array(keyMaterialBuffer);

const encryptedMessage = addons.crypto_stream_chacha20_xor(message, typedNonce, typedKeyMaterial, 'uint8array');

console.log('Result', encryptedMessage);
```

Since we took the [necessary](https://github.com/wireapp/libsodium-addons/blob/master/dist/index.js#L7) [functions](https://github.com/wireapp/libsodium-addons/blob/master/dist/tools.js#L6) from `libsodium.js`, we would like to ask you - which license would you suggest for our addons and who should be the author and contributor(s)?

**Comment by jedisct1** [comment]
Hi Florian,

Maybe these can be directly merged to `libsodium.js`?

**Comment by ffflorian** [comment]
@jedisct1 
Yes, I can add the `constants` and the `symbols`, could you do the rebuild then (since I don't have an `emscripten` setup)?
I also don't know exactly how to write a test which would suit your standards 🙂

**Comment by bennyn** [comment]
@jedisct1 Since jedisct1/libsodium.js#78 got merged, can you please make a new libsodium.js release version? Because then we can also close this issue here. 🔨

**Comment by bennyn** [comment]
I can see that npm is on 0.4.9 👏 ([libsodium-wrappers-sumo)](https://www.npmjs.com/package/libsodium-wrappers-sumo). Only thing missing now is a new Bower version via [GitHub releases](https://github.com/jedisct1/libsodium.js/releases).

**Comment by ffflorian** [comment]
I see, the release version is online! 🎉 
Thank you @jedisct1!

**Comment by jedisct1** [comment]
Thanks a lot for your help!

Hope this version works as expected for you!

**Comment by Jack-Edwards** [comment]
Is `_to_allocated_buf_address()` still around?  I cannot find it in any of the NPM packages.  I've checked libsodium-sumo, libsodium-wrappers, and libsodium-wrappers-sumo.
