### ISSUE TITLE
Documentation of "libsodium-sumo" is misleading

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#75]
I wanted to use the Sumo version of libsodium.js found on npm: https://www.npmjs.com/package/libsodium-sumo

[The readme](https://www.npmjs.com/package/libsodium-sumo#usage-with-commonjsamdes6-import) tells me that I need to do the following (in order to use it):

```javascript
var sodium = require('libsodium-wrappers');
console.log(sodium.to_hex(sodium.crypto_generichash(64, 'test')));
```

Doing this results in the following error:

> Error: Cannot find module 'libsodium-wrappers'

I think the correct execution would be:

```javascript
var sodium = require('libsodium-wrappers-sumo');
console.log('Hex', sodium.to_hex(sodium.crypto_generichash(64, 'test')));
```

But this also required to run:

```bash
npm i libsodium-wrappers-sumo
```

**Comment by jedisct1** [comment]
Does npm allow specifying where the `README` file to display is?

The source code for the `sumo` and the normal version is the same, the repository is the same, and compiling it produces both versions.

So I don't know what a clean way to have different README files would be.

**Comment by bennyn** [comment]
@jedisct1 Doesn't npm take an exact copy of the `README.md` when publishing a new version? In that case you would need to check the import statements of `README.md` when executing `npm publish`.

**Comment by jedisct1** [comment]
Unfortunately, there are no statements for the `README.md` file :(
