### ISSUE TITLE
[Question] is crypto_pwhash safe to use?

### ISSUE THREAD

**Issue by bufke** [jedisct1/libsodium.js#79]
>Alternatively, the "sumo" version, available in the dist/browsers-sumo and dist/modules-sumo directories contains all the symbols from the original library. **This includes undocumented, untested, deprecated, low-level and easy to misuse functions.**
The crypto_pwhash_* function set is also only included in the Sumo version.

At this time are crypto_pwhash_* functions "safe" to use in production environments? I ask because my use case requires user typed passwords for encryption. As I understand it, without using something like crypto_pwhash_scryptsalsa208sha256 it would be considered dangerous to encrypt private keys using human typeable (short) passwords.

**Comment by jedisct1** [comment]
Yes, they are totally "safe" to use in production.

The main reason these are only available in the sumo builds is that they intentionally require a lot of memory compared to other functions, so they may not be suitable to all environments.

You may want to use `crypto_pwhash` (Argon2) over `crypto_pwhash_scryptsalsa208sha256()` though.

**Comment by bufke** [comment]
Great - makes sense.
