### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by gpalomar** [jedisct1/libsodium.js#81]
Hi Frank!

I'm having trouble generating Argon2i hashes using your sumo build. It seems to take a long time to generate them in Chrome whereas in Firefox I have no problems. (Chrome takes approximately x5 more time than Firefox).
The problem seems to be that Chrome is not optimizing well ASM while other browsers, such as Firefox, do.

The solution would be to use WASM, which will be supported by Firefox version 52 (currently at version 50) and by Chrome version 57 (currently at version 56).
Also, it seems that Emscripten already supports it.

Are there any plans to add WASM support for LibsodiumJS in the future?

Sources:
Firefox v52 release notes: https://developer.mozilla.org/en-US/Firefox/Releases/52
Chrome platform status: https://www.chromestatus.com/feature/5453022515691520
Emscripten WASM: https://github.com/kripken/emscripten/wiki/WebAssembly

**Comment by jedisct1** [comment]
Yes, WASM is absolutely something we need.

There are still a few things to fix, but it's mostly working, see https://github.com/jedisct1/libsodium/issues/475

**Comment by jedisct1** [comment]
By the way, Firefox is currently at version 52. Which does support WASM :)

**Comment by BurningEnlightenment** [comment]
> Firefox is currently at version 52. Which does support WASM

sadly WASM support is disabled in the ESR (Extended Support Release) version 😞

**Comment by jedisct1** [comment]
Ready for testing.
