### ISSUE TITLE
Strange long delay in fourth execution of cryoto_sign_detached in fresh process

### ISSUE THREAD

**Issue by yan-foto** [jedisct1/libsodium.js#84]
I came across this issue while I was executing my tests. I noticed that `crypto_sign_detached` is taking much longer in one case compared to the rest and I found out that it's the `crypto_sign_detached`. It can be reproduced rather easily:

```js
const sodium = require('libsodium-wrappers')
const crypto = require('crypto')

const key_pair = sodium.crypto_sign_seed_keypair(crypto.createHash('SHA256').update('user:pass', 'utf8').digest())
const hash = Uint8Array.from(crypto.createHash('SHA256').update('payload', 'utf8').digest())

for(let i = 0; i < 10; i++) {
  console.time(`sign:${i}`)
  sodium.crypto_sign_detached(hash, key_pair.privateKey)
  console.timeEnd(`sign:${i}`)
}
```

In my setup it is always the 4th iteration (`sign:3`) that is taking much longer (seconds instead of milliseconds). I could reproduce this on node `v6.10.0` with libsodium `v0.4.9`.

---
This is the console output, when I run the aforementioned script on my computer:

```
sign:0: 111.292ms
sign:1: 5.195ms
sign:2: 9.040ms
sign:3: 3453.915ms
sign:4: 3.584ms
sign:5: 14.469ms
sign:6: 4.008ms
sign:7: 13.127ms
sign:8: 14.750ms
sign:9: 11.061ms
```

**Comment by maccheck** [comment]
I can confirm the aforementioned unusual timing behavior with libsodium-wrappers v0.4.9 and node v6.10.0 and v4.8.0.

**Comment by jedisct1** [comment]
Welcome to the world of Just-In-Time compilers :)

**Comment by jedisct1** [comment]
On the bright side, it doesn't seem to be visible with current versions of Node (tested with `v7.7.2`).

**Comment by yan-foto** [comment]
@jedisct1 That was quick! 😅 

I haven't got deep into how node/V8 handles JIT compiling. But it sure is interesting to know, how it can ruin your expectations on a very systematic way!

**Comment by maccheck** [comment]
With node v7.7.2 there still is a delay in 4th iteration for me, but it's not that noticeable anymore:

```
sign:0: 28.215ms
sign:1: 9.264ms
sign:2: 11.697ms
sign:3: 145.884ms
sign:4: 4.201ms
sign:5: 7.488ms
sign:6: 4.688ms
sign:7: 4.008ms
sign:8: 4.117ms
sign:9: 4.116ms
```

**Comment by jedisct1** [comment]
Early tests with WASM show that the delay is completely gone :)

**Comment by yan-foto** [comment]
I'd close this issue then!
