### ISSUE TITLE
support for URLSafeBase64encoder ?

### ISSUE THREAD

**Issue by mitra42** [jedisct1/libsodium.js#87]
Has anyone figured out how to support the URLSafeBase64encoder ? 

I'm trying to get libsodium to talk to an app using PyNaCl, everything is being transferred as URLSafeBase64encoder so that it can be easily encapsulated in JSON, but libsodium only seems to support the hex format. 

I'm guessing this would be easy to add in, e.g. to support "urlsafebase64" as well as "text" and "hex", and would add that myself if this was ordinary javascript, but I haven't yet figured out the emscripten process, so haven't really got a clue how to make changes/bug-fixes.

**Comment by mitra42** [comment]
More investigation shows "base64" is supported in dist/browsers/combined/sodium.js but not in sodium.min.js and not documented in README.md.  And the URLSafe variant isn't support. I've added "urlsafebase64" to sodium.js and created a Pull Request. Appreciate any help with that.

**Comment by jedisct1** [comment]
I'm usually quite against base64 for anything related to cryptography, as it is sadly common to think that base64 is a form of encryption. There are also many ways to directly use binary data without requiring base64.

But well, things that absolutely require JSON and can't refer to additional sections remain a decent use case for that.

**Comment by mitra42** [comment]
Sure - using base64 is not a form of encryption, but that isn't what we are talking about here. Its turning binary data (keys, encrypted data, signatures) into something that can be moved around in text files, json files etc.

Importantly one advantage of Sodium is that its cross-platform, so we'll be using common functions between a python based system (using PyNaCl) and a Javascript based system (using LibSodium) so its also import to have a cross-platform way to know the ascii representation of the binary is consistent between the encrypter and encryptee. The C library and PyNaCl have the nice concept of an encoder, and so does LibSodium (except for missing out the urlsafebase64 (and not documenting the "base64" that was already there.)

I created a Pull request - first time I've done that (I'm familiar with GIT, but on a bare repository, rather than GitHub) did I do it correctly ?

**Comment by mitra42** [comment]
Hi - was there some reason the Pull request implementing this didn't get merged ? It would be great to have the support in the standard node package rather than having to special case it.

**Comment by jedisct1** [comment]
Maybe in the next libsodium version, as other languages may want this as well.

**Comment by mitra42** [comment]
ok - thanks - we are about to push a new Open Source project that "requires" libsodium-wrappers, but I guess we'll have to figure out how to have it require my fork of it instead.
