### ISSUE TITLE
Bump for bower verseion

### ISSUE THREAD

**Issue by kstewart83** [jedisct1/libsodium.js#9]
Thanks for working on such an awesome project!

It looks like you recently updated to include 1.0.3 support (I'm looking to use the seal/unseal operations, so this is much appreciated). I think the bower files need a version bump from 0.2.5 to 0.2.6 to reflect the change. I'll use the raw js files for now, but it would be nice to have bower grab the new version.

**Comment by jedisct1** [comment]
Hi!

I intend to bump it after support for `crypto_seal` is added to the high-level wrappers.

**Comment by jedisct1** [comment]
Done!
