### ISSUE TITLE
Missing "sodium.js" in Bower "dist/browsers-sumo/combined"

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#90]
I can see that there is a [dist/browsers-sumo/combined/sodium.js](https://github.com/jedisct1/libsodium.js/tree/master/dist/browsers-sumo/combined/sodium.js) file, however this one is not distributed with Bower (`bower install libsodium.js`). Can you please add it?

**Screenshot**

![Screenshot](https://cloud.githubusercontent.com/assets/469989/25726695/ab8e18d2-3125-11e7-8bea-234aaa4a9127.PNG)

**Comment by bennyn** [comment]
Any updates here? We could really benefit from it.

**Comment by jedisct1** [comment]
Looks like Bower doesn't handle symlinks.

Might be fixed in 785c08a592096d1fd088ddb9ac1118103ce8a330

**Comment by bennyn** [comment]
Issue has been solved with libsodium v0.5.4, see: https://github.com/wireapp/wire-webapp/pull/1605 :)
