### ISSUE TITLE
Strangeness in "seed" functions

### ISSUE THREAD

**Issue by mitra42** [jedisct1/libsodium.js#91]
The seed function API looks a bit weird, e.g. in
`sodium.crypto_box_seed_keypair(seed, "hex");`
The "hex" is interpreted as an encoding on the output of the function, but this doesn't make a lot of sense since the output is supposed to be able to be fed to an encrypt function ?  

In the broadly similar PyNaCl bindings this would be done with.
`PrivateKey(seed, nacl.encoding.HexEncoder`
which treats the encoding completely differently, in this case it means "seed" is in hex. 

Its simple to work around - you have to do a "from_hex(seed)" but its confusing and took me quite a while to figure out this was what was happening. Wouldnt it make more sense for the keys to always be raw (Ubyte8). So that the encoder in my first example is applied to the input and if you want a hex output this would be  for example. boxkey.privateKey.to_hex()

I haven't checked any of the other javascript bindings to see how they handle this.

**Comment by mitra42** [comment]
There is a potentially related issue in that there doesnt seem to be a way to consistently round-trip a seed into a PrivateKey and out e.g. 
```
            let seedstr = "01234567890123456789012345678901"
            let seed = sodium.from_string(seedstr);
            console.log(seed);
            console.log(sodium.to_string(seed));   // Works - matches seedstr
            let boxkey = sodium.crypto_box_seed_keypair(seed);
            console.log(boxkey.privateKey); // Doesnt match seed
```
In the PyNaCl bindings, you can use a seed to create a Key, and then get that seed back (in order to exchange it for example). No such round-trip appears to exist in libsodium.  

If it shouldn't exist for crypto reasons - then maybe its the PyNaCl bindings that are odd - either way it doesn't seem to be possible to use the same Seed on the Javascript and Python bindings to generate the keys to allow communications between a JS and Python instance.

**Comment by jedisct1** [comment]
The optional, extra parameter, always conditions the output format, for all available functions.

This is an optional shortcut. For clarity, using the more explicit `to_hex` and `from_hex` functions instead is highly recommended.

I'm going to update the examples in the documentation to use these functions.

The seed required by `crypto_box_seed_keypair()` is not a private key. The length is not guaranteed to be the same, and even when it is the case, there are no guarantees that all possible values could be directly used as valid or secure secret keys.

The seed is what the key pair is derived from. A given seed will always produce the same key pair.

It is a one-way function; there are no efficient ways to find a valid seed given a secret key. Which is considered good practice: unless your protocol actually needs it, one shouldn't be able to access the key material used to generate secret keys.

A typical use case for the seed is to derive a key pair from a password or from another key. But once you have a secret key, the seed should never be needed again. If the secret key has to be shared, you can share it directly.
