### ISSUE TITLE
New emscripten features

### ISSUE THREAD

**Issue by buu700** [jedisct1/libsodium.js#94]
I've recently added two features to emscripten that would be useful here, particularly concerning WebAssembly support.

(They aren't specific to wasm, but were needed to implement the pattern I chose to use in upgrading [mceliece.js](https://github.com/cyph/mceliece.js), [ntru.js](https://github.com/cyph/ntru.js), [rlwe.js](https://github.com/cyph/rlwe.js), [sidh.js](https://github.com/cyph/sidh.js), [sphincs.js](https://github.com/cyph/sphincs.js), and [xkcd-passphrase](https://github.com/cyph/xkcd-passphrase) two weeks ago.)

* https://github.com/kripken/emscripten/pull/5357 (just merged): adds a `Module.onAbort` callback

  - This is needed for detecting failure of asynchronous wasm compilation (`WebAssembly.instantiate`) and falling back to asm.js, since [just checking for the availability of wasm functionality isn't sufficient](https://github.com/WebAssembly/design/issues/1092#issuecomment-310433517).

* https://github.com/kripken/emscripten/pull/5296 (on track to be merged soon): adds an `-s SINGLE_FILE=1` flag that embeds all subresources as base64 strings (mem init file, wasm binary, etc.)

  - With this, the wasm version of libsodium.js can remain as a single JS file just like the asm.js version. (It also replaces the previous `--memory-init-file 0` implementation with this more efficient encoding.)

I haven't followed the work that's gone into implementing WebAssembly in libsodium.js up until now, but as far as how I implemented WebAssembly in those libraries, the pattern I used looks more or less like this (not exactly, but same basic idea):

```
${preJS}

try {
    await new Promise((resolve, reject) => {
        var Module = {onRuntimeInitialized: resolve, onAbort: reject};
        ${wasmBuild}
    });
}
catch (_) {
    ${asmjsBuild} // compiled with -Oz, "use asm" stripped to prevent redundant AOT compilation
}

${postJS}
```

(As a side benefit, with asm.js becoming a second-class citizen, it's also now safe to run the whole output through uglifyjs mangling and compression.)

The other change I had to make to account for wasm compilation being asynchronous was to convert every field and method into a Promise. For libsodium.js, it could alternatively make more sense to keep the existing API surface synchronous and just expose an "is ready" Promise and/or callback.

**Comment by jedisct1** [comment]
Support for WebAssembly has been added. It's ugly and hacky, so all improvements would be very welcome!

I won't be able to work on this any more in a near future.

**Comment by buu700** [comment]
Awesome! In that case, I'll just test it out with that new SINGLE_FILE emscripten flag and submit a PR if there are no issues.
