### ISSUE TITLE
Unable to install v0.5.2 via Bower

### ISSUE THREAD

**Issue by bennyn** [jedisct1/libsodium.js#97]
I wanted to consume `"libsodium.js": "0.5.2"` via Bower but it gives the following error:

>  code: EMALFORMED
    details: Unexpected string in JSON at position 792
    data: [object Object]

I think this is because [this fix](https://github.com/jedisct1/libsodium.js/commit/08d5b7b50f1f7503b21e2f7dac8014da1c68d879) isn't part of the v0.5.2 release, am I right?

**Comment by jedisct1** [comment]
Yes :(

**Comment by bennyn** [comment]
These things just happen... :) Can you please make a new release with the fix included?

**Comment by jedisct1** [comment]
I'd like to release 0.6.0 soon, but since there are some major internal changes due to WebAssembly support, I'd love your feedback on it.
If you think it's fine to push it to Bower/NPM, I'll do it shortly. If not, I'll maintain the 0.5 branch for a bit.

**Comment by bennyn** [comment]
@jedisct1 Can you specify what (and how) we should test with v0.6? We are also eagerly awaiting WebAssembly support. 🤗 

For the time being I would still appreciate a new 0.5 version which can be used with Bower.

**Comment by jedisct1** [comment]
Hi Benny!

Just check out the current code in the master branch!

**Comment by bennyn** [comment]
I tried to lock libsodium.js to 5ae7f98ca97d3de6329690f31c00a72e07b25d7e (from your master branch) but it doesn't seem to work:

![unbenannt](https://user-images.githubusercontent.com/469989/29372233-d56ebbc6-82aa-11e7-9bab-3622fa9d5960.PNG)

**Comment by jedisct1** [comment]
Try without bower?

The file names have changed a bit, too (due to Wasm) https://github.com/jedisct1/libsodium.js/tree/master/dist

**Comment by bennyn** [comment]
Are we still talking about the broken v0.5 release? Bower is part of our build system and we don't want to skip it for our production builds.

**Comment by jedisct1** [comment]
Just published a 0.5.3 version on Bower :)

**Comment by bennyn** [comment]
Thanks publishing it but v0.5.3 is still missing the `dist/browsers-sumo/combined/sodium.js` file. See: https://github.com/jedisct1/libsodium.js/issues/90 😢

**Comment by jedisct1** [comment]
Try 0.5.4, maybe? :)

Sorry, I never use bower.

**Comment by bennyn** [comment]
**Great!** Version 0.5.4 works with Bower. Now the related npm packages (like https://www.npmjs.com/package/libsodium-wrappers-sumo) need to get updated because these are still on v0.5.2. 🙈

**Comment by bennyn** [comment]
Hey. 😃  Hope everything is fine!? 

Can you please sync the version numbers on Bower (currently at 0.5.4) and npmjs (currently at 0.5.2)?

**Comment by bennyn** [comment]
Thanks for releasing v0.5.4 on npmjs! 😊 https://github.com/wireapp/proteus.js/pull/68
